### ISSUE TITLE
Throw exception when there is a cache miss with acquire token silent

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-java#100]
Return value for acquireTokenSilent should never be null. It should either be: 
- IAuthenticationResult in case of successful request
- Exception is thrown if there is a cache miss or STS returns an error (`MsalUiRequiredException`)

**Comment by jmprieur** [comment]
@sangonzal : I was wondering about this: this is the pattern for the other MSAL libraries, but was not surfaced for msal4j.
I would imagine we'd want that for the final public preview? @SomkaPe ?
cc: @henrik-me

**Comment by sangonzal** [comment]
@jmprieur Yes this will be fixed before public preview. @SomkaPe has agreed to make the fix.
