### ISSUE TITLE
AsymmetricKeyCredentials should not user internal, proprietary API

### ISSUE THREAD

**Issue by JonathanGiles** [AzureAD/microsoft-authentication-library-for-java#11]
The AsymmetricKeyCredentials class currently uses `sun.security.util.Length`, but this is not public API and it is not guaranteed to be included in all JDKs, and is unavailable after JDK 9 due to the introduction of modules. Usage of API in the `sun.*` namespace is not recommended.

**Comment by sangonzal** [comment]
@JonathanGiles Thanks for bringing this up, I have added a task to the backlog to address this issue.
