### ISSUE TITLE
How to validate access_token on backend

### ISSUE THREAD

**Issue by hunao0221** [AzureAD/microsoft-authentication-library-for-java#111]
Hi, I request a access_token and refresh_token from https://login.microsoftonline.com/{tenant}/oauth2/token on the backend which base on SpringBoot and response to frontend.

and then frontend send a request to backend api with access_token, the question is how to validate access_token on the backend ? and we alse use Sring Security.

At the moment I did't found any suggestions.

I'm looking forward to your reply as soon as possible.

**Comment by SomkaPe** [comment]
Msal is client SDK, so used for requesting tokens for resources,  To validate tokens on resource side you can use Spring security or other corresponding libraries

**Comment by sangonzal** [comment]
@hunao0221 We are in the process of writing a sample with a README.md on how to validate tokens with Spring security. In the meantime, take a look at the [MSAL OBO sample](https://github.com/AzureAD/microsoft-authentication-library-for-java/tree/dev/src/samples/msal-obo-sample/src/main/java/com/microsoft/azure/msalobosample). Spring security is used to validate request coming into ApiController. Spring security is configured in [SecurityResourceServerConfig](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/samples/msal-obo-sample/src/main/java/com/microsoft/azure/msalobosample/SecurityResourceServerConfig.java)
