### ISSUE TITLE
Azure AD B2C acquire access token error

### ISSUE THREAD

**Issue by PengleiShi** [AzureAD/microsoft-authentication-library-for-java#112]
I run this demo 
`https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/samples/public-client/B2CFlow.java`

CompletableFuture<IAuthenticationResult> future = app.acquireToken(

                UserNamePasswordParameters.builder(
                        Collections.singleton(TestData.LAB_DEFAULT_B2C_SCOPE),
                        userName,
                        password.toCharArray()).build());
but what does TestData.LAB_DEFAULT_B2C_SCOPE mean? where can i get this value in azure portal?

**Comment by jmprieur** [comment]
@PengleiShi we are in the process of creating samples with README.md s
meanwhile you can probably get inspired by this sample: https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi. It's for .NET, not Java, but the app registration is the same

**Comment by PengleiShi** [comment]
@jmprieur thanks a lot. In fact, i have an azure ad b2c app, which users can log-in according to b2c user flow on browser.  But i need enable user's authentication without interactive log-in, my app will  send username and credential to azure which will authenticate the user in my java code. I konw it is workable for app registered in Azure AD,  like this one https://github.com/Azure-Samples/active-directory-java-native-headless, is there any similiar soulution for app registered in Azure AD B2C?

**Comment by jmprieur** [comment]
@PengleiShi : did you have a look at this sample: https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/samples/public-client/UsernamePasswordFlow.java ?

**Comment by PengleiShi** [comment]
Thanks, i will look at that one. And i found a solution which finishes programmatic or “headless” authentication to Azure AD B2C using only a username and password. https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-ropc. I will compare the two solutions.

**Comment by sangonzal** [comment]
Closing this issue. Feel free to reopen if you have any more questions.
