### ISSUE TITLE
Support for ADFS authority in msal4j

### ISSUE THREAD

**Issue by mukulb82** [AzureAD/microsoft-authentication-library-for-java#113]
Hello MSAL4J team,

i am getting below error when i am trying to cleate "ConfidentialClientApplication" using client id and client secret for "ADFS" authority:
"**Unsupported authority type. Please use AAD authority**".

i need to use only ADFS as authentication server.

i know we have **ADFSAuthority** class in the msal4j JAR but "ClientApplicationBase" class doesnt provide have code for "ADFS" authority type. i am using msal4j - "0.5.0-preview" maven dependency.

kindly help and advice. Is there any updated library?

Thanks,
Mukul

**Comment by sangonzal** [comment]
Hi @mukulb82 MSAL4J currently does not support talking directly to AD FS. We have an [ADFS support Wiki](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Active-Directory-Federation-Services-(AD-FS)-Support) page with more details. 

We plan to add support for ADFS 2019 in an upcoming release. Here is the [GitHub issue](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/51) tracking that work

**Comment by mukulb82** [comment]
@sangonzal Thanks for the response. As I am working on application using MSAL4J where I would need to talk to ADFS, what are approximate timelines when this implementation will be available?

Also, could you point me to alternate solution or library or other ways for implementing it ? I am able to receive response from ADFS by directly calling the ADFS server through REST client app.

How suitable would it be if I create a Apache HTTP's APIs REST client (using CloseableHttpClient class from "**org.apache.httpcomponents**" maven dependency ) and acquire token?

Thanks,
Mukul

**Comment by sangonzal** [comment]
@mukulb82 What version of ADFS are you using?

**Comment by mukulb82** [comment]
@sangonzal We are trying to connect to ADFS v4 in windows 2016.
