### ISSUE TITLE
Acquiring token using Username/Password in public client applications

### ISSUE THREAD

**Issue by PengleiShi** [AzureAD/microsoft-authentication-library-for-java#114]
My Azure AD has intergrated with a third-party IDP using SAML for sso, just like this:  https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-saml-idp
The third party IDP will finish the authentication. This solution is workable for web-based applications.
Now, i need to finish this authentication in a programmatic way. if i use ADAL or MSAL, Could i get an access token from Azure using username and password  without interactive log-in? just like this: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token
My Azure AD do not store passwords, and i do not need sso,  i jsut want to get access token in my code.

**Comment by henrik-me** [comment]
Any reason you need to use user name and password? It basically means you will not be able to take advantage of MFA and CA and other security mechanisms.

**Comment by PengleiShi** [comment]
@henrik-me hi, this is because, my datasource connector for Power BI can not use a interactive log-in with AAD to authenticate AAD accounts, that is, when users log in my connector, my connector can't redirect to MS login-in page. For a third-party connector, Power BI has the limit.
