### ISSUE TITLE
Gson is used as JSON parser

### ISSUE THREAD

**Issue by JonathanGiles** [AzureAD/microsoft-authentication-library-for-java#12]
The azure-sdk-for-java project is trying to standardise on using Jackson as its JSON library of choice. Is it possible to discuss the possibility of this library also standardising on this library, or is Gson a set-in-stone decision now?

**Comment by sangonzal** [comment]
Gson is not set-in-stone, happy to discuss what it would take to move over to Jackson.

**Comment by SomkaPe** [comment]
Lets discuss in teams or by email the reasons for this standardisation.

**Comment by henrik-me** [comment]
Re-opening per discussion with Jonathan
