### ISSUE TITLE
How to use client credentials with Azure AD B2C?

### ISSUE THREAD

**Issue by wimdeblauwe** [AzureAD/microsoft-authentication-library-for-java#125]
I want to programmatically add/remove users from the Azure AD B2C directory I have. I have made my application 'User administrator'. I also created a client secret in the 'Certificates & secrets' section of my app.

In my Spring boot application, I created this bean:

```
    @Bean
    public ConfidentialClientApplication clientApplication() throws MalformedURLException {

        return ConfidentialClientApplication.builder("<application-id>",
                                                     ClientCredentialFactory
                                                             .createFromSecret("<client-secret>"))
                                            .b2cAuthority("https://mycompb2ctestorg.b2clogin.com/tfp/oauth2/nativeclient")
                                            .build();

    }
```

Using this bean, I try to get an access_token:

```
        CompletableFuture<IAuthenticationResult> future = clientApplication
                .acquireToken(ClientCredentialParameters.builder(Set.of("Directory.ReadWrite.All")).build());
        future.handle((authenticationResult, throwable) -> {
            if( throwable != null ) {
                System.out.println("throwable = " + throwable);
                return null;
            }

            String accessToken = authenticationResult.accessToken();
            System.out.println("accessToken = " + accessToken);
            return null;
        });
```

When I run this, I get an exception:
```
java.util.concurrent.CompletionException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: 
Expected BEGIN_OBJECT but was STRING at line 1 column 1
```

When I debug, I see that the JSON is not JSON, but a HTML page with this body:
```
    <body>
        <div id="header"><h1>Server Error</h1></div>
        <div id="content">
            <div class="content-container"><fieldset>
                <h2>404 - File or directory not found.</h2>
                <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
            </fieldset></div>
        </div>
    </body>
```

What am I doing wrong?

**Comment by sangonzal** [comment]
Hi @wimdeblauwe, I think there are two separate issues here: 

1) It seems that you are hitting an endpoint that it not valid - I would check that the authority that you are passing in is correct. The B2C authority format should be `https://{your-tenant-name}.b2clogin.com/tfp/{your-tenant-ID}/{policyname}`. In you case it should be something along the lines of `"https://mycompb2ctestorg.b2clogin.com/tfp/mycompb2ctestorg.onmicros.com/{Policy}"`. The {Policy} would be a policy that you created on the Azure AD B2C portal. 

2) B2C does not support client credentials grant (acquiring a token for an application, instead of an user). https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-apps#daemonsserver-side-applications

You can either go with [Authorization Code Grant (this requires user interaction)](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Acquiring-Tokens-with-Authorization-codes) or [UsernamePassword Grant](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Acquiring-Tokens-with-username-and-password). Although use of username password is usually not recommended, it seems that based on your scenario this is what are looking for.

**Comment by wimdeblauwe** [comment]
I can confirm that fixing the B2C authority format to `https://mycompb2ctestorg.b2clogin.com/tfp/mycompb2ctestorg.onmicrosoft.com/B2C_1_ropc_flow` makes the HTML error message go away. I now get:
```
com.microsoft.aad.msal4j.MsalServiceException: AADB2C90086: The supplied grant_type [client_credentials] is not supported.
```

which is to be expected given you remark 2.

I don't quite understand what the recommended approach is for mobile applications with B2C if we want to provide an own UI for creating an account in our mobile application. Is the best thing to do to open the mobile browser from the app to allow a user to create an account there? But then how to return to your app? Seems like a UX nightmare compared to just having a form in your app to allow the user to create an account.

**Comment by wimdeblauwe** [comment]
I am now trying the UsernamePassword grant. For this I had to switch from a `ConfidentialClientApplication` to a `PublicClientApplication` (not sure what the actual impact of that is).

Then I am trying:
```
        UserNamePasswordParameters parameters = UserNamePasswordParameters.builder(Set.of("Directory.ReadWrite.All"),
                                                                                   "<application-id>",
                                                                                   "<client-secret>".toCharArray())
                                                                     .build();
        CompletableFuture<IAuthenticationResult> future = clientApplication
                .acquireToken(parameters);
```

But that gives:
```
The scope 'Directory.ReadWrite.All' provided in the request is not supported.
```

**Comment by sangonzal** [comment]
@wimdeblauwe Could you describe exactly what your scenario looks like? Above you mention that you have a spring boot application and also a mobile application - How are these related? 

> "I am now trying the UsernamePassword grant. For this I had to switch from a `ConfidentialClientApplication` to a `PublicClientApplication` (not sure what the actual impact of that is)."

[This page](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Client-Applications) describes the difference in between PublicClientApplications and ConfidentialClientApplications.

**Comment by wimdeblauwe** [comment]
There is a mobile application where users can log on and create accounts. The mobile application mainly communicates with the Spring Boot application that exposes a REST API that is secured with Spring Security. I want to use Azure as the authorization server. So for login, the mobile app will do a REST call to Azure to get a JWT token and use that JWT token in the `Authorization` header towards the Spring Boot application.

I have this working already with users that I manually create in Azure AD B2C. Now I want to be able to implement a user registering via the mobile application. For that, the Spring Boot app will expose an unsecured endpoint that allows the mobile app to do a POST call with the users' email and password for the new user account. When this POST arrives at the Spring Boot application, it needs to call Azure AD B2C to create that user account. If that succeeds, the Spring Boot application can respond to the mobile app that the account is created and the mobile app can use Azure AD B2C to get a token for this new user.

So I am now investigating how the Spring Boot application can do a call to Azure AD B2C to create a user account in a secure way.

**Comment by sangonzal** [comment]
Thanks for clarifying. I think it would make more sense here to have the mobile application calling Azure AD B2C directly. You can use either MSAL Android and MSAL IOS to call AzureAD B2C with a sigin/signup policy. This will signup the user and create an account in the B2C tenant. Azure AD B2C here handles the singin/signup UI, and redirects back to your app after it is done. 

[MSAL Android B2C documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-b2c) and [MSAL IOS B2C documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/config-authority#b2c).

**Comment by sangonzal** [comment]
@wimdeblauwe did that solve you problem?

**Comment by wimdeblauwe** [comment]
No, we want to have our own UI and now the Azure AD B2C UI.

**Comment by wimdeblauwe** [comment]
FYI: I have successfully used ADAL4J to get a client_credentials token that allows me to create a user:

```
import com.microsoft.aad.adal4j.AuthenticationCallback;
import com.microsoft.aad.adal4j.AuthenticationContext;
import com.microsoft.aad.adal4j.AuthenticationResult;
import com.microsoft.aad.adal4j.ClientCredential;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.*;
import org.springframework.stereotype.Component;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.RestTemplate;

import java.net.MalformedURLException;
import java.util.Collections;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;

@Component
public class AzureAdB2cAuthorizationServerGateway implements AuthorizationServerGateway {
    private static final Logger LOGGER = LoggerFactory.getLogger(AzureAdB2cAuthorizationServerGateway.class);

    private final SecuritySettings securitySettings;
    private final ExecutorService executorService;
    private final RestTemplate restTemplate;

    public AzureAdB2cAuthorizationServerGateway(SecuritySettings securitySettings,
                                                ExecutorService executorService,
                                                RestTemplate restTemplate) {
        this.securitySettings = securitySettings;
        this.executorService = executorService;
        this.restTemplate = restTemplate;
    }

    @Override
    public void createUser(UserCreationParameters parameters) throws AuthorizationServerGatewayException {
        try {
            String tenant = securitySettings.getTenant();
            AuthenticationContext authenticationContext = new AuthenticationContext(
                    securitySettings.getAuthorityUrlPrefix() + tenant, true, executorService);

            ClientCredential clientCredential = new ClientCredential(securitySettings.getClientId(),
                                                                     securitySettings.getClientSecret());
            CountDownLatch latch = new CountDownLatch(1);
            AtomicReference<Throwable> throwableReference = new AtomicReference<>();
            authenticationContext.acquireToken(securitySettings.getGraphUrlResource(),
                                               clientCredential,
                                               new DoCreateUserAuthenticationCallback(parameters,
                                                                                      tenant,
                                                                                      latch,
                                                                                      throwableReference));

            try {
                boolean success = latch.await(5, TimeUnit.SECONDS);
                if (!success) {
                    throw new AuthorizationServerGatewayException(
                            "There was a timeout trying to create the user with email " + parameters.getEmail());
                } else {
                    Throwable throwable = throwableReference.get();
                    if (throwable != null) {
                        String errorMessage = "Error creating user with email " + parameters.getEmail();
                        if (throwable instanceof HttpClientErrorException) {
                            errorMessage = errorMessage + "\nResponse: " + ((HttpClientErrorException) throwable)
                                    .getResponseBodyAsString();
                        }
                        throw new AuthorizationServerGatewayException(errorMessage, throwable);
                    }
                }
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new AuthorizationServerGatewayException(
                        "Got interrupted waiting on user creation of user with email " + parameters.getEmail());
            }
        } catch (MalformedURLException e) {
            throw new AuthorizationServerGatewayException(e);
        }


    }

    private class DoCreateUserAuthenticationCallback implements AuthenticationCallback<AuthenticationResult> {
        private final UserCreationParameters parameters;
        private final String tenant;
        private final CountDownLatch latch;
        private final AtomicReference<Throwable> throwableReference;

        DoCreateUserAuthenticationCallback(UserCreationParameters parameters, String tenant, CountDownLatch latch, AtomicReference<Throwable> throwableReference) {
            this.parameters = parameters;
            this.tenant = tenant;
            this.latch = latch;
            this.throwableReference = throwableReference;
        }

        @Override
        public void onSuccess(AuthenticationResult result) {
            String accessToken = result.getAccessToken();

            AzureAdB2cCreateUserParameters azureParameters = AzureAdB2cCreateUserParameters
                    .fromUserCreationParameters(parameters);
            HttpHeaders headers = new HttpHeaders();
            headers.setAccept(Collections.singletonList(MediaType.APPLICATION_JSON));
            headers.add(HttpHeaders.AUTHORIZATION, "Bearer " + accessToken);
            HttpEntity<AzureAdB2cCreateUserParameters> httpEntity = new HttpEntity<>(
                    azureParameters,
                    headers);
            ResponseEntity<String> response = restTemplate.exchange(
                    securitySettings.getGraphUrl(),
                    HttpMethod.POST,
                    httpEntity,
                    String.class,
                    tenant);
            if (response.getStatusCode() == HttpStatus.CREATED) {
                LOGGER.debug("User created : {}", response);
                latch.countDown();
            } else {
                LOGGER.error("Error creating user: " + response
                        .getStatusCode() + "\n" + response
                        .toString());
            }
        }

        @Override
        public void onFailure(Throwable throwable) {
            throwableReference.set(throwable);
            LOGGER.error("Error creating user with email " + parameters.getEmail(),
                         throwable);
            latch.countDown();
        }
    }
}
```

`SecuritySettings` is a configuration bean from Spring Boot that maps the following properties:
```
my-application.authority-url-prefix=https://login.microsoftonline.com/
my-application.graph-url-resource=https://graph.windows.net
my-application.graph-url=https://graph.windows.net/{tenant}/users?api-version=1.6
my-application.tenant=mytesttenant.onmicrosoft.com
my-application.client-id=CLIENT_ID_UUID
my-application.client-secret=ADD_CLIENT_SECRET_HERE
```

Is it possible to do exactly the same with MSAL4J?

**Comment by jmprieur** [comment]
@wimdeblauwe did you have a look at this article ?
https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet?tabs=applications

**Comment by wimdeblauwe** [comment]
But it explicitly states:
> For now, you need to use ADAL (not MSAL) to get access tokens. (You can also send protocol messages directly, without using a library.)

**Comment by jmprieur** [comment]
@wimdeblauwe: thanks for the heads-up. This will also work with MSAL and the Microsoft Graph, I'd think. @mmacy : shouldn't we update the article to use MSAL?

**Comment by mmacy** [comment]
@jmprieur Yes, I'll remove that line today. To note, this article will be included as part of a larger update to switch over to MS Graph in several documents, though that's going to be a bit before that's completed.

**Comment by wimdeblauwe** [comment]
Looking forward to the updated docs, because I have unable to get it working with MSAL so far. Maybe another tip: some of the chapters on the page show the HTTP call itself. It would be good to add that for everything as that really helps to quickly try some things to be sure the Azure AD B2C settings (in the cloud so to say) themselves are correct.

**Comment by sangonzal** [comment]
@wimdeblauwe This should work in MSAL. What error are you running into?

When using MSAL: 
1) Instead of using `.b2cAuthority`, use `.authority()` and use "https://login.microsoftonline.com/mytesttenant.onmicrosoft.com"
2)  Change the value you are using for resource to "https://graph.windows.net/.default" and pass this in to scope.

```
        ConfidentialClientApplication app = ConfidentialClientApplication.builder(
                "APP_ID",
                ClientCredentialFactory.createFromSecret("CLIENT_SECRET"))
                .authority("https://login.microsoftonline.com/mytesttenant.onmicrosoft.com")
                .build();

        ClientCredentialParameters clientCredentialParam = ClientCredentialParameters.builder(
                Collections.singleton("https://graph.windows.net/.default"))
                .build();
  IAuthenticationResult authenticationResult = app.acquireToken(clientCredentialParam).join();

```

**Comment by wimdeblauwe** [comment]
Thanks for that. It works indeed using the code you presented here. Thanks!

**Comment by DaveBrickley** [comment]
@sangonzal - I am trying to do similar but I want to authenticate against the B2C directory itself

Basically I want a generic token for 'unregistered' users

How would the second part of the example above look if not using graph pls?
