### ISSUE TITLE
pom.xml file need review

### ISSUE THREAD

**Issue by JonathanGiles** [AzureAD/microsoft-authentication-library-for-java#13]
The pom.xml file in this project needs review - there are a number of issues I would like to discuss. Primarily, the dependencies listed in the pom.xml file seem to be more than what is required. For example, I'm not clear that javax.servlet is required. Additionally, almost all 'test scope' dependencies aren't actually scoped for test only. 

Guava is imported almost needlessly - it appears to be only used in one class where it could be trivially replaced.

Please feel free to ping me at jonathan.giles@microsoft.com so that we can work together to improve this pom file.

**Comment by sangonzal** [comment]
@JonathanGiles There are certain cases where we have to import dependencies due certain requirements (For instance in the case of Guava, it is required for Selenium:  https://github.com/SeleniumHQ/selenium/issues/3880 ).  Having said that, I agree that we should explore ways of improving the Pom. I will reach out to discuss any ideas you might have regarding #11, #12, #13

**Comment by SomkaPe** [comment]
thank you for pointing that out, pom.xml was reviewed
