### ISSUE TITLE
Unexpected 'java.lang.StackOverflowError' exception in TokenCache.java class

### ISSUE THREAD

**Issue by narayanagowdas** [AzureAD/microsoft-authentication-library-for-java#130]
Hi,

I'm getting  'java.lang.StackOverflowError' exception from authenticationResult.account() when both accountCacheEntity and account are null;
 https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/6b184088b59a07ed4e54a538c25c90d3067fac08/src/main/java/com/microsoft/aad/msal4j/TokenCache.java#L237

### Scenario causing the issue is,

- Trying to fetch token using ConfidentialClientApplication **acquireToken(ClientCredentialParameters parameters)** method.

- Able to successfully fetch the token by passing ClientCredentialParameters. Responses received are
**httpResponse** :{"token_type":"Bearer","expires_in":3600,"ext_expires_in":3600,"access_token":"<ACTUAL_TOKEN>"}
**TokenResponse** : tokens = {"access_token":"<ACTUAL_TOKEN>","id_token":"","token_type":"Bearer","expires_in":3600}

- The **AuthenticationResult** received in the TokenRequest.java class contains valid values for "accessToken", "extExpiresOn", "expiresOn" and "environment". All other fields including accountCacheEntity and account are null.
https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/6b184088b59a07ed4e54a538c25c90d3067fac08/src/main/java/com/microsoft/aad/msal4j/TokenRequest.java#L113

- When accountCacheEntity and account is null, authenticationResult.account() in the TokenCache.java class is throwing 'java.lang.StackOverflowError' for account field. 
<img width="1061" alt="Screen Shot 2019-11-21 at 10 45 25 PM" src="https://user-images.githubusercontent.com/6948613/69360503-b2194780-0cb0-11ea-80a6-0dbe56032547.png">

Is this an open issue? or please let me know if I am missing something. Thanks in advance.

**Comment by SomkaPe** [comment]
account field is "lazy" initialized, so IDE can not evaluate it, null will be returned if you actually call it

**Comment by narayanagowdas** [comment]
@SomkaPe Thanks for the clarification. 
With your explanation, closing the ticket as not an issue.
