### ISSUE TITLE
Token cache ignores guest user entries

### ISSUE THREAD

**Issue by jianghaolu** [AzureAD/microsoft-authentication-library-for-java#139]
I have a user with access to 2 tenants - one is the home tenant, the other as a guest user.

This is what it looks like in the token cache:
![image](https://user-images.githubusercontent.com/2320445/70284270-5c48a300-1778-11ea-88f8-b66fa72db82e.png)

I'm trying to login silently with this account in the shared token cache access the second tenant as the guest user:

```java
String tenantId = "c32df355-c3c7-49eb-8718-dcf53254b0c8";
String clientId = "04b07795-8ddb-461a-bbee-02f9e1bf7b46";
List<String> scopes = Arrays.asList("https://management.azure.com/.default");

String authorityUrl = "https://login.microsoftonline.com/organizations/" + tenantId;

PublicClientApplication pubClient = PublicClientApplication.builder(clientId)
        .authority(authorityUrl)
        .build();

IAccount requestedAccount = getAccountFromCache(pubClient.getAccounts().get(), username);

SilentParameters params = SilentParameters.builder(
        new HashSet<>(scopes), requestedAccount)
    .authorityUrl(authorityUrl)
    .build();

CompletableFuture<IAuthenticationResult> future = pubClient.acquireTokenSilently(params);
```

This code throws error: Exception in thread "main" com.azure.core.exception.HttpResponseException: Status code 401, "{"error":{"code":"Unauthorized","message":"AKV10032: Invalid issuer. Expected one of https://sts.windows.net/c32df355-c3c7-49eb-8718-dcf53254b0c8/, https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/, https://sts.windows.net/e2d54eb5-3869-4f70-8578-dee5fc7331f4/, found https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/."}}"

Digging into `TokenCache.java`, it seems like we are looking for the first cached entry with a an home account id match (https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/main/java/com/microsoft/aad/msal4j/TokenCache.java#L438): 
```java
    Optional<AccountCacheEntity> getAccountCacheEntity
            (IAccount account, Set<String> environmentAliases) {

        return accounts.values().stream().filter
                (acc -> acc.homeAccountId.equals(account.homeAccountId()) &&
                        environmentAliases.contains(acc.environment)
                ).findAny();
    }
```

when we should really find the entry whose realm equals the tenant we are trying to access. Unfortunately, home account id doesn't include tenant **we are accessing** but only has info of the tenant the account **resides**. Other than that, there's no information about the tenant we are accessing in the interface `IAccount`.

Proposed fix: we need to include the realm information from the token cache in `IAccount` so that we will be using the correct cached account to refresh tokens.

**Comment by SomkaPe** [comment]
" String authorityUrl = "https://login.microsoftonline.com/organizations/" + tenantId  " - is not
correct format of tenant specific authority, 
should be 
String authorityUrl = "https://login.microsoftonline.com/" + tenantId

**Comment by jianghaolu** [comment]
Thanks! That does seem to be the issue. It seems like it doesn't matter which account I load from the cache, acquiring an AT to a different tenant from the RT also works.
