### ISSUE TITLE
Remove commons-codec dependency

### ISSUE THREAD

**Issue by JonathanGiles** [AzureAD/microsoft-authentication-library-for-java#145]
it's only used in three places for encoding to base64.

**Comment by henrik-me** [comment]
@JonathanGiles : what is your recommendation instead? Just ensuring we don't do it differently from what you expect.

**Comment by JonathanGiles** [comment]
In the first instance you should consider using the Java 8 `java.util.Base64` class. There is a good tutorial here: https://www.baeldung.com/java-base64-encode-and-decode

If that is not sufficient, we should explore options, but probably writing out an implementation of the one method that was being used (if I recall correctly) might be the next-best option.
