### ISSUE TITLE
Remove lombok dependency

### ISSUE THREAD

**Issue by JonathanGiles** [AzureAD/microsoft-authentication-library-for-java#146]
Hand-code the API rather than rely on Lombok trickery to have it magically created at compile time. Lombok is basically a pre-compiler hack in my humble opinion.

**Comment by JonathanGiles** [comment]
The azure-sdk team uses spotbugs and checkstyle to enforce consistency across our libraries. I'm happy to work with you to introduce this tooling into your build process too. For reference, you might want to check out the https://github.com/Azure/azure-sdk-for-java/tree/master/eng/code-quality-reports directory to see our configuration for both of these libraries.

**Comment by sangonzal** [comment]
Scope change to ‘provided’ as discussed via email.
