### ISSUE TITLE
Multitenant application has different behaivor by tenant

### ISSUE THREAD

**Issue by oscarcosta** [AzureAD/microsoft-authentication-library-for-java#167]
Hello,

I am building an Outlook Add-In which is composed by a client (React, Typescript) and a server (Java, Spring). The client runs in different versions of Outlook, i.e. desktop, web and mobile, and the server needs access to listen for new messages arriving in the customers inbox. Due to those requiments I implemented the on-behalf-of flow as described in various documents and sample applications (e.g. [active-directory-dotnet-webapi-onbehalfof-ca](https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof-ca)). Moreover, the application is intended to be multi-tenant and it does not have any permission that needs administrator authorization.

Both applications are registered in an Azure business account (domain A). I am testing the application with my Outlook email from a different domain (domain B) hosted by GoDaddy. For this account, everything is working as expected: I am able to login in the client, and it sends an access token to the server, which gets a new access token to access Microsoft Graph API.

However, when another person try to use the app with another email (domain C) hosted by an university, the on-behalf-of authentication does not work properly, as can be seen in the log:

```
2020-01-19 17:17:35,198 INFO com.microsoft.aad.msal4j.HttpHelper [Thread-35] [Correlation ID: 7d8a69dd-ac29-49bb-bb4f-91e5b91a1f26] Sent (7d8a69dd-ac29-49bb-bb4f-91e5b91a1f26) Correlation Id is not same as received (null).
2020-01-19 17:17:35,202 ERROR com.microsoft.aad.msal4j.ConfidentialClientApplication [Thread-35] [Correlation ID: 7d8a69dd-ac29-49bb-bb4f-91e5b91a1f26] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.
com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS65001: The user or administrator has not consented to use the application with ID '<SERVER_APP_ID>' named '<SERVER_APP_NAME>'. Send an interactive authorization request for this user and resource.
Trace ID: 647d6a55-c2c1-4999-99e8-ae8287291300
Correlation ID: 7d8a69dd-ac29-49bb-bb4f-91e5b91a1f26
Timestamp: 2020-01-19 19:17:35Z
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:37)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:81)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:36)
	at com.microsoft.aad.msal4j.ClientApplicationBase.acquireTokenCommon(ClientApplicationBase.java:92)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:52)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.lang.Thread.run(Thread.java:748)
```

Client dependencies:
```
"dependencies": {
  "@microsoft/office-js-helpers": "^1.0.2",
  "core-js": "^3.6.4",
  "es6-promise": "^4.2.8",
  "msal": "^1.2.1",
  "office-ui-fabric-react": "^7.83.1",
  "react": "^16.12.0",
  "react-aad-msal": "^2.3.2",
  "react-dom": "^16.12.0",
  "react-router-dom": "^5.1.2",
  "regenerator-runtime": "^0.13.3"
},
```

Client AddIn (partial) manifest:
```
<AppDomains>
  <AppDomain>https://SERVER_URL</AppDomain>
  <AppDomain>https://login.windows.net</AppDomain>
  <AppDomain>https://login.microsoftonline.com</AppDomain>
</AppDomains>
...
<WebApplicationInfo>
  <Id>CLIENT_APP_ID</Id>
  <Resource>api://SERVER_URL/CLIENT_APP_ID</Resource>
  <Scopes>
    <Scope>api://SERVER_APP_ID/access_as_user</Scope>
    <Scope>email</Scope>
    <Scope>Mail.ReadWrite</Scope>
    <Scope>MailboxSettings.ReadWrite</Scope>
    <Scope>offline_access</Scope>
    <Scope>openid</Scope>
    <Scope>profile</Scope>
    <Scope>User.Read</Scope>
  </Scopes>
</WebApplicationInfo>
```

Client authentication (partial) code:
```
const authProvider = new MsalAuthProvider({
  auth: {
    authority: 'https://login.microsoftonline.com/common',
    clientId: 'CLIENT_APP_ID',
    redirectUri: serverURL + '/taskpane.html'
  }
}, {
  scopes: [
    'api://SERVER_APP_ID/access_as_user',
    'email',
    'Mail.ReadWrite',
    'MailboxSettings.ReadWrite',
    'offline_access',
    'openid',
    'profile',
    'User.Read'
  ]
}, {
  loginType: LoginType.Popup,
  redirectUri: serverURL + '/auth.html'
})

const headers = new Headers()
headers.append('Accept', 'application/json')
headers.append('Content-Type', 'application/json')
const token = await authProvider.getAccessToken({
  scopes: [
    'api://SERVER_APP_ID/access_as_user'
  ]
})
headers.append('Authorization', 'Bearer ' + token.accessToken

return new Promise((resolve) => {
    fetch(`${this.baseURL}${url}`, {
        method: 'POST',
        headers: headers,
        body: JSON.stringify(body)
    }).then(response => response.json())
        .then(body => body != null ? resolve(body) : {})
        .catch(error => console.error(error))
})
```

Server dependencies:

```
<dependency>
	<groupId>com.microsoft.graph</groupId>
	<artifactId>microsoft-graph</artifactId>
	<version>1.7.1</version>
</dependency>
<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>msal4j</artifactId>
	<version>1.3.0</version>
</dependency>
```

Server authentication (partial) code:
```
ConfidentialClientApplication application = ConfidentialClientApplication.builder(<SERVER_APP_ID>, ClientCredentialFactory.createFromSecret(<SERVER_APP_SECRET>))
                .authority("https://login.microsoftonline.com/common/")
                .setTokenCacheAccessAspect(new TokenPersistence(cacheRepository, <USER_EMAIL>)) // user_email is used to obtain the persistent cache, if one exists
                .build();
                
String[] scopes; // email,Mail.ReadWrite,MailboxSettings.ReadWrite,offline_access,openid,profile,User.Read

String accessToken = getClientAccessToken(); // Get the Client Access Token from Security Context

OnBehalfOfParameters parameters = OnBehalfOfParameters
        .builder(Sets.newHashSet(scopes), new UserAssertion(accessToken))
        .build();
        
IAuthenticationResult auth = application.acquireToken(parameters).get();

return auth.accessToken();
```

I have been struggling with this problem for weeks and I am almost giving up the 'on-behalf-of' authentication and registering only one App in the Azure for both applications, as they share the same server and url. So, any help with this matter will be greatly appreciated.

Thanks!

**Comment by sangonzal** [comment]
Hello @oscarcosta, are you using the same client id for the client application and the server application? 

It seems you are receiving this error because the middle tier application (in your case the spring app) does not have the proper consent to call Graph. Take a look at this [page explaining consent for OBO](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow#gaining-consent-for-the-middle-tier-application). This provides multiple ways of ensuring that the middle tier application has the proper consent. 

Also given that this is a multi-tenant application, make sure you are following all of the steps [outlined in this page](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant)

**Comment by oscarcosta** [comment]
Hi  @sangonzal thanks for answering my question.

Currently we are using only one Azure App (Client ID) for both applications, since they are deployed in the same server and share the same address. With this configuration the authentication is working fine for different users. However, I believe the OBO authentication would be the correct way to implement our scenario. That is the reason I was trying to implement the OBO.

I will 'double check' these links and let you know the result.

Thanks

**Comment by sangonzal** [comment]
@oscarcosta Were you able to solve your issue?

**Comment by oscarcosta** [comment]
Hi @sangonzal, sorry I haven't had enough time to work on it those days. However I will definitely take a look on this issue this week.

**Comment by sangonzal** [comment]
@oscarcosta I'm going to close this issue. If you have any follow up questions or issues, feel free to reopen.
