### ISSUE TITLE
Multi-Factor authentication support

### ISSUE THREAD

**Issue by ulvii** [AzureAD/microsoft-authentication-library-for-java#168]
Hi team,

Does the library support MFA/any plans to add it? We are interested in some kind of a callback configuration that can be used by UIs.

**Comment by sangonzal** [comment]
Hi @ulvii, 

Yes, the library supports MFA. This will actually be handled by the UI rendered by AzureAD when you do interactive authentications. 

The team recommends a pattern of: 
- acquireTokenSilently
- if acquireTokenSilently fails for a reason that can be fixed by an interactive flow (such as the user having to do MFA), then do acquireToken by via an interactive flow, such as AuthorizationCodeParameters or DeviceCodeParameters

So from the application developers perspective, what you need to do is be able to handle the exception that MSAL will throw in the case that the user needs to auth interactively. More details [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-handling-exceptions?tabs=java)

**Comment by sangonzal** [comment]
@ulvii Does that answer your question?

**Comment by ulvii** [comment]
Hi @sangonzal ,
Thanks for the response, very helpful. I just wanted to confirm a few things.

> if acquireTokenSilently fails for a reason that can be fixed by an interactive flow (such as the user having to do MFA), then do acquireToken by via an interactive flow, such as AuthorizationCodeParameters or DeviceCodeParameters

Will calling acquireToken with AuthorizationCodeParameters or DeviceCodeParameters trigger AzureAD UI? Or we would need to implement the UI?

Another question I had was, could acquireToken with AuthorizationCodeParameters or DeviceCodeParameters be called from a native JAVA application or it has to be a web application?

We are looking into implementing MFA support in JDBC driver for SQL Server, hence we don't have an option of implementing a UI or use web applications.

I also noticed .net version of the library has AcquireTokenInteractive API, any plans on adding the same API for the JAVA library?

**Comment by sangonzal** [comment]
@ulvii Calling acquireToken with AuthorizationCodeParameters will redirect the user to AzureAd, where AzureAD will handle the UI, and then the user gets redirected back to your app. You can use this in both desktop apps and web apps. 

With DeviceCodeParameters what happens is that AzureAd returns a code and an URL, then the user will go and open that URL in a separate browser, put in their credentials and the code received, and then go back to the app. This flow is really only supposed to be used for devices without a browser or way of inputting credentials (think IOT for example). 

Take a look at the wiki page on [acquiring tokens](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Acquiring-Tokens). This will explain all the supported scenarios.

Yes, we plan to add AcquireTokenInteractive for the next release. This will land sometime in February.

**Comment by sangonzal** [comment]
Closing this issue as the question is answered. Feel free to reopen/comment if anything else comes up.

**Comment by ulvii** [comment]
Thanks for the detailed information @sangonzal .
I will try a sample later and let you know if there are any questions.

**Comment by ulvii** [comment]
Hi @sangonzal ,
I noticed there is a new release and "Added acquire token interactive API, using system default browser" in the changelog. I searched the source code, but there is still no `acquireTokenInteractive` API in the library. Could you provide more details?

**Comment by sangonzal** [comment]
Hi @ulvii, see https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Acquiring-Token-Interactively
