### ISSUE TITLE
Confidential client sample fails when acquireTokenSilently() is called within 5 minutes before access token expiry or later

### ISSUE THREAD

**Issue by Kars-de-Jong** [AzureAD/microsoft-authentication-library-for-java#170]
The sample confidential client uses `acquireToken()` for obtaining the initial access token, subsequent retrieval of the access token is done using `acquireTokenSilently()` (see [src/samples/confidential-client/ClientCredentialGrant.java](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/samples/confidential-client/ClientCredentialGrant.java)).

When using this flow in an actual application, `acquireTokenSilently()` fails with a `MsalClientException` with an `AuthenticationErrorMessage.NO_TOKEN_IN_CACHE` message when the call is made within 5 minutes of the access token expiration time. The underlying cause of this is that there is no refresh token present in the client credentials authentication flow (see the [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#how-each-flow-emits-tokens-and-codes)).

I find this behaviour to be confusing and undocumented. There's some general [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-acquire-cache-tokens#recommended-call-pattern-for-public-client-applications) which suggests `acquireTokenSilently()` should not be used when using the client credentials flow, because "This method takes care of verifying this application token cache before sending a request to the STS." I interpret this to mean that I should always use `acquireToken()`, which contradicts the sample. However, when always using `acquireToken()`, MSAL for Java requests a new token every time and doesn't use the cache at all.

I have for now solved this by keeping track of the expiration time of the access token myself and requesting a new one using `acquireToken()` when it's close to expiry or expired, with the decision to do so based on "the time is now after 6 minutes before token expiration", to avoid the `MsalClientException`. I don't really like this solution as it depends on the value of `MIN_ACCESS_TOKEN_EXPIRE_IN_SEC` (which is not accessible).

I have the following questions/remarks:
1. Should I only use `acquireToken()`?
2. If yes, I think `acquireToken()` should consult the access token cache (like it should according to the docs) before actually deciding to request a new access token from the STS. Also, the sample application should be updated accordingly.
3. If no, I think `acquireTokenSilently()` should be modified to provide a better exception / error code for the case of an (almost) expired access token. The sample application should then also be updated to show a more realistic code flow showing how to handle this.

**Comment by sangonzal** [comment]
@Kars-de-Jong Thanks for bringing this up, it is indeed confusing.  

You should try `acquireTokenSilently()`, then if no token is found in the cache then you fall back to to using `aquireToken()`. This could potentially save you a lot of network requests if you are making calls within 60 minutes (before the access token expires). You should not be keeping track of the expiration time in the access token yourself. Clients should treat access tokens as opaque, as their format can change at any point. 

The samples that are part of the library were originally put there to do manual testing before releases. This is not clear, and people are referencing them, so we will [update them](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/171) to show the recommended pattern. The documentation that you referenced is outdated. That will also be updated.

**Comment by Kars-de-Jong** [comment]
@sangonzal Thanks for your reply!

I will change my code flow to match your suggestion.
