### ISSUE TITLE
Update dev samples to show recommended patterns

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-java#171]
Update [samples](https://github.com/AzureAD/microsoft-authentication-library-for-java/tree/dev/src/samples) show recommended acquire token patterns.

**Comment by alex-mason-jdas** [comment]
I took the b2c MSAL4J sample as a good pattern so am really now needing to know what the right pattern is for this issue/pattern around silent than not. Is it possible to give me at least a preview? Which overload of acquireToken would I use in the fallback? If it's the refresh token one, where do I get the refresh token?

**Comment by sangonzal** [comment]
@alex-mason-jdas The b2c sample is up to date. We will eventually move it to it's own repository with a README containing instructions, but the code will remain the same. This issue is specifically referring to samples under the public-client and confidential-client folders.
