### ISSUE TITLE
Example of how to pass domain_hint properly?

### ISSUE THREAD

**Issue by alex-mason-jdas** [AzureAD/microsoft-authentication-library-for-java#174]
Is there an example of how to pass domain_hint properly using MSAL4J? Other MSAL libraries seem to have this ability, but am not immediately seeing how to do it. If there's no built in support, is there any plan to support or is there an example of how to add it?

**Comment by sangonzal** [comment]
@alex-mason-jdas You would pass in domain_hint as a query parameter to the request to the authorization endpoint. If you are following the web app or b2c sample, it would go in [here](https://github.com/Azure-Samples/ms-identity-java-webapp/blob/master/src/main/java/com/microsoft/azure/msalwebsample/AuthHelper.java#L177)

By the way, we are working on adding a helper method to the library that crafts this URL for you based on the parameters that you pass.  #95 tracks this work. It should be released this week.

**Comment by alex-mason-jdas** [comment]
OK, thanks! I guess there is no impact on the acquireTokenSilently in this regard (domain_hint) when it comes time to refresh a token?

**Comment by sangonzal** [comment]
That's right, no impact.

**Comment by szalapski** [comment]
> @alex-mason-jdas You would pass in domain_hint as a query parameter to the request to the authorization endpoint. If you are following the web app or b2c sample, it would go in [here](https://github.com/Azure-Samples/ms-identity-java-webapp/blob/master/src/main/java/com/microsoft/azure/msalwebsample/AuthHelper.java#L177)

That link is broken.  Do you know of any example as was asked?
