### ISSUE TITLE
acquireTokenSilently called after acquireToken in sample

### ISSUE THREAD

**Issue by anant-k-singh** [AzureAD/microsoft-authentication-library-for-java#177]
Please review the code flow for the __public-client/UsernamePasswordFlow.java__ in samples.
`app.acquireTokenSilently()` future is used after `app.acquireToken()`.
Shouldn't it be the other way round?

**Comment by sangonzal** [comment]
Yes, acquireTokenSilently should be called before acquireToken. The samples were traditionally used for manual testing. We plan to update them - #171 tracks this work.
