### ISSUE TITLE
Permission denied exception while fetching  Access token using Client Credentials flow

### ISSUE THREAD

**Issue by pankaj0007** [AzureAD/microsoft-authentication-library-for-java#186]
Hi All,

We are trying to using MSAL4j library for integrating our application with Azure.
Our Application has java Security Manager enabled in it.

Below is the code snippet used to fetch access token.

```
class ClientCredentialGrant {


 public static IAuthenticationResult getAccessTokenByClientCredentialGrant() throws Exception {

        ConfidentialClientApplication app = ConfidentialClientApplication.builder(
                CONFIDENTIAL_CLIENT_ID,
                ClientCredentialFactory.createFromSecret(CONFIDENTIAL_CLIENT_SECRET))
                .authority(TENANT_SPECIFIC_AUTHORITY)
                .build();

        // With client credentials flows the scope is ALWAYS of the shape "resource/.default", as the
        // application permissions need to be set statically (in the portal), and then granted by a tenant administrator
        ClientCredentialParameters `clientCredentialParam` = ClientCredentialParameters.builder(
                Collections.singleton(SYNC_READ_SCOPE))
                .build();


        CompletableFuture<IAuthenticationResult> future = app.acquireToken(clientCredentialParam);
        return future.get();
    }
}

```

Exception:

INFO   | jvm 1    | 2020/02/24 15:40:02 | Caused by: java.lang.ExceptionInInitializerError
INFO   | jvm 1    | 2020/02/24 15:40:02 | at com.microsoft.aad.msal4j.MsalRequest.headers(MsalRequest.java:50)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:115)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:131)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:42)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:32)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:49)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
INFO   | jvm 1    | 2020/02/24 15:40:02 | Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "os.arch" "read")
INFO   | jvm 1    | 2020/02/24 15:40:02 | at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at java.security.AccessController.checkPermission(AccessController.java:886)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1294)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at java.lang.System.getProperty(System.java:717)
INFO   | jvm 1    | 2020/02/24 15:40:02 | at com.microsoft.aad.msal4j.HttpHeaders.<clinit>(HttpHeaders.java:20)

As per our investigation, since our application has Java Security Manager enabled,  and MSAL4j library uses below code to fetch the access token Asynchronously.

    CompletableFuture<String> completableFuture
                = CompletableFuture.supplyAsync(new CustomSupplier());

security context is not inherited to the child thread. 
So in debugging, 
`AccessController.getInheritedAccessControlContext()`

gives null values whereas when Java Security is not enabled, we are able to get access token.

**Comment by sangonzal** [comment]
@pankaj0007 The client application object lets you set an `ExecutorService` which gets passed in to the `CompleteableFuture.supplyAsync()` call. You should be able to instantiate an `ExecutorService` that uses threads that have the same permissions as the current thread. 

```
        ExecutorService executorService = ... ;
        ConfidentialClientApplication app = ConfidentialClientApplication.builder(
                CONFIDENTIAL_CLIENT_ID,
                ClientCredentialFactory.createFromSecret(CONFIDENTIAL_CLIENT_SECRET))
                .authority(TENANT_SPECIFIC_AUTHORITY)
                .executorService(executorService).
                .build();

``

**Comment by pankaj0007** [comment]
@sangonzal  Thanks for your answer. We did the same by using the trial and error and it worked.

Subsequently your answer also point us in the same direction.

Thanks Again.
