### ISSUE TITLE
Maven Build lombok Failure

### ISSUE THREAD

**Issue by brendangl** [AzureAD/microsoft-authentication-library-for-java#187]
Hi,

I tried to create the msal4j jar file with Maven using the instructions listed in [https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Maven](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Maven).

mvn clean results in a BUILD SUCCESS

But mvn package gives me the below error. How can I resolve this? Thanks!

[INFO] Scanning for projects...                                                                                                                                            [INFO]                                                                                                                                                                     [INFO] ---------------------< com.microsoft.azure:msal4j >---------------------                                                                                            [INFO] Building msal4j 1.4.0                                                                                                                                               [INFO] --------------------------------[ jar ]---------------------------------                                                                                            [INFO]                                                                                                                                                                     [INFO] --- lombok-maven-plugin:1.18.2.0:delombok (default) @ msal4j ---                                                                                                    [WARNING] Unable to detect tools.jar; java.home is C:\Program Files\Java\jdk-13.0.2                                                                                        WARNING: An illegal reflective access operation has occurred                                                                                                               WARNING: Illegal reflective access by lombok.javac.JavacTreeMaker$TypeTag to method com.sun.tools.javac.code.Type.getTag()                                                 WARNING: Please consider reporting this to the maintainers of lombok.javac.JavacTreeMaker$TypeTag                                                                          WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations                                                                      WARNING: All illegal access operations will be denied in a future release                                                                                                  [INFO] ------------------------------------------------------------------------                                                                                            [INFO] BUILD FAILURE                                                                                                                                                       [INFO] ------------------------------------------------------------------------                                                                                            [INFO] Total time:  10.007 s                                                                                                                                               [INFO] Finished at: 2020-02-24T15:15:38-05:00                                                                                                                              [INFO] ------------------------------------------------------------------------                                                                                            [ERROR] Failed to execute goal org.projectlombok:lombok-maven-plugin:1.18.2.0:delombok (default) on project msal4j: Unable to delombok: InvocationTargetException: pat -> [Help 1]                                                                                                                                                                    [ERROR]                                                                                                                                                                    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.                                                                                        [ERROR] Re-run Maven using the -X switch to enable full debug logging.                                                                                                     [ERROR]                                                                                                                                                                    [ERROR] For more information about the errors and possible solutions, please read the following articles:                                                                  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by sangonzal** [comment]
@brendangl What JDK version are you using?

**Comment by brendangl** [comment]
@sangonzal I was using jdk-13.0.2. I switched to jdk1.8.0_241 and then it worked. So there's a compatibility issue with the newer JDK version, but for my purposes, it's fine to use JDK 1.8.

**Comment by sangonzal** [comment]
@brendangl Yes there seems to be a problem with org.projectlombok:lombok-maven-plugin when using JDK12 and up - need to look in it. 

You can run `mvn install -DskipITs`. I've updated the wiki with this info.

**Comment by SomkaPe** [comment]
msal4j jar can always be downloaded from https://mvnrepository.com/artifact/com.microsoft.azure/msal4j,  

currently we support minimal JDK 8+,
so have corresponding maven-compiler-plugin and lombok plugins configuration
