### ISSUE TITLE
[BUG] MSAL using ForkJoinPool to acquire token results in overall hang when all threads in the pool are used.

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#192]
**Describe the bug**
MSAL confidential application client's acquireToken method is using a Completeable future to return IAuthenticationResult which by default uses the common ForkJoin thread pool. When the user application uses up all the threads in the common pool and attempts to authenticate via MSAL, no threads are available for MSAL to execute and results in a hang.

***Exception or Stack Trace***
Application hangs.

**Expected behavior**
The authentication request should still get executed.

**Comment by sangonzal** [comment]
@g2vinay as Petro explained in the email thread, MSAL uses ForkJoin thread pool by default. You can override this behavior by setting a custom `ExecutorService` on the client application object.
