### ISSUE TITLE
[Question] Why can't I use dynamic scopes through client credentials flow, even if it's possible via raw HTTP?

### ISSUE THREAD

**Issue by nsadeh** [AzureAD/microsoft-authentication-library-for-java#199]
It appears that MSAL4J does not support dynamic scopes for `acquireToken` using the confidential client credentials flow (https://stackoverflow.com/questions/51781898/aadsts70011-the-provided-value-for-the-input-parameter-scope-is-not-valid). 

When I pass in dynamic credentials I get 

`Caused by: com.microsoft.aad.msal4j.MsalServiceException: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope openid profile offline_access User.Read Mail.Read is not valid`

I have a variety of other attempts (using lower case, appending the https://graph.microsoft.com/ URI) but they all fail.

However, I got working code that just hits `https://login.microsoftonline.com/<tenantId>/oauth2/v2.0/token`. with a set of scopes.
 I'd like to replicate this in MSAL4J but can't figure out how.

**Comment by sangonzal** [comment]
@nsadeh Can you expand a bit on your scenario? You have a web service that is requesting tokens but you don't know the scopes ahead of time? 

When you say  "I got working code that just hits https://login.microsoftonline.com/<tenantId>/oauth2/v2.0/token" , what query parameters are you including in the call?

**Comment by nsadeh** [comment]
We use

`new StringBuilder()
 .append("grant_type=").append("refresh_token")
                    .append("&client_id=").append(URLEncoder.encode(clientId, "UTF-8"))
                    .append("&client_secret=").append(URLEncoder.encode(clientSecret, "UTF-8"))
                    .append("&scope=").append(URLEncoder.encode(SCOPE, "UTF-8"))
                    .append("&redirect_uri=").append(URLEncoder.encode(redirectUri, "UTF-8"))
                    .append("&refresh_token=").append(refreshToken)
                    .toString();`

as the body.

Update: I confirmed that the app has Mail.ReadWrite and User.ReadWrite on Azure AD, but running with `.default` scope still yields a null token.

**Comment by SomkaPe** [comment]
Could you please provide more details ? you have mentioned client credential flow, but you request token for user - User.Read Mail.Read .
Client credential flow can not be used to get tokens to some user`s resources.

Also in last comment you have used grant_type=").append("refresh_token"), which is not client credential flow

**Comment by nsadeh** [comment]
I got this covered by getting my admin to add this to application API scope on Azure AD.
