### ISSUE TITLE
[Doc] Update ADFS 2019 support in the docs

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-java#204]
Reading this:
https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Active-Directory-Federation-Services-(AD-FS)-Support

Causes confusion about ADFS 2019 support. Should be updated to accurately reflect that ADFS 2019 is supported.

**Comment by navyasric** [comment]
This is now updated in the [Wiki page](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Active-Directory-Federation-Services-(AD-FS)-Support).
