### ISSUE TITLE
Failed to validate data received from Authorization service - Could not validate state

### ISSUE THREAD

**Issue by Ale-Car** [AzureAD/microsoft-authentication-library-for-java#205]
I have cloned the sample project **msal-b2c-web-sample** and configured according to the indications, referenced the MSAL4J library in versions 1.3 and 1.4, for both versions the following error occurs checking the status for the callback from B2C
**Failed to validate data received from Authorization service - Could not validate state**

The problem occurs differently for the two versions:

- 1.3 -> the error occurs randomly with the Chome, Firefox and Edge broswer, when returning from B2C the session lacks the **states** attribute so the validation of the state fails
- 1.4 -> the error always occurs and with all browsers, when returning from B2C there is no cookie **msal_web_app_auth_state**, so status validation fails

In both cases, the calling application uses the HTTPS protocol

**Comment by SomkaPe** [comment]
Please create an issue in corresponding repository - msal-b2c-web-sample

**Comment by Ale-Car** [comment]
The repository is correct, I'm refferring to the project **microsoft-authentication-library-for-java/src/samples/msal-b2c-web-sample/**

**Comment by sangonzal** [comment]
@Ale-Car Can you try running the sample at https://github.com/Azure-Samples/ms-identity-java-webapp/tree/master/msal-b2c-web-sample? 

That one is kept more up to date, and has instructions on how to do the app registration. If you run into any issues, please open up an issue there and we will try to help out.
