### ISSUE TITLE
Token not found it the cache should not be thrown as an Error

### ISSUE THREAD

**Issue by MBurchard** [AzureAD/microsoft-authentication-library-for-java#206]
I have implemented a very simple IAuthenticationProvider that uses some of Microsofts samples.

This will be used for accessing the Graph API or other secured web APIs.

		final IAuthenticationProvider authenticationProvider = ConfidentialClientAuthProvider
				.builder(clientId, clientSecret, tenant).graph().build();
		GraphServiceClient.builder().authenticationProvider(authenticationProvider).buildClient();

Taking the code from the example first one has to check if the access token is already in the cache.

I wrapped that in the following method of my ConfidentialClientAuthProvider:

	private Optional<IAuthenticationResult> acquireTokenSilently(
			final ConfidentialClientApplication cca) throws Throwable {
		final IAuthenticationResult result;
		try {
			final SilentParameters silentParameters = SilentParameters.builder(scopes).build();

			// try to acquire token silently. This call will fail since the token cache does not
			// have a token for the application you are requesting an access token for
			return Optional.ofNullable(cca.acquireTokenSilently(silentParameters).join());
		} catch (final CompletionException ex) {
			if (ex.getCause() instanceof MsalClientException) {
				LOG.debug(ex.getMessage());
			} else {
				throw ex.getCause();
			}
		}
		return Optional.empty();
	}

The problem: If the token is not in the cache, what is absolutely normal for the first request, this will be logged as an error by `AuthenticationResultSupplier` line 88:

    clientApplication.log.error(
            LogHelper.createMessage(
                    "Execution of " + this.getClass() + " failed.",
                    msalRequest.headers().getHeaderCorrelationIdValue()), ex);

It is thrown by `AcquireTokenSilentSupplier` line 58:

    throw new MsalClientException(AuthenticationErrorMessage.NO_TOKEN_IN_CACHE, AuthenticationErrorCode.CACHE_MISS);

And thus it is part of the logfile.

Either there is a way to check if the token is in the cache, that does not throw an error, that I have not found, or this behaviour should be changed.

**Comment by sangonzal** [comment]
@MBurchard The recommended pattern is to catch the error and then try to `acquireToken` as you are doing in https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/207.

Older version of MSAL actually returned `null` for cases when there was no token in the cache. When doing this though, the logic looked something like: if result is null OR `acquireTokenSilently` throws, then fall back to `acquireToken`, which wasn't as ergonomic. The team thus decided to instead throw an error for that case, and simplify the previous logic to just catching the error.

**Comment by lyytinen** [comment]
I agree with @MBurchard here. Throwing an error in this case is not that great because it's completely normal for the token to not exist in the cache. Personally, I can live with catching the Error in my code but it's a bit awkward that it also get's logged at ERROR level. So unless you filter those out you get alerts from your log monitoring.

**Comment by lyytinen** [comment]
There's also a typo in the error message:

https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/main/java/com/microsoft/aad/msal4j/AuthenticationErrorMessage.java#L11

**Comment by MBurchard** [comment]
What @lyytinen said is the point. It is ok to throw an error that one must catch, but it is not okay to log it. It is not an error from the application point of view but will occur in our logfiles again and again.

Another possible solution would be to return an Optional. I did it an wrapped the MSAL code in my implementation.

	/**
	 * @return Optional of AccessToken
	 * @throws AuthenticationException
	 * 		with cause
	 */
	@Nonnull
	public Optional<AccessToken> getAccessToken() throws AuthenticationException {

		final IAuthenticationResult iAuthenticationResult =
				acquireTokenSilently().orElseGet(this::acquireToken);

		return Optional.of(new AccessToken(iAuthenticationResult.accessToken(),
				iAuthenticationResult.expiresOnDate()));
	}

**Comment by sangonzal** [comment]
Acknowledge the annoyance of log monitoring. I agree that this shouIdn't be logged as an error: I  have submitted a PR to update log level from ERROR to DEBUG: https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/216

Thanks for pointing to the spelling mistake, it's also updated: https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/215

**Comment by sangonzal** [comment]
@MBurchard @lyytinen These changes were released as part of MSAL Java v1.5.0
