### ISSUE TITLE
Why can't I get the example/demo code to work?

### ISSUE THREAD

**Issue by jayr-davis** [AzureAD/microsoft-authentication-library-for-java#209]
I am trying to get the ClientCredentialGrant demo code to work.
The code is at [https://github.com/Azure-Samples/ms-identity-java-daemon/blob/master/src/main/java/ClientCredentialGrant.java](https://github.com/Azure-Samples/ms-identity-java-daemon/blob/master/src/main/java/ClientCredentialGrant.java)

Here is the issue I posted there:
[https://github.com/Azure-Samples/ms-identity-java-daemon/issues/4](https://github.com/Azure-Samples/ms-identity-java-daemon/issues/4)

Not sure if it is the demo or the underlying code.  So I'm asking in both places.
thanks

**Comment by sangonzal** [comment]
I have replied to the issue in ms-identity-java-daemon. Closing this as it's a duplicate.
