### ISSUE TITLE
Private JWT to reassert fix

### ISSUE THREAD

**Issue by Budlee** [AzureAD/microsoft-authentication-library-for-java#224]
The PrivateJwt assertion with a certificate is generated once
This means that when a request for a new OAuth Token is made that
the client assertion has expired and fails. This change
fixes that by reubuilding the assersion for a private jwt when
it has expired

I have created a PR to fix this. Can someone take a look #221

**Comment by SomkaPe** [comment]
@Budlee  PR accepted. Thank you for your contribution.

**Comment by sangonzal** [comment]
@Budlee These changes were released as part of MSAL Java v.1.5.0
