### ISSUE TITLE
[Question] How to access refresh token

### ISSUE THREAD

**Issue by sleshJdev** [AzureAD/microsoft-authentication-library-for-java#228]
Hi
I need to keep refresh token in the database to sync up with client's inbox. I couldn't find any legal way to retrieve a refresh token from the  IAuthenticationResult. I think up with temporal dirty workaround using reflection:
```
try {
            //see com.microsoft.aad.msal4j.AuthenticationResult#refreshToken
            final Field refreshTokenField = credentials.getClass()
                .getDeclaredField("refreshToken");
            refreshTokenField.setAccessible(true);
            return refreshTokenField.get(credentials).toString();
        } catch (IllegalAccessException | NoSuchFieldException e) {
            throw new RuntimeException(e);
        }
```
Is there better anyway to retrieve a refresh token? Serialize TokenCache doesn't look much better for me.

**Comment by sangonzal** [comment]
@sleshJdev Does 'acquireTokenSilently' work for your scenario? MSAL doesn't expose the refresh token but instead takes care of refreshing the access token for you. When you acquire a token with any of the APIs, MSAL will store the refresh token in an in-memory cache, which [you can save to disk.](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-java-token-cache-serialization) `AcquireTokenSilently()` will first look into the cache, see if you have a valid access token, and if not then will try to refresh the refresh token.

**Comment by sleshJdev** [comment]
Unfortunately, it won't work as I need to **refresh** the token, not the **access** one. The acquireTokenSilently method returns IAuthenticationResult too which doesn't expose any public method to get a refresh token.

**Comment by sangonzal** [comment]
Short answer: MSAL Java does not expose refresh token at all, so if you really need it then you'll have to do what you are already doing. 

More details: Resources take access tokens, not refresh tokens. A refresh tokens purpose is to get new tokens without prompting the user for permission again. Most MSALs (I think actually all) made the choice to hide the details of caching and refreshing tokens from the user. Instead, they expose some form of `acquireTokenSilently` and a `TokenCache`. You can store the `TokenCache` and load into the client application object, similar to how you would store the tokens yourself, with the benefit that you don't have to manage the lifetimes. 

Having said that, you might be able to do what you are trying to accomplish in a different way. Can you expand on "I need the refresh token(noun, not verb), not the access one"? Trying to understand your scenario.

**Comment by sleshJdev** [comment]
When onboarding a new client, we try to authenticate them through different OAuth providers like Microsoft/Google, etc. In the response, we receive authentication code and receive a **refresh_token** which store in our database for future usage. We need this as we read emails from the client and we need **refresh_token** be available in any time. We cannot ask the client to pass authentication again each time. They're don't care. When we get **refresh_token** into our database we use it in our recurrent jobs which acquire **access_token** by using **refresh_token** first and then read the emails delta. That's basically it.

**Comment by sleshJdev** [comment]
@sangonzal is it aligned with library philosophy if I'll provide PR which would make refresh token accessible from IAuthenticationResult?

**Comment by sleshJdev** [comment]
Any updates here?

**Comment by sangonzal** [comment]
@sleshJdev Instead of storing the refresh_token, you can store the `TokenCache`, which contains the access token, refresh token, id token and account. At the moment we don't have plans for exposing refresh token, and I don't think a PR with those those changes would get merged in.

**Comment by sleshJdev** [comment]
What reason for such restrictions if token is still accessible using reflection or from the raw json?

**Comment by sleshJdev** [comment]
When onboarding a new client, we try to authenticate them through different OAuth providers like Microsoft/Google, etc. In the response, we receive authentication code and receive a **refresh_token** which store in our database for future usage. We need this as we read emails from the client and we need **refresh_token** be available in any time. We cannot ask the client to pass authentication again each time. They're don't care. When we get **refresh_token** into our database we use it in our recurrent jobs which acquire **access_token** by using **refresh_token** first and then read the emails delta. That's basically it.

**Comment by sangonzal** [comment]
It's a design decision by MSALs. It leads to customers to using `acquireTokenSilently`, which offloads the management of refreshing tokens. This ultimately leads to less complexity for the users of the library (writing token cache logic can be involved), less issues around refreshing of tokens, and reduces COGS. Also it's not blocking any scenarios for people - as previously discussed you can store the token cache, and if you really don't want to do that then you can always use reflection.

**Comment by navyasric** [comment]
Closing this issue as the question has been answered above.

**Comment by HaydenDekker** [comment]
I'm in the process of putting MSAL app together for the first time and have found this part particularly confusing.

I need to persist the refresh token. The Oauth spec says we get both an access and a refresh token but I could not find anyway of obtaining it. It was not clear by the API that I need to provide a custom TokenCacheAspect to implement my persistence.

**Comment by bgavrilMS** [comment]
@HaydenDekker - msal will handle the refresh token internally. All you need to do is to specify a persistence strategy and to call the right APIs. 

What type of app do you have?
