### ISSUE TITLE
Unable to acquire token

### ISSUE THREAD

**Issue by RajatNair** [AzureAD/microsoft-authentication-library-for-java#240]
Hi,

The following snippet of code was working fine and generating an access token couple of days back -

```Java
private static IAuthenticationResult acquireToken() throws Exception {

     // Load token cache from file and initialize token cache aspect. The token cache will have
     // dummy data, so the acquireTokenSilently call will fail.
     TokenCacheAspect tokenCacheAspect = new TokenCacheAspect("sample_cache.json");

     IClientCredential credential = ClientCredentialFactory.createFromSecret(CLIENT_SECRET);
     ConfidentialClientApplication cca =
             ConfidentialClientApplication
                     .builder(CLIENT_ID, credential)
                     .authority(AUTHORITY)
                     .setTokenCacheAccessAspect(tokenCacheAspect)
                     .build();

     IAuthenticationResult result;
     try {
         SilentParameters silentParameters =
                 SilentParameters
                         .builder(SCOPE)
                         .build();

         // try to acquire token silently. This call will fail since the token cache does not
         // have a token for the application you are requesting an access token for
         result = cca.acquireTokenSilently(silentParameters).join();
     } catch (Exception ex) {
         if (ex.getCause() instanceof MsalException) {

             ClientCredentialParameters parameters =
                     ClientCredentialParameters
                             .builder(SCOPE)
                             .build();

             // Try to acquire a token. If successful, you should see
             // the token information printed out to console
             result = cca.acquireToken(parameters).join();
         } else {
             // Handle other exceptions accordingly
             throw ex;
         }
     }
     return result;
 }
```
[Source](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-acquire-token?tabs=java#acquiretokenforclient-api)

but today this exception is throw

> java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: net.minidev.json.JSONObject.getAsNumber(Ljava/lang/String;)Ljava/lang/Number;

Current setup - 
- Apache Maven 3.6.3
- Java 1.8.0_252
- Spring Boot 2.3.0.RELEASE
- msal4j 1.5.0

Was using ms-graph-sdk 1.7.1 and ms-graph-core 1.0.1 but got same error even after removing them.

Pulling my hair out trying to figure out root cause. Not sure which dependency is causing this error. I see that msal4j uses net.minidev's json-smart 1.3.1
![image](https://user-images.githubusercontent.com/3319907/83284411-47663d00-a1fa-11ea-9d28-75f563bc53fc.png)
but excluding that dependency and using newer 2.3 version also did not help.

I have stripped my `pom.xml` to bare minimum but still no luck - 
```xml
    <dependencies>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>msal4j</artifactId>
            <version>${ms-azure-msal4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
    </dependencies>
```

**Comment by RajatNair** [comment]
1. Any temporary workarounds for this issue? Downgraded to 1.2.0 based on comments in https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/213 and traced `com.fasterxml.jackson.dataformat` usage (see screenshot) based on https://github.com/Azure-Samples/ms-identity-java-daemon/issues/4 
![image](https://user-images.githubusercontent.com/3319907/83648888-350e4980-a5d4-11ea-834b-e9860b03dfbd.png)
but neither worked.
2. Any tentative release date for 1.6.0 milestone?

**Comment by schuch** [comment]
I still run into this issue with `1.6.0`.

As a user of this library, i do not want to manage your transitive depencencies, so please fix them.
I added some details about that in this discussion: https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/214#issuecomment-638709638

**Comment by SomkaPe** [comment]
@RajatNair 1.6.1 version is released, please try
