### ISSUE TITLE
Tenant profile support in MSAL Java

### ISSUE THREAD

**Issue by navyasric** [AzureAD/microsoft-authentication-library-for-java#247]

**Comment by jan-tosovsky-cz** [comment]
When creating daemon app which should send emails by my name (graphClient.me().sendMail()), I assume the only possibility to authenticate as a specific user is to get AuthToken using UserNamePassword approach. However, this "flow" can only be used in PublicClientApplication. When using this way:
```java
public static IAuthenticationResult getUserPasswordAccessToken() throws Exception {

    PublicClientApplication app = PublicClientApplication.builder(CLIENT_ID).build();

    UserNamePasswordParameters userNamePasswordParams = UserNamePasswordParameters.builder(
        Collections.singleton("Send.Mail"), "email", "password".toCharArray())
        .build();

    CompletableFuture<IAuthenticationResult> future = app.acquireToken(userNamePasswordParams);

    return future.get();
}
```
But I am getting this error the Tenant has to be specified:
```
com.microsoft.aad.msal4j.MsalServiceException: AADSTS9001023: The grant type is not supported 
over the /common or /consumers endpoints. Please use the /organizations or tenant-specific endpoint.
```
I can't see any way how to specify Tenant, but looking into C# sample app I can see `PublicClientApplicationBuilder.CreateWithApplicationOptions(appConfig)` method which can be used for this.
https://github.com/Azure-Samples/active-directory-dotnetcore-console-up-v2/blob/master/up-console/Program.cs

Is this enhancement about the same thing or should I create separate feature request?
