### ISSUE TITLE
Auth failures report NullPointerException instead of full error

### ISSUE THREAD

**Issue by CharlesW4** [AzureAD/microsoft-authentication-library-for-java#250]
I have a project based closely on the [java web app sample](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-java-webapp). When attempting to redeem the auth code for a token it occasionally fails. However instead of reporting a AD exception it encounters a NullPointerException within the logging step: `AuthenticationResultSupplier.logException(AuthenticationResultSupplier.java:139`.
Stack trace: [msal4j nullpointer.txt](https://github.com/AzureAD/microsoft-authentication-library-for-java/files/4794790/msal4j.nullpointer.txt)

I am using v1.5.0 but based on v1.6.1 the issue appears to be that `MsalClientException` does not have an error code in that scenario and fails comparison.

**Comment by Avery-Dunn** [comment]
Thanks for bringing this to our attention, I've just created a PR that should take care of this issue, and it will go into the next release: https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/254

**Comment by navyasric** [comment]
Released in 1.6.2
