### ISSUE TITLE
Implement ADFS authority validation

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-java#252]
Please read ADFS authority validation [spec](https://microsoft.sharepoint.com/:w:/r/teams/aad/devex/_layouts/15/Doc.aspx?sourcedoc=%7BF0EB0F6F-2B78-42A2-B44F-01DA1D6015E2%7D&file=ADFS%20Authority%20Validation%20-%20Original%20Spec.docx&action=default&mobileredirect=true&wdLOR=c22AE0924-0124-3D40-8BD4-435F36B291C7&cid=55F6763D-6E90-4588-A0AD-AF062981A3E4) and asses if MSAL java implements this. 

Please see equivalent MSAL.NET [issue ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1885)for a few more details.

As discussed with @henrik-me

**Comment by dongdongw** [comment]
I want to using java implements ADFS authority, can you help me hot to do that?

**Comment by bganapa** [comment]
The java packages used by the AzureStack customers are all still with ADAL. Doc page details below[1]. We will be moving to consume the MSAL based track 2 SDK in the current semester. ADFS is a key scenario for AzureStack and this issue will be a blocker for us to move to track 2 SDKs. Could you please prioritize this issue?

[1]
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles-java?view=azs-2008

**Comment by bgavrilMS** [comment]
Please note that after further investigation we've realized that ADFS authority validation is not fit for purpose. It would only work if the username is known upfront by the app, making it impractical.

Recommendation is to make sure ADFS server is well-known.

**Comment by siddhijain** [comment]
@bgavrilMS based on your comments above, can we close this issue?
