### ISSUE TITLE
[Enhancement] Add support for extraQueryParameters

### ISSUE THREAD

**Issue by navyasric** [AzureAD/microsoft-authentication-library-for-java#256]
Spec: 

- [x] new API at request level (on **all** AcquireToken* methods) should allow passing in a map of key / value string pairs
- [x] in public client, the authorization url which is used to open the browser, must use append these parameters
- [x] in confidential client, the `GetAuthorizationUrl` API should take into account these parameters
- [x] in both clients, the token endpoint must append these parameters (even though the request is a POST request)
- [x] when talking to broker, the parameters must be added the `Properties` bag of auth parameters
- [x] in case of conflict, (e.g. app developer tries to pass in `scope=foo` and call AcquireTokenInteractive), throw exception

Needed for a number of functionalities to be enabled. E.g.: 
Customers needs support of extra query parameters in order to use ROPC flow with B2C

**Comment by henrik-me** [comment]
Similar to: https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/255

**Comment by bgavrilMS** [comment]
This will be needed for full WAM support.

**Comment by bgavrilMS** [comment]
@siddhijain - is this done? Can this be closed?

**Comment by siddhijain** [comment]
This will be closed once we update the broker PR with
'when talking to a broker, the parameters must be added to the Properties bag of auth parameters'. Avery is planning to update. Tagging him to close this once done. @Avery-Dunn

**Comment by Avery-Dunn** [comment]
Support for extraQueryParameters in the broker package was add as part of https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/639, so this is fully supported.
