### ISSUE TITLE
Add public convenience string constants for endpoints of each cloud (sovereign and public)

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-java#258]
**Context**
Customers have had difficulty finding the right documentation pages:
https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-developer-guide#endpoint-mapping
https://docs.microsoft.com/en-us/azure/china/resources-developer-guide#check-endpoints-in-azure

**See also other libraries exposing these:**
- [obj-c](https://azuread.github.io/microsoft-authentication-library-for-objc/Enums/MSALAzureCloudInstance.html) 
- [.net](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.azurecloudinstance?view=azure-dotnet)

**Reference:**
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1063014

**Other:**
https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/221

**Comment by Avery-Dunn** [comment]
Relevant PR is merged into dev branch: https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/298

**Comment by Avery-Dunn** [comment]
Released as part of version 1.8.0 https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/314
