### ISSUE TITLE
B2C token validation by msal libraby

### ISSUE THREAD

**Issue by rajesh-naik-by** [AzureAD/microsoft-authentication-library-for-java#262]
I have a generic question about token validation from msal library for java, does msal library takes care of validating below attributes from the token? or is it a responsibility of consumer to validate the token?

- Signature
- exp
- nbf
- iss
- aud

**Comment by SomkaPe** [comment]
Resource supposed to validate access token attached to incoming requests. MSAL is a client side SDK , it helps to get access tokens which will be used by application to access resources.
Spring Security can be used to validate access tokens.

**Comment by rajesh-naik-by** [comment]
So what I understood is MSAL doesn't validate any of the above attributes and its a responsibility of application to validate the token.

**Comment by SomkaPe** [comment]
it is responsibility of resource, accessed with token
