### ISSUE TITLE
Wiki outdated for Instantiating a Confidential Client Application section

### ISSUE THREAD

**Issue by allantargino** [AzureAD/microsoft-authentication-library-for-java#267]
This is the current sample on how to instantiating a confidential client application from Wiki (https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Client-Applications):

```java
IClientCredential credential = ClientCredentialFactory.create(CLIENT_SECRET)
ConfidentialClientApplication app = 
    ConfidentialClientApplication
        .builder(CLIENT_ID, credential)
        .authority(AUTHORITY)
        .build();
```

I believe `ClientCredentialFactory.create(CLIENT_SECRET)` is outdated, it should be `ClientCredentialFactory.createFromSecret(CLIENT_SECRET)`. It is also missing a semicolon in the end of the first line.

So it should be:

```java
IClientCredential credential = ClientCredentialFactory.createFromSecret(CLIENT_SECRET);
ConfidentialClientApplication app = 
    ConfidentialClientApplication
        .builder(CLIENT_ID, credential)
        .authority(AUTHORITY)
        .build();
```

**Comment by Avery-Dunn** [comment]
Thanks for bringing that to our attention. I've just fixed the issues you mentioned, and also added an example of creating a confidential client application with a certificate (just to cover all options mentioned in the [Client Credentials](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Client-Credentials) wiki page).

**Comment by allantargino** [comment]
Thank you very much @Avery-Dunn! The certificate example also helps a lot.

I think it is missing a semicolon:
`IClientCredential credential = ClientCredentialFactory.createFromCertificate(PRIVATE_KEY, PUBLIC_KEY)`

**Comment by Avery-Dunn** [comment]
Another good catch (I probably should've fixed that *before* copying it), but it should be all good now.

**Comment by allantargino** [comment]
Thank you @Avery-Dunn !
