### ISSUE TITLE
IClientApplicationBase should be public (again)

### ISSUE THREAD

**Issue by gesundkrank** [AzureAD/microsoft-authentication-library-for-java#280]
`IClientApplicationBase` is the base interface to several public classes. Without the interface being public it is very hard to add abstraction and implement logic that supports multiple login flows (e.g. logging, error handling).

**Comment by SomkaPe** [comment]
IPublicClientApplication and IConfidentialClientApplication are public

**Comment by gesundkrank** [comment]
I know that `IPublicClientApplication` and `IConfidentialClientApplication` are public but these interfaces are useless to me since they don't define a **common** interface. 

Here's an example (in Scala) how I'm using `IClientApplicationBase` to handle caching in an abstract class which is than implemented by one class that creates a `PublicClientApplication` and another class that creates a `ConfidentialApplication`.

```scala
  val app: IClientApplicationBase

  def loginWithCache(scopes: Set[String])
      (implicit ec: ExecutionContext): Future[IAuthenticationResult] = {
    val silentParams = SilentParameters.builder(scopes.asJava).build()
    app.acquireTokenSilently(silentParams).toScala.recoverWith({
      case exception: MsalException if AuthenticationErrorCode.CACHE_MISS
          .equals(exception.errorCode()) =>
        logger.debug("Token not found in the cache")
        login(scopes)
      case exception: Throwable =>
        logger.error("Failed to acquire token from cache", exception)
        login(scopes)
    })
  }

  def login(scopes: Set[String]): Future[IAuthenticationResult]
```

In my opinion this is an appropriate use-case. Do you disagree? Why? And why decided you to not make `IConfidentialClientApplication` public in the first place?
