### ISSUE TITLE
Enhance or add sample to demonstrate group claims

### ISSUE THREAD

**Issue by Avery-Dunn** [AzureAD/microsoft-authentication-library-for-java#284]
As per this work item: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1052161

**Comment by CryptoLOCK33CyberSecurity** [comment]
Admin can adjust from other vantage points. I may be of assistance with an invitation.

**Comment by Avery-Dunn** [comment]
This is now demonstrated in the Java servlet samples: https://github.com/Azure-Samples/ms-identity-java-servlet-webapp-authentication/tree/main/3-Authorization-II/roles
