### ISSUE TITLE
How to add url infomation in the scope parameter in an authentication request

### ISSUE THREAD

**Issue by yiliuTo** [AzureAD/microsoft-authentication-library-for-java#286]
Migrateing from [issue58](https://github.com/Azure-Samples/ms-identity-java-webapp/issues/58).

I am running the _msal-java-webapp-sample_, and it can work well with instructions from the README.md. However, when I modify the `scope` parameter (the code I modified is [here](https://github.com/Azure-Samples/ms-identity-java-webapp/blob/54b385853939a2f5e230e2cb0629f7f5a7253a52/msal-java-webapp-sample/src/main/java/com/microsoft/azure/msalwebsample/AuthFilter.java#L65) in the authentication request from `null` to an API permission, like `https://graph.microsoft.com/Analytics.Read` (here all the permissions haven't not been consented before), then the sample will keep redirecting to the login page to ask to fill in login info. And if I remove the resource url and set the `scope` as `Analytics.Read` then it can work well.

I did the same thing in the `AuthPageController.java` (here are the code I modified, [place 1](https://github.com/Azure-Samples/ms-identity-java-webapp/blob/cfd24b51cb7822550c311188af1eb0ab898a7a27/msal-java-webapp-sample/src/main/java/com/microsoft/azure/msalwebsample/AuthPageController.java#L80) and [place 2](https://github.com/Azure-Samples/ms-identity-java-webapp/blob/cfd24b51cb7822550c311188af1eb0ab898a7a27/msal-java-webapp-sample/src/main/java/com/microsoft/azure/msalwebsample/AuthHelper.java#L113)), and I got the error of `AADSTS65001: The user or administrator has not consented to use the application with ID xxxxxxxxxxxxxxx`. 

Seems like the permisson with url as prefix cannot be identified. So I want to know that if the library supports specifying url for `scope` and if it does, how should I do so?

Besides, I am testing the feature of this library that how it supports allowing consenting to scopes from mulithple resources and then acquire access tokens from each resource silently, so I need the url info for scopes.

**Comment by sangonzal** [comment]
@yiliuTo Are you testing on with an app registration on Microsoft tenant on your ow personal test tenant? If it's on the Microsoft tenant, then you might be getting AADSTS65001: The user or administrator has not consented to use the application with ID xxxxxxxxxxxxxxx because the scope you are requesting needs admin approval, which you can't give on the Microsoft tenant.

"So I want to know that if the library supports specifying url for scope and if it does, how should I do so?" - I think here what you mean is using https://graph.microsoft.com/Analytics.Read vs Analytics.Read. I believe only the analytics.Read with would work with MSAL. MSAL supports scopes, not resources (difference in between the AAD v1 and v2 endpoints).

"Besides, I am testing the feature of this library that how it supports allowing consenting to scopes from mulithple resources and then acquire access tokens from each resource silently, so I need the url info for scopes." - I think this should work by just passing in the scopes. You should pass in scopes for one resource into scopes parameter, and pass in scopes for extra resources in extraScopesToConsent parameter. Is this not working for you?

**Comment by yiliuTo** [comment]
@sangonzal Thanks for your reply. And for your questions and suggestions,

1. I am using my personal test tenant and all the scopes I chose to test with are those can be approved by users instead of admin. But when the page is redirected to login and I fill in my username and password, then it doesn't redirect to the consent page to ask for approval of permissons but redirect back to the login page.

2. Sorry I made my issue confusing, and here what I mean is that when I set the authorization request parameter as `scope=https://graph.microsoft.com/Analytics.Read` or other permissons with the resource url prefix (e.g. https://management.azure.com/user_impersonation) then the sample goes wrong (keep redirecting to login page), here are the code example which is modified from [here](https://github.com/Azure-Samples/ms-identity-java-webapp/blob/54b385853939a2f5e230e2cb0629f7f5a7253a52/msal-java-webapp-sample/src/main/java/com/microsoft/azure/msalwebsample/AuthFilter.java#L65).
```
                    authHelper.sendAuthRedirect(
                            httpRequest,
                            httpResponse,
                            "https://graph.microsoft.com/Analytics.Read",
                            authHelper.getRedirectUriSignIn());
```
 but if I set the `scope=Analytics.Read` like below, then it can successfully authorize and get access tokens.
```
                    authHelper.sendAuthRedirect(
                            httpRequest,
                            httpResponse,
                            "Analytics.Read",
                            authHelper.getRedirectUriSignIn());
```
So I suppose this is not a problem of AAD v1 and v2 endpoints, right? v1 endpoints mean that I should use `resource` instead of `scope` parameter.

3. Yes, `extraScopesToConsent` is exactly I wanted to use to implement approving scopes from mulithple resources. I intended to test this function as below:
```
    String getAuthorizationCodeUrl(String claims, String scope, String registeredRedirectURL, String state, String nonce)
            throws UnsupportedEncodingException {

        String urlEncodedScopes = scope == null ? "" : URLEncoder.encode(scope, "UTF-8");

        PublicClientApplication pca = PublicClientApplication.builder(clientId).build();

        AuthorizationRequestUrlParameters parameters =
                AuthorizationRequestUrlParameters
                        .builder(registeredRedirectURL,
                                Collections.singleton(urlEncodedScopes))
                        // here I just select an permisson randomly from Azure portal
                        .extraScopesToConsent(new LinkedHashSet<>(Arrays.asList(URLEncoder.encode("https://management.azure.com/user_impersonation", "UTF-8"))))
                        .responseMode(ResponseMode.QUERY)
                        .prompt(Prompt.SELECT_ACCOUNT)
                        .state(state)
                        .nonce(nonce)
                        .claimsChallenge(claims)
                        .build();

        return pca.getAuthorizationRequestUrl(parameters).toString();
    }
```
But I am now blocking with the setting `scope` parameter with resource url prefix. But I am glad that you tell me `extraScopesToConsent` can meet my requirements.

So could you help to investigate that how should I set the `scope` parameter as `{resource-url}/{api-permisson}`?

Thanks

**Comment by yiliuTo** [comment]
And if you want to reproduce my issue, you just need to run your sample of [msal-java-webapp-sample](https://github.com/Azure-Samples/ms-identity-java-webapp/tree/158d769d96261f9c37f26fafd2d9d6f98b4b6621/msal-java-webapp-sample), and modify the `scope` parameter [here](https://github.com/Azure-Samples/ms-identity-java-webapp/blob/master/msal-java-webapp-sample/src/main/java/com/microsoft/azure/msalwebsample/AuthFilter.java#L65) from `null` to any other API permissons with its resource url prefix, e.g. `https://graph.microsoft.com/Analytics.Read`.
Then visit the https://localhost:8443/msal4jsample , after login you will be redirected back to login page again and again.

**Comment by sangonzal** [comment]
@yiliuTo Thanks for the detailed description, I was able to reproduce this issue. The issue has been fixed by this [change](https://github.com/Azure-Samples/ms-identity-java-webapp/pull/60). Let us know if that fixes the issue for you.

**Comment by yiliuTo** [comment]
@sangonzal Thanks, I hava tested it again and it can work for me now.
