### ISSUE TITLE
Tenant Profile is not set in IAuthenticationResult

### ISSUE THREAD

**Issue by SomkaPe** [AzureAD/microsoft-authentication-library-for-java#296]

**Comment by navyasric** [comment]
This is to address the issue https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/294

**Comment by Avery-Dunn** [comment]
Fixed in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/300, and part of the 1.8 release https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/314
