### ISSUE TITLE
ClientCertificate is using SunJSSE provider hard coded and I can't change it

### ISSUE THREAD

**Issue by ihudedi** [AzureAD/microsoft-authentication-library-for-java#318]
When you trying to load client certificate you are using SunJSSE provider as hardcoded provider.
My java_security doesn't contain SunJSSE and it failed that no such provider.
com.microsoft.aad.msal4j.ClientCertificate ( version 1.8)
method create
final KeyStore keystore = KeyStore.getInstance("PKCS12", "SunJSSE"); ( line 72)
Could you please modify this and let the java decided in which provider to user ( remove the provider creating the keystore)
Thanks,
Itay

**Comment by SomkaPe** [comment]
Hi @ihudedi,  I agree - general purpose API should not be tied to specific provider.
We are going to include fix into next release.

**Comment by ihudedi** [comment]
Hi @SomkaPe 
Do you know which version will be the fix?
Thanks,
Itay

**Comment by Avery-Dunn** [comment]
Hello @ihudedi : Sorry for the long delay, but in case you were still looking for this the latest release, version 1.10, has the fix for this issue. If you have any related issues or questions, feel free to re-open this thread or leave a comment.
