### ISSUE TITLE
[Fundamentals] Rename master branch to main

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-java#319]
**Main branch**
_An inclusive new default_
New repos created within Microsoft orgs now have the default branch name of 'main'.

Teams are encouraged to rename their default branches if they are still using the 'master' branch name. This is an important, but not urgent, change.

**See more:**
https://repos.opensource.microsoft.com/

**Comment by sangonzal** [comment]
Created main branch, taking history from master. Updated release instructions to refer to main, and updated the release build to point to main. 

Will wait to delete the master branch until we can confirm next release that everything is working fine.

FYI @SomkaPe @Avery-Dunn - Releases should be from main moving forward.
