### ISSUE TITLE
Silent refresh of on-behalf-of tokens

### ISSUE THREAD

**Issue by sbellan** [AzureAD/microsoft-authentication-library-for-java#320]
I'm able to generate on-behalf-of tokens like this,

```
   ConfidentialClientApplication cca =
        ConfidentialClientApplication.builder(CLIENT_ID, secret)
            .authority(String.format(AUTHORITY, PRIMARY_DOMAIN))
            .logPii(true)
            .build();

    OnBehalfOfParameters parameters =
        OnBehalfOfParameters.builder(Collections.singleton(SCOPE_GRAPH),
            new UserAssertion(AUTH_TOKEN))
            .build();

    IAuthenticationResult result = cca.acquireToken(parameters).get();
```

The `result` has `accessToken` and `refreshToken` but no `idToken`. Since there is no `idToken`, the `result` does not have an `account` associated with it.

If there is no `account` reference in `SilentParameters`, automatic refresh of the tokens is not happening(`AcquireTokenSilentSupplier.java`)  even though there is a valid refresh token. 

Please let me know how can I use the sdk to automatically refresh 'on-behalf-tokens`

**Comment by Avery-Dunn** [comment]
Hello @sbellan: Silent refreshes can still be done even with no account, as `SilentParameters` does not need an account. When fetching/refreshing a token from the cache, all silent calls filter the cache based on scopes, authority, and client ID, and account is just an extra filter if it's provided. 

However, this means that your application needs a token cache for each user/account. Our [Web API sample](https://github.com/Azure-Samples/ms-identity-java-webapi) gives a good example of the on-behalf-of flow, and I believe demonstrates this per-user token cache behavior.

**Comment by sbellan** [comment]
Thanks, @Avery-Dunn 

I got misled by this piece of code then in AcquireTokenSilentSupplier (where refresh is attempted only if account is not null)
```
        if (silentRequest.parameters().account() == null) {
            res = clientApplication.tokenCache.getCachedAuthenticationResult(
                    requestAuthority,
                    silentRequest.parameters().scopes(),
                    clientApplication.clientId());
        } else {
            res = clientApplication.tokenCache.getCachedAuthenticationResult(
                    silentRequest.parameters().account(),
                    requestAuthority,
                    silentRequest.parameters().scopes(),
                    clientApplication.clientId());

            if (!StringHelper.isBlank(res.accessToken())) {
                clientApplication.getServiceBundle().getServerSideTelemetry().incrementSilentSuccessfulCount();
            }

            if (silentRequest.parameters().forceRefresh() || StringHelper.isBlank(res.accessToken())) {
                if (!StringHelper.isBlank(res.refreshToken())) {
                    RefreshTokenRequest refreshTokenRequest = new RefreshTokenRequest(
                            RefreshTokenParameters.builder(silentRequest.parameters().scopes(), res.refreshToken()).build(),
                            silentRequest.application(),
                            silentRequest.requestContext(),
                            silentRequest);

                    AcquireTokenByAuthorizationGrantSupplier acquireTokenByAuthorisationGrantSupplier =
                            new AcquireTokenByAuthorizationGrantSupplier(clientApplication, refreshTokenRequest, requestAuthority);

                    res = acquireTokenByAuthorisationGrantSupplier.execute();
                } else {
                    res = null;
                }
            }
        }
```
In my case, I was working with the same instance of `ConfidentialClientApplication` where I noticed that `acquireTokenSilently` did not return the token after initial token expired.  Even if I set `forceRefresh` in SIlentParameters, no refresh was happening.

**Comment by sbellan** [comment]
> The result has `accessToken` and `refreshToken` but no `idToken`. Since there is no `idToken`, the result does not have an account associated with it.

My problem of why the `idToken` was not returned turned out to be because of missing `openid` scope in the `on-behalf-of` token request. After adding that scope along with the graph scope, I get both access_token, id_token and the account is populated correctly and is able to refresh silently.

Thank you.
