### ISSUE TITLE
[Question] - How to use FederationMetadata.xml with MSAL

### ISSUE THREAD

**Issue by virjeej** [AzureAD/microsoft-authentication-library-for-java#323]
Hi, I'm trying to use MSAL in a java web app I'm working on.
Basically, I need to request an authentification token from an ADFS server, in order to authenticate users in my application with a username and a password.
The administrator of this ADFS server sent me an URL to a FederationMetadata.xml that I need to use to get this authentification token.

I did some research and from what I understood, this XML file contains the data needed to request the authentification token from the ADFS, and especially the endpoint on which the request has to be made.

The thing is, I don't really know how to use this XML file with MSAL. 
I tried to experiement with this example : https://github.com/Azure-Samples/ms-identity-java-desktop/tree/master/Username-Password-Flow , and one of my ideas is that I might need to configure the application.properties file with the URL to the FederationMetadata.xml . I'm just not sure where to put it.

CLIENT_ID=
USER_NAME=
USER_PASSWORD=
AUTHORITY=https://login.microsoftonline.com/organizations/
SCOPE=user.read

Or maybe do I just need to extract data from this XML manually (or with some parser) in order to request the authentification token from the ADFS server?

Thanks for your help.

**Comment by SomkaPe** [comment]
@virjeej  to acquire tokens from ADFS IP with MSAL you need to provide authority, client id, scopes.

ADFS identity provider can be federated with Azure AD, in this case MSAL will interact with Azure AD endpoints, The authority you use in this case is the usual authority (Azure AD authority host name + tenant ) - login.microsoftonline.com/TENANT.

MSAL also supports acquisition of tokens directly from Open ID Connect compliant ADFS 2019. The authority you'll want to use to build your application is similar to https://mysite.contoso.com/adfs/.

**Comment by virjeej** [comment]
Thanks for your answer @SomkaPe!

So, I managed to get an error saying that my credentials couldn't be validated, which is good!
I specified the authority just as you said, with login.microsoftonline.com/<TENANT DOMAIN NAME>/

My question was more about the FederationMetadata.xml file, and if MSAL could process it in order to extract the authority and request the token. But maybe I just misunderstood the use of this file, and maybe I shouldn't even bother trying to use it.

**Comment by Avery-Dunn** [comment]
@virjeej : Yeah, MSAL shouldn't need that file. Most of the authentication flows just need to be provided an authority, client ID, and scopes, and occasionally some extra flow-specific info. So if you want a certain authority from your FederationMetadata.xml file you can parse that out and provide it, but the library should be able to handle the rest.
