### ISSUE TITLE
What about supporting SAML 2.0 in this library?

### ISSUE THREAD

**Issue by aukhatov** [AzureAD/microsoft-authentication-library-for-java#329]
Hi everyone!
I have a concern to use this library.
Could you explain me about supporting SAML 2.0 Protocol there?

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-saml-protocol-reference

**Comment by sangonzal** [comment]
@aukhatov MSAL implements the OAuth2.0 and OpenID Connect protocols, and does not support SAML 2.0. You can read more about the supported scenarios in the [wiki page](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Scenarios)

**Comment by aukhatov** [comment]
@sangonzal Thank you.
What about the future? Will this library support the SAML 2.0?

**Comment by aukhatov** [comment]
### There is a second part of the question
Now we use SAML 2.0 to authenticate via the `https://login.microsoftonline.com` endpoint.
**Could we just replace SAML 2.0 authentication way with MSAL?**
My point is based on the same endpoint to authenticate, according to the documentation paper https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud and https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/main/java/com/microsoft/aad/msal4j/IClientApplicationBase.java#L18 where the default authority endpoint is `https://login.microsoftonline.com`.

**Comment by sangonzal** [comment]
@aukhatov The short answer is that there are no plans to support SAML 2.0 in MSAL. The longer answer is that if you look int the code, you'll actually see that we use SAML assertions internally for certain scenarios (for example federated username password flow), but these details are never exposed to the user. From the perspective of the user, you are just doing OAuth2.0 username password grant. 

Can you provide more details about your scenario? Are you starting a new project or working with a legacy system?

**Comment by aukhatov** [comment]
@sangonzal  I'm working with legacy software.
We also use SAML 2.0 for **federated username password flow**. And we must support it because our customers already use it and authenticated in this way.

When MS announced about closing and supporting the ADAL library and released the MSAL we have been started the migration to the MSAL. And during migration, I've just found how we use username+password auth flow. But I can't support this flow by the MSAL. This is my concern.

@sangonzal Is this information enough for you? Do you have additional questions?

**Comment by sangonzal** [comment]
@aukhatov If I understand correctly, you already have a working implementation in ADAL, and are trying to migrate to using MSAL? 

If so, then MSAL supports all scenarios supported by ADAL, and you should be able to migrate. Take a look at the [Username Password sample](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/samples/public-client/UsernamePasswordFlow.java) and see if it works for you.

 If you are running into any issues migrating from ADAL to MSAL, please post the ADAL code here and details about the error.

**Comment by aukhatov** [comment]
@sangonzal You understood almost correctly. I misled you a little about my concerns.
We have also the way when we use Federated or Managed (according to the user realm) username+password authentication for our customers. And my concerns are related to that.

**Comment by sangonzal** [comment]
@aukhatov MSAL can handle username+password for both managed and federated users without you having to worry about this. From your end, it looks the same for managed vs federated, without having to worry calling the user discovery endpoint or implementing SAML. You can see how it's done [here](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/main/java/com/microsoft/aad/msal4j/AcquireTokenByAuthorizationGrantSupplier.java#L77)

**Comment by aukhatov** [comment]
@sangonzal Thank you!
How can I use that?
I don't know how should I create a `com.microsoft.aad.msal4j.PublicClientApplication` instance without **clientId**?

**Comment by aukhatov** [comment]
@sangonzal Could you share some examples of usage?

**Comment by sangonzal** [comment]
@aukhatov This [sample](https://github.com/Azure-Samples/ms-identity-java-desktop/) has instructions on how to register an application in the azure portal, as well as the code for acquiring tokens.

You'll need an app registration to use MSAL. When you register the application you'll receive the clientId. I assume even when you used your own implementation, you still had to register an app in Azure Active Directory?

**Comment by aukhatov** [comment]
@sangonzal Hi!
Actually yes, if I register an app it is easiest to acquire a token.
But what in the case when I don't have a registered app in Azure AD? Just by username and password.

**Comment by sangonzal** [comment]
@aukhatov having a registered app is a prerequisite for using MSAL. Client registration is part of the [OAuth2.0 Spec](https://tools.ietf.org/html/rfc6749#section-2). Without a client identifier, you can't interact with Azure AD via OAuth2.0

**Comment by aukhatov** [comment]
@sangonzal Great.
I think we can close this question.
Thanks.
