### ISSUE TITLE
Upgrade oauth2-oidc-sdk Dependency Major Version

### ISSUE THREAD

**Issue by alzimmermsft** [AzureAD/microsoft-authentication-library-for-java#335]
Upgrade the `oauth2-oidc-sdk` dependency major version to `8.x.x` to allow `msal4j` to be compatible with the latest Spring Framework release. Beginning in the newest release of Spring Framework they upgraded their dependency of `oauth2-oidc-sdk` to `8.23.1`, upgrade from version `7.1.1` in their last major release. Given that `msal4j` depends on version `7.4` of the library this can result in potential compile or runtime exceptions when using `msal4j` with the latest Spring Framework.

**Comment by joshfree** [comment]
This dependency conflict is blocking the azure/azure-sdk-for-java repo from upgrading and releasing new Spring Boot Starters that support the latest Spring Framework

/cc @jialindai as fyi

**Comment by Avery-Dunn** [comment]
Hello @alzimmermsft and @joshfree : We've started investigating how best to upgrade the `oauth2-oidc-sdk` dependency while minimizing any breaking changes for those still using the old Spring Framework. I'll update this thread once we have the exact fix, but we'll definitely have at least some fix in the next release (most likely next week).

Also, are you using version 1.8.1 of msal4j? We had a related issue (https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/316) some time back and it seemed like the library was now working for Spring Boot 2.4/oauth2-oidc-sdk 8.23.1

**Comment by alzimmermsft** [comment]
Thanks for the response @Avery-Dunn. 

Appears we are using version `1.8.0` as our dependency, I'll upgrade this to `1.8.1` and reply back once I do some testing.

**Comment by AmanVm13** [comment]
Hi @Avery-Dunn 

Thanks for your comment, I was also facing same issue with upgrade to spring boot 2.4.0. Upgrade of msal4j to 1.8.1 resolved my issue.

**Comment by davidkarlsen** [comment]
Try boot 2.4.3 - it seems they added a fix for consistent library versions.

**Comment by Avery-Dunn** [comment]
Closing this thread as all issues related to Spring and its dependencies appear to be solved: as of version 1.8.1 MSAL Java uses version 8.x of `oauth2-oidc-sdk`, and as covered in https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/348 a dependency issue in Spring Boot 2.4.2 was resolved in Spring Boot 2.4.3 so our library should now work in all versions of Spring Boot 2.4.x (except 2.4.2, see https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/348), as well as any versions of Spring Boot that the library worked in before these changes.

If y'all have any other related issues or questions, feel free to leave a comment or re-open the thread.
