### ISSUE TITLE
Release pipeline should use main and not master

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-java#337]
When renaming master to main, it was not a rename, it was a clone and master was not removed, thus the work on updating the build pipelines was not completed. This work item is to track completion of this work. 

Readme updated to point to main, which says it was never built. Assuming there should be a nightly build of main, as well as new builds to be triggered when changes are merged in.

Before cloing up, the master branch should be removed. Should not be an issue as everything is now tracked in main.

**Comment by sangonzal** [comment]
Master has been renamed to main. Master was deleted, and release 1.9.1, was done out of main.

**Comment by henrik-me** [comment]
Thanks, I now see the build pointing to main have a build :)
