### ISSUE TITLE
Failed serialization for IAuthenticationResult

### ISSUE THREAD

**Issue by burhanelgun** [AzureAD/microsoft-authentication-library-for-java#338]
I want to serialize the IAuthenticationResult but, I can't serialize it. I am using version 1.8.1.

I got `"java.io.NotSerializableException: com.microsoft.aad.msal4j.AuthenticationResult"` exception, when I run below command
```
.......
IAuthenticationResult authResult = app.acquireToken(parameters); // I can get IAuthenticationResult successfully
ByteArrayOutputStream bos = new ByteArrayOutputStream();
ObjectOutputStream out = new ObjectOutputStream(bos);
out.writeObject(authResult);   // Exception throwed
........
```
How can I serialize it?

**Comment by xsimo** [comment]
@burhanelgun How did you resolve this issue ? 
I tried to use the implementing class `com.microsoft.aad.msal4j.AuthenticationResult` but that class is not declared public as of version 1.9.1
