### ISSUE TITLE
How can I setup the number of retries and the retry interval when HTTP 429 occurred?

### ISSUE THREAD

**Issue by aukhatov** [AzureAD/microsoft-authentication-library-for-java#349]
Hi!
I want to control how many times authentication requests can be called when 429 occurred? And the retry interval also.

**Comment by SomkaPe** [comment]
429 response typically contains Retry-After header which should be respected by clients, ignoring that ask may lead to more aggressive throttling. Could you please provide more details about your scenario ?

**Comment by aukhatov** [comment]
@SomkaPe we would like to control the timeout value and number of attempts from our side.
we had a lot of experiences working with Microsoft services, and sometimes the Retry-After not actually true. And it's the reason why we want to control these values from our side.

**Comment by aukhatov** [comment]
@sangonzal Could you help me?

**Comment by SomkaPe** [comment]
Current implementation is done according to Azure AAD identity service provider request. Retry timeout is determined based on Retry-After header, if it is absent default value 120 sec is used, also throttling is limited by 3600 seconds by client. The reason why this was requested is clients who do not respect server side instructions, which lead to more aggressive throttling of such clients. Could you please explain how do you plan to determine if Retry-After value true or false ?

**Comment by aukhatov** [comment]
@SomkaPe How many attempts are set by default?

**Comment by SomkaPe** [comment]
2 retries ( 3 attempts ), but only for transient errors ( codes [500, 600) ), 429 is not considered as transient.

**Comment by aukhatov** [comment]
@SomkaPe Why did you exclude `429`?

**Comment by SomkaPe** [comment]
@aukhatov 429 response means that service ask you to retry request after some delay, retrying earlier most likely would not help. Retrying make sense in case of network errors or  500 Internal Server Error, so retrying is likely to receive different response.
