### ISSUE TITLE
Issue in ROPC flow in  public client

### ISSUE THREAD

**Issue by maxynandy** [AzureAD/microsoft-authentication-library-for-java#350]
When I tried ROPC using public client i am getting below error:
code snipped:
UserNamePasswordParameters userNamePasswordParameters = UserNamePasswordParameters.builder(scopes,email,password.toCharArray()).build();
PublicClientApplication publicClientApplication = PublicClientApplication.builder(clientId)
.authority(AUTHORITY).build();
CompletableFuture future = publicClientApplication.acquireToken(userNamePasswordParameters);

Error:
16:30:41.219 [ForkJoinPool.commonPool-worker-1] INFO com.microsoft.aad.msal4j.WSTrustResponse - Found token of type: urn:oasis:names:tc:SAML:1.0:assertion
16:30:41.583 [ForkJoinPool.commonPool-worker-1] ERROR com.microsoft.aad.msal4j.PublicClientApplication - [Correlation ID:xxxx] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.
com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance.

@Avery-Dunn .Please note we are getting token using Dot net code  with same  AD configuration.

**Comment by maxynandy** [comment]
Thanks @Avery-Dunn .Its due to conditional access policy and resolved by adding user agent parameter which is expected in http  header. 
PublicClientApplication publicClientApplication = PublicClientApplication.builder(clientIdIlab).httpClient(**iHttpClient**)
                .authority(AUTHORITY).build();

**Comment by Avery-Dunn** [comment]
Hello @maxynandy : So, is your issue resolved after adding that header and everything is working as expected now? If so, good to hear, and I'll probably be adding a new page to the repo's wiki about how to get things working with conditional access policies.

**Comment by maxynandy** [comment]
@Avery-Dunn yes its working as expected.thanks.
