### ISSUE TITLE
How to retrieve an access token using a refresh token

### ISSUE THREAD

**Issue by manuelmazzuola** [AzureAD/microsoft-authentication-library-for-java#355]
I would like to do this call, that gather an access token using the refresh token
(https://docs.microsoft.com/en-us/graph/auth-v2-user#request)

I already have the refresh token, all i want is to generate a new access token using it.
Is it possible using MSAL4j?

**Comment by sangonzal** [comment]
Hi @manuelmazzuola, if you have a refresh token you can get new tokens, but the new refresh token that is returned will not be exposed to you. MSAL will instead manage the refreshing of tokens for you, and you instead should use the `acquireTokenSilently` API. `AcquireTokenSilently` will automatically look in the `TokenCache` for you, and return an access token if you have a valid one, if not will try to refresh it with the refresh token, and if not will throw an exception, at which point you can fall back to using an interactive flow for acquiring tokens. You can then just store the whole `TokenCache`, which will contain all of the tokens returned as well as the account. You can then later load the whole `TokenCache` object into the `ClientApplication`

This [documentation here](https://docs.microsoft.com/en-us/azure/active-directory/develop/migrate-adal-msal-java#adal-to-msal-migration) will show you how you can acquire new tokens with a refresh token for the first time.

**Comment by sangonzal** [comment]
Feel free to ask any other questions if they arise.
