### ISSUE TITLE
MsalInteractionRequiredException.correlationId() seems to contain the same value as statusCode

### ISSUE THREAD

**Issue by Mark-Palmer-Imprivata** [AzureAD/microsoft-authentication-library-for-java#357]
Here is a dump of the exception information:
errorCode=invalid_grant
message=AADSTS50057: The user account is disabled.
Trace ID: cc99e083-2e57-470b-bf1b-a3c5c6fa1500
Correlation ID: 6006855a-47ac-46c9-a9f7-42b1629d0803
Timestamp: 2021-02-26 12:53:34Z
-----end of message----
correlationId=400
statusCode=400
statusMessage=null
claims=null
reason=NONE

Note that the "message" contains the Correlation ID, but the correlationId() function contains the same value as the statusCode.

This definitely happens for very MsalInteractionRequiredException that has been encountered.  It is unknown whether this holds true for other child classes of MsalServiceException.

**Comment by sangonzal** [comment]
@Mark-Palmer-Imprivata what version of MSAL are you using? Can you provide steps to reproduce? 

I am not able to reproduce this behavior on my end:
![missingCorrelationId](https://user-images.githubusercontent.com/35743865/109527412-3d1eeb00-7a79-11eb-8363-f44cbc53dfc2.PNG)
