### ISSUE TITLE
Is there any reason why response_type  set to "code" only in the default implementation of AuthorizationRequestUrlParameters?

### ISSUE THREAD

**Issue by JoshuaAtEriks** [AzureAD/microsoft-authentication-library-for-java#370]
Hi ,
I am using msal jar to follow authorisation flow for my java app .During building/preparing the url i can see that the response_type option is not available in the client and when I checked implementation i see it is set to code by default in AuthorizationRequestUrlParameters.
**requestParameters.put("response_type",Collections.singletonList("code"));**
How to proceed if i want to use msal jars in my implementation ?
Thanks

**Comment by sangonzal** [comment]
Hi @JoshuaAtEriks, response_type=code is a required parameter for the OAuth2.0 authorization code flow. For more details about this flow, see this [documenation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow).

What would you like to set response_type to instead?

**Comment by JoshuaAtEriks** [comment]
hi @sangonzal ,
Thanks for your response .I do know it is a mandatory param, but i am seeing if it is possible to use other param values like 'id_token' instead of 'code' without extending AuthorizationRequestUrlParameters?
Thanks

**Comment by sangonzal** [comment]
It is not currently possible. `AuthorizationRequestUrlParameter` is a precursor to AuthorizationCodeParameters, where an authorization code is required, so we decided to make this the mandatory value.

**Comment by JoshuaAtEriks** [comment]
Thanks @sangonzal
