### ISSUE TITLE
Login via commons requires client secret

### ISSUE THREAD

**Issue by adrianorapussi** [AzureAD/microsoft-authentication-library-for-java#374]
I'm following some tutorials to embed a report from power bi and came across a sample code with this lib, after some time I got the following error in a reponse.

I'm guessing the endpoint has changed at some point, but the documentation hasn't 

POST https://login.microsoftonline.com/common/oauth2/token

``` JSON
{
    "error": "invalid_client",
    "error_description": "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: 155fc144-9260-416d-9ce3-e3f4bb59e700\r\nCorrelation ID: 91d62d6f-231b-462e-bb9a-141075a34f07\r\nTimestamp: 2021-04-22 22:33:05Z",
    "error_codes": [
        7000218
    ],
    "timestamp": "2021-04-22 22:33:05Z",
    "trace_id": "155fc144-9260-416d-9ce3-e3f4bb59e700",
    "correlation_id": "91d62d6f-231b-462e-bb9a-141075a34f07",
    "error_uri": "https://login.microsoftonline.com/error?code=7000218"
}
```

**Comment by sangonzal** [comment]
@adrianorapussi Can you link to the tutorial?

**Comment by adrianorapussi** [comment]
Sure, 

https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers?tabs=java

**Comment by sangonzal** [comment]
@adrianorapussi Did you follow the instructions, specifically step 8.10? The error message is saying that no client secret was included in the request to AAD. When you register the application on AAD, you can create a secret, and then you have to put in the config file of the tutorial's application. 

If you did follow the instructions and are still having issues with their tutorial, you can open an issue on their GitHub page, the feedback link is at the bottom of the tutorial that you linked to. They will best be able to help you, as this is not an MSAL issue.
