### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.sun.net.httpserver.HttpHandler" in Android 

### ISSUE THREAD

**Issue by erikhakansson** [AzureAD/microsoft-authentication-library-for-java#383]
Hello!

I'm a bit unsure if this is the right place to open this issue, so please tell me if I'm barking up the wrong tree.

According to https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Android, an `InteractiveBrowserCredential` should be used on Android to acquire a token for the Graph api. 

Eventually that ends up in an instantiation of an `AuthorizationResponseHandler` from this library which results in a `java.lang.ClassNotFoundException` since `AuthorizationResponseHandler` implements and imports a bunch of classes from `com.sun.net.httpserver.*` and `com.sun` stuff isn't available in Android.

I couldn't find any references to Android in the readme of this project so perhaps it isn't intended for Android use, but at the same time the official Microsoft documentation for using Microsoft Graph SDK for Android leads me here.

So, i guess my issue is two-fold:

1. Should I even open this issue here, or should I open it with the Graph SDK people?
2. If the issue does belong here, how do I get around using `com.sun` packages?

Thanks!

**Comment by Avery-Dunn** [comment]
Hello @erikhakansson : Just to be clear, you're trying to create an Android application that acquires tokens from the Graph API, right? If so, what you actually want is [MSAL Android](https://github.com/AzureAD/microsoft-authentication-library-for-android), that's our library for Android applications. This repository is for [MSAL Java](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-overview#languages-and-frameworks), our library for Java applications.

**Comment by erikhakansson** [comment]
Thank you @Avery-Dunn. You're absolutely right that I'm using the wrong library. It works much better when using the Android one, and especially following the documentation in that repo.

In my defense though, the documentation on the link in my first post (which is linked from https://github.com/microsoftgraph/msgraph-sdk-java) suggests that the same code should be used for both regular Java and Android, i.e:
```
final InteractiveBrowserCredential interactiveBrowserCredential = new InteractiveBrowserCredentialBuilder()
                .clientId(clientId)
                .redirectUrl("http://localhost:8765")
                .build();
final TokenCredentialAuthProvider tokenCredentialAuthProvider = new TokenCredentialAuthProvider(scopes, interactiveBrowserCredential);
```
which is what threw me off initially.

That's an issue for the Graph SDK people, though, and not an issue with this library 😄
