### ISSUE TITLE
Unexpected many INFO logs in AcquireTokenByOnBehalfOfSupplier

### ISSUE THREAD

**Issue by blacelle** [AzureAD/microsoft-authentication-library-for-java#384]
Our application reports many INFO logs due to:

https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/main/java/com/microsoft/aad/msal4j/AcquireTokenByOnBehalfOfSupplier.java#L24

We can configure this in our logging configuration, but it seems like an error in the configured error level.

**Comment by sangonzal** [comment]
@blacelle I think INFO can be considered appropriate here, but can also see how it would case too much noise in someone's logs. We will consider moving down to either DEBUG or TRACE.

**Comment by blacelle** [comment]
If INFO is considered appropriate here,I would expect more INFO logs in other components, typically ones being more transverse. I use msal4j with INFO logs by default, but I see only logs from this class, which looks awkward to me

**Comment by sangonzal** [comment]
@blacelle Thats fair, I agree that this is inconsistent with logging in other parts of the library (which is almost nonexistant). I was hoping to start adding new logging in with new changes, but they should probably all go in at once to keep the consistency throughout.
