### ISSUE TITLE
PublicClientApplication.acquireToken with UsernamePasswordParameters has high latency

### ISSUE THREAD

**Issue by Mark-Palmer-Imprivata** [AzureAD/microsoft-authentication-library-for-java#389]
Latency for authenticating a user with their password is pretty high.  In our tests we have seen times of 350ms to 800ms or more.  Our use case is to always verify the users password with Azure AD - we are not using the MSAL4j cache (after successful authentication, we remove the user account from the cache), and we are not doing any "acquire silently" calls.

Investigation into what MSAL4j does reveals the following:
1. First, an HTTP GET call is made to this URL:  https://login.microsoftonline.com/common/userrealm/<user_upn>?api-version=1.0 - this call can cake 75ms to 300+ms.
2. It looks like if the user is "Federated", this could result in a WS-Trust call, which is expected to add additional latency.
3. Finally, an HTTP POST call is made to authenticate the user with their username and password.

The URL in step 3 is the only one defined by OAuth 2.0 ROPC, and the calls in steps 1 and 2 are unnecessary for our use case.  There does not appear to be a way to disable these calls.

Two questions:
1. Can an enhancement be added which disabled any calls other than the HTTP POST to handle the authentication with username and password?
2. Is there anything that can be done to further reduce the latency when performing this authentication?

**Comment by Avery-Dunn** [comment]
Hello @Mark-Palmer-Imprivata : The calls to that URL are to grab some account information for the user, mainly for info on whether the account is federated or managed since we need to handle them differently. We'll discuss adding an option to skip this step if you know a given user is/isn't federated, and I'll update this thread once that happens.

If you don't mind saying, why do you not use the cache or make silent calls? That probably would significantly improve the response times if latency is an issue.

**Comment by Mark-Palmer-Imprivata** [comment]
> Hello @Mark-Palmer-Imprivata : The calls to that URL are to grab some account information for the user, mainly for info on whether the account is federated or managed since we need to handle them differently. We'll discuss adding an option to skip this step if you know a given user is/isn't federated, and I'll update this thread once that happens.
> 
This would be very useful to skip any HTTP calls with aren't related to OAuth 2.0 ROPC - we are only making this call to authenticate the user with their password.  There is no need to know whether the user is Federated or not.

> If you don't mind saying, why do you not use the cache or make silent calls? That probably would significantly improve the response times if latency is an issue.
For our use case, we always need to freshly verify the users password.  In this case, the latency definitely appears to be on the Microsoft server side.  Are there any other things that a client can do that might reduce the latency further?

We tried switching from the "common" endpoint **https://login.microsoftonline.com/organizations/** to a tenanted endpoint like the following:  **https://login.microsoftonline.com/{tenantId}/v2.0/oauth2/token**

This URL worked, but we didn't notice much change in the latency.

**Comment by SomkaPe** [comment]
@Mark-Palmer-Imprivata  steps 1 and 2 are necessary to support federated accounts. Do you need to support them?

**Comment by Mark-Palmer-Imprivata** [comment]
@Avery-Dunn I noticed that this has been categorized as a question, when this is really an enhancement request to improve performance.

**Comment by SomkaPe** [comment]
@Mark-Palmer-Imprivata
"This would be very useful to skip any HTTP calls with aren't related to OAuth 2.0 ROPC - we are only making this call to authenticate the user with their password. There is no need to know whether the user is Federated or not."  
- There is a need to know whether user is federated or not, for federated users SAML based authorization grant is used.
- For both types of users OAuth 2.0 ROPC  is used, but different types of authorization grants
- Majority of work accounts are federated

**Comment by Mark-Palmer-Imprivata** [comment]
> @Mark-Palmer-Imprivata
> "This would be very useful to skip any HTTP calls with aren't related to OAuth 2.0 ROPC - we are only making this call to authenticate the user with their password. There is no need to know whether the user is Federated or not."
> 
> * There is a need to know whether user is federated or not, for federated users SAML based authorization grant is used.
> * For both types of users OAuth 2.0 ROPC  is used, but different types of authorization grants
> * Majority of work accounts are federated

Our use case is strictly verifying the users password - we have no need of any other functionality.  Hence the request to allow disabling the Federated checks.

**Comment by Avery-Dunn** [comment]
@Mark-Palmer-Imprivata : Just to be clear, you're only using the library to verify user's credentials? Not using tokens, not accessing any Azure resources, etc.? If so, that's not really a use case our library is meant to cover, and even if we fix this specific issue it'll never be as performative as something more dedicated. 

However, I believe that [any OpenID Connect provider](https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-provider-openid-connect) can be used to authenticate users, so if you don't need any of the features of our library then perhaps there's is something more lightweight out there that you could use?

**Comment by Mark-Palmer-Imprivata** [comment]
Correct - for users, we only need to verify the username/password.  At the moment, we discard the returned accessToken.
We also use the ConfidentialClientApplication for obtaining an accessToken so that our service can use Microsoft Graph to read information from Azure AD.

Being able to use the same library for both operations has value.

I don't believe the ROPC flow described by the library (or the example repository) go into any detail around these other HTTP calls that the library makes related to userrealm and WS-Trust.

Here's the link to the example I'm referring to:  https://github.com/Azure-Samples/ms-identity-java-desktop.git

**Comment by Avery-Dunn** [comment]
@Mark-Palmer-Imprivata : Sorry for the delayed response, but I just wanted to update you on our discussions on this: we currently don't have any plan/timeline for implementing a way for devs to control how the library handles federated vs. non-federated users. 

However, we may make this change if/when we have some more use cases where this would be needed or add more optional functionality that only applies to one or the other. So, I'll leave this thread open for now and mark it as an enhancement, in case we either have a need to make the change in the near future or more definitively decide not to do it.

**Comment by bgavrilMS** [comment]
Will be closing this. Please ensure you call AcquireTokenSilent to reuse cached tokens.

We are not improving legacy auth.
