### ISSUE TITLE
How to initilize a Graph Client (from the graph-java-sdk) in the OBO scenario ?

### ISSUE THREAD

**Issue by RPerles** [AzureAD/microsoft-authentication-library-for-java#398]
Hello.

I have a hard time to figure out how to initialize a GraphServiceClient object in the OBO scenario.

I have implemented the MSAL4J library with the OBO scenario and everything is working well, but I don't find how to create an OnBehalfOf provider in order to get the graph client in the way it is intended by the graph sdk
 https://github.com/microsoftgraph/msgraph-sdk-java#23-get-a-graphserviceclient-object

Sorry if I missed something, and thanks in advance for your time!

**Comment by sangonzal** [comment]
Hi @RPerles - take a look at [OboAuthProvider](https://github.com/Azure-Samples/ms-identity-java-webapi/blob/update-sample/msal-obo-sample/src/main/java/com/microsoft/azure/msalobosample/OboAuthProvider.java) in the Java Web API sample.

**Comment by RPerles** [comment]
Thanks a lot @sangonzal !

That's definitely what was missing to make it work, sorry for the inconvenience I didn't see this branch and therefore the file, so I think I'm good to go with that !

Again thank you for your quick response and support !

**Comment by RPerles** [comment]
Thanks a lot @sangonzal !

That's definitely what was missing to make it work, sorry for the inconvenience I didn't see this branch and therefore the file, so I think I'm good to go with that !

Again thank you for your quick response and support !
