### ISSUE TITLE
How to execute PublicClientApplication.acquireToken() synchronously?

### ISSUE THREAD

**Issue by Mark-Palmer-Imprivata** [AzureAD/microsoft-authentication-library-for-java#403]
We have a desire to make this call run in the callers thread - we want it to be a blocking call.  No matter what I try, this call always seems to execute in another thread - in the log4j logs, the thread only appears as "Thread -8".  I'm not sure where this thread is coming from.

Is there a way to make this call explicitly run within the calling thread?

**Comment by Mark-Palmer-Imprivata** [comment]
> @Mark-Palmer-Imprivata You can pass in an ExecutorService with the thread pool you'd like MSAL to use. The Executor service is set on the `ClientApplication` builder.

That will still have MSAL4j use another thread for making the request.

**Comment by sangonzal** [comment]
@Mark-Palmer-Imprivata If you want to block the calling thread on the execution if the MSAL thread, you can just call .get() on the future returned from MSAL. `result = pca.acquireToken(parameters).get();`

**Comment by Mark-Palmer-Imprivata** [comment]
> @Mark-Palmer-Imprivata If you want to block the calling thread on the execution of the MSAL thread, you can just call .get() on the future returned from MSAL. `result = pca.acquireToken(parameters).get();`

We are currently doing that.  The point is that we want to prevent MSAL from using a new thread, but I can't prevent it from happening.

**Comment by sangonzal** [comment]
@Mark-Palmer-Imprivata It seems that you'll have to implement your own custom executor service, and pass that into MSAL. A quick google search returns this [thread](https://stackoverflow.com/questions/6581188/is-there-an-executorservice-that-uses-the-current-thread), which provides possible ways of doing this.

**Comment by Mark-Palmer-Imprivata** [comment]
> @Mark-Palmer-Imprivata It seems that you'll have to implement your own custom executor service, and pass that into MSAL. A quick google search returns this [thread](https://stackoverflow.com/questions/6581188/is-there-an-executorservice-that-uses-the-current-thread), which provides possible ways of doing this.

Thank you - this was helpful.
