### ISSUE TITLE
How to use extraScopesToConsent when creating AuthorizationRequestUrlParameters?

### ISSUE THREAD

**Issue by javate** [AzureAD/microsoft-authentication-library-for-java#404]
When do we need this `extraScopesToConsent` parameter? It can be passed like below when creating `AuthorizationRequestUrlParameters` object.

```
AuthorizationRequestUrlParameters parameters =
        AuthorizationRequestUrlParameters
                .builder(redirectUri,
                        scopes).extraScopesToConsent("someExtraScope")
                .responseMode(ResponseMode.QUERY)
                .prompt(prompt)
                .state(state)
                .nonce(nonce)
                .claimsChallenge(claims)
                .build();
```

I think if I need some scopes that they belong different audiences/resources, I can use it. Am I right?

However when I check the source code of this `AuthorizationRequestUrlParameters`. It simply merged the`scopes` and `extraScopesToConsent` like below:

```
this.scopes = builder.scopes;
String[] commonScopes = "openid profile offline_access".split(" ");
Set<String> scopesParam = new LinkedHashSet(Arrays.asList(commonScopes));
scopesParam.addAll(builder.scopes);
if (builder.extraScopesToConsent != null) {
    scopesParam.addAll(builder.extraScopesToConsent);
}
```

Then why this parameter exposed and usable? Am I missing a point?

**Comment by sangonzal** [comment]
@javate You're understanding is correct, extraScopesToConsent is used for acquiring tokens for a separate resource. The parameters are merged together, but you'll notice that they are placed in a specific order. This is an implementation detail that users shouldn't have to be concerned with - therefore there is a separate parameter.

If you want to get a token for the second resource, you'll have to acquireTokenSilently with those scopes. Although this [doc](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-user-gets-consent-for-multiple-resources) is for the MSAL.NET, the same pattern applies to Java.
