### ISSUE TITLE
'openid profile offline_access' is not valid error when calling acquireToken method with code

### ISSUE THREAD

**Issue by javate** [AzureAD/microsoft-authentication-library-for-java#407]
I am using Authorization Code Flow. I want to get consent for two different audiences/resources in one login popup.
So, I know that it is needed for `acquireToken` for first audience and then `acquireTokenSilently` for second audience.

However I got below error when calling `acquireToken` method:

> AADSTS28002: Provided value for the input parameter scope 'openid profile offline_access' is not valid when requesting an access token. Please specify a valid scope.

I remember that I didn't get this error when I tried this scenario last week.

I am using below URL for opening popup. Since `AuthorizationRequestUrlParameters` generated it. I passed `https://graph.microsoft.com/User.ReadWrite.All` to its `scopes` parameter . And I passed to `https://teamsconfigapi-int.trafficmanager.net/user_impersonation` to its `extraScopesToConsent` parameter. 
Also, I didn't add the `openid, profile, offline_access` scopes, it is added to url automatically by the library.

Then below url is generated.

`https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?scope=openid+profile+offline_access+https%3A%2F%2Fgraph.microsoft.com%2FUser.ReadWrite.All+https%3A%2F%2Fteamsconfigapi-int.trafficmanager.net%2Fuser_impersonation&response_type=code&redirect_uri=https%3A%2F%2Flocalhost%3A8080%2Flogin&state=bd237c04-76b6-4a76-beca-fe4650c1f64d&nonce=3eab6371-df43-5cga-aded-a106fed74ab6&prompt=consent&client_id=56b7k4bh-8ce4-4b45-adkd-c51cdf5t52c2&response_mode=query`

Note: Also, when I getting `https://graph.microsoft.com/User.ReadWrite.All` and `https://teamsconfigapi-int.trafficmanager.net/user_impersonation` consents separately(in two different login popup), there is no any problem. I can get `AuthenticationResult` objects both of them separately.

Why I got this error?

**Comment by sangonzal** [comment]
@javate what are the scopes that you are passing into the acquire token call? Also, you said this was working last week, and now it's not - were there any changes to your code in the mean time?

**Comment by javate** [comment]
@sangonzal `acquireToken` call doesn't accept the `scopes`. I gave it the `code` and the `redirectUri`.

```
AuthorizationCodeParameters authorizationCodeParameters = AuthorizationCodeParameters.builder(authCode, new URI(redirectUri)).build();
Future<IAuthenticationResult> future = confidentialClientApplication.acquireToken(authorizationCodeParameters);
IAuthenticationResult authenticationResult = future.get(1, TimeUnit.MINUTES);

```
I remember that I didn't make a code change which can cause this problem from last week.

**Comment by sangonzal** [comment]
@javate You can pass in a scope to the authorization code parameters builder this way: 

`AuthorizationCodeParameters.builder(authCode, new URI(redirectUri)).scopes(Collections.singleton("https://graph.microsoft.com/User.ReadWrite.All")).build();`

If you pass in the graph scope here, does that change anything?

**Comment by javate** [comment]
@sangonzal I have never use `scopes` for `acquireToken` method. However until last week it is worked. Actually, I don't want to use `scopes`. and I wonder why this error started to occurred.

**Comment by sangonzal** [comment]
@javate This is not a workaround, this is the right pattern for acquiring a token to multiple resources at once. The sample is indeed different, but that's because it's a different scenario - it doesn't show acquiring tokens for multiple resources.  

I just tried this scenario and can confirm that what I am suggesting works: 
- Build `AuthorizationRequestUrlParameters` with both scopes, and consent to them both at the same time.
- Build `AuthorizationCodeParameters` with the first scope, and acquire tokens for the first resource.
- Build `SilentParameters` with the second scope, and acquire tokens for the second resource. 

The token cache will now have tokens for both resources.

**Comment by sangonzal** [comment]
Closing as I never heard back. Feel free to reopen if you are still facing issues.
