### ISSUE TITLE
SSO with no client secret/client certificate

### ISSUE THREAD

**Issue by 701chang** [AzureAD/microsoft-authentication-library-for-java#411]
I'm working on a Java web application, trying to implement SSO, and the request is to implement SSO with no client secret and no client certificate. At first I tool reference from this msal-web-sample(https://github.com/AzureAD/microsoft-authentication-library-for-java/tree/e6a10f415d1683d1fee2c1847e4de8043b6cad6e/src/samples/msal-web-sample), and realized the ConfidentialClientApplication requires a client secret/certificate to initialize, then I switched the ConfidentialClientApplication to PublicClientApplication, then the response is giving me an exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

Please advise where I might be doing wrong and maybe point out where I may need to head down next.

**Comment by sangonzal** [comment]
@701chang Why do you want to avoid using a client secret/ certificate? 

If you are updating you client code from ConfidentialClientApplication to PublicClientApplication, I believve you'll also need to update your application type on the Azure application registration portal.

**Comment by 701chang** [comment]
> @701chang Why do you want to avoid using a client secret/ certificate?
> 
> If you are updating you client code from ConfidentialClientApplication to PublicClientApplication, I believve you'll also need to update your application type on the Azure application registration portal.

Thanks for replying! It's strongly asked by the customer, they told that none of their other applications uses client secret/certificate, so they don't want us to implement with one. I did not see too much documents saying whether this is supported, but they insist on it.

With what you responded, it sounds like as a Java web application, I shouldn't use PublicClientApplication and should only use ConfidentialClientApplication, correct? And is there any way we can circumvent a client secret/certification?

**Comment by sangonzal** [comment]
If it's a web application, the right way to acquire tokens is via ConfidentialClientApplication, but this will require using either a client secret/certificate ([More info](https://datatracker.ietf.org/doc/html/rfc6749#section-2.1) about client types and client authentication from the OAuth2.0 spec). 

If you want to proceed with not using a client secret/ certificate, although not recommended, you can instead use PublicClientApplication in your client code and register the application as a public client client application in the portal, even if your application is a web app. You can do this by going to "Authentication" -> "Add a platform" -> "Mobile and desktop applications". If you do this you should stop getting "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'"

**Comment by 701chang** [comment]
I will see if the customer can configure this way and see if this works. Thanks for the quick response!
