### ISSUE TITLE
Threads collisions found under high concurrency

### ISSUE THREAD

**Issue by javieu** [AzureAD/microsoft-authentication-library-for-java#418]
Hello. This is basically a question since we lack the required information to open a real issue, but we want to share some events that we have experienced under production conditions.

We have basically included Azure ADFS login features using the library (1.10.0, we have not upgraded to 1.10.1), including in our application basically the approach found in the msal-java-webapp sample application that can be found here:

https://github.com/Azure-Samples/ms-identity-java-webapp/tree/master/msal-java-webapp-sample/src/main/java/com/microsoft/azure/msalwebsample

Obviously with some minor modifications. 

With 4000 concurrent users, we found two issues related to thread collisions. Checking the logs, we found the same pattern:

* User X starts a login operation.
* In the same instant (< 5ms) user Y does the same.
* User X receives user Y token -> enters as Y.
* User Y logs in successfully as user Y.

We checked the logic that we used from msalwebsample. There is no such thing -or at least we were unable to find it- as a static variable in a class or something that is not thread safe. We are using the same AuthHelper object, and it is instantiated in every single login process, so there is no way to have a collision there:

```
String authority = "https://login.microsoftonline.com/" + tenant + "/";
authHelper = new AuthHelper(clientId, clientSecret, authority);
```

Could it be possible that this issue is caused by something that is not thread-safe inside the library? I found some old issue, but fixed in 0.6.0 version.

Thanks in advance. Best regards,

  Javier

**Comment by sangonzal** [comment]
Hi @javieu, could you share logs showing this issue? You can send them to sagonzal [at] microsoft.com

**Comment by sangonzal** [comment]
Closing since I never heard back. Feel free to reopen if you have any other questions.
