### ISSUE TITLE
Updates to regional support

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-java#423]
According to email from Bogdan - 

1.	On the public cloud, the regional authority was “region.login.microsoft.com”. However, due to DNS issues, we must go back to “microsoftonline.com”. The authority will be “region.r.login.microsoftonline.com”. 
2.	On sovereign, the rule remains “region.sovereign_authority” but try to use the preferred authority value, as hardcoded in MSAL (i.e. don’t do instance discovery just for this)
3.	Avoid doing instance discovery when regional is used and the authority is known (hardcoded) to MSAL.

**Comment by Avery-Dunn** [comment]
This was addressed in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/504, and should be fixed as of the recent [1.12.0 release](https://search.maven.org/artifact/com.microsoft.azure/msal4j/1.12.0/jar).

If anyone is still running into issues with regions or if there are any related issues feel free to re-open this thread or open a new one.
