### ISSUE TITLE
Expose IdToken

### ISSUE THREAD

**Issue by maltalex** [AzureAD/microsoft-authentication-library-for-java#425]
Would it be possible to make `com.microsoft.aad.msal4j.IdToken` public and have `com.microsoft.aad.msal4j.IAuthenticationResult` be able to return a **parsed** token object?

The code already exists in `AuthenticationResult`, but isn't exposed, creating unnecessary work.

**Comment by SomkaPe** [comment]
Hi @maltalex, ITenantProfile from IAuthenticationResult contains all claims from idToken in the form of key-value pairs,  do you consider exposed IdToken (contains only standard claims) easier to use compared to all claims in ITenantProfile?

**Comment by maltalex** [comment]
Hi @SomkaPe

I haven't realized that `ITenantProfile` contains the fields from the `id_token`. Thanks!

But I think that somewhat highlights the problem - keeping the `id_token` values in a generic map makes the API less discoverable.

I think it would be more convenient to expose an object so developers will be able to explore the API in the IDE rather than looking up the documentation at every step. Or at least add some actual documentation to the `tenantProfile` field beyond the laconic `tenant profile` javadoc and add an enum of `id_token` field names to make looking through the map easier.

**Comment by bgavrilMS** [comment]
Not planning to revisit this API at this time.
