### ISSUE TITLE
Msal4j uses variable range of net.minidev:json-smart that causes dependency resolution issues.

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#428]
Hello, 

The Msal4j utlizies net.minidev:json-smart:[1.3.3,2.4.7] dependency via oauth2-oidc-sdk:9.7 as a variable range.
This tends to cause dependency resolution issues in users application.

This dependency should be pinned to its latest version in the Msal library or at Oauth2-Oidc-sdk..

**Comment by joshfree** [comment]
related https://github.com/Azure/azure-sdk-for-java/issues/23373, https://github.com/Azure/azure-sdk-for-java/issues/22807, and https://github.com/Azure/azure-sdk-for-java/issues/14907 (all same customer)

**Comment by sangonzal** [comment]
@g2vinay @joshfree I have opened an issue on oauth2-oidc-sdk:9.7 asking if they can pin net.minidev:json-smart to a specific version: https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/370/variable-range-of-netminidev-json-smart

If this is not something that can be done in oauth2-oidc-sdk, then well look at doing in MSAL.

**Comment by joshfree** [comment]
Thanks @sangonzal, we appreciate it

**Comment by JonathanGiles** [comment]
It seems that this was not picked up by the oauth2-oidc-sdk team - could we now consider pinning the version in msal4j?

**Comment by sangonzal** [comment]
@Avery-Dunn @SomkaPe FYI

**Comment by chenrujun** [comment]
Hi, @sangonzal 

FYI: You can use this way to avoid bring version range to your customer in your side:
https://github.com/Azure/azure-sdk-for-java/pull/27453

**Comment by siddhijain** [comment]
@g2vinay @JonathanGiles @joshfree msal java now uses version 9.32 of oauth2-oidc-sdk that does not specify net.minidev:json-smart dependency as a variable range.
Can this issue be closed now?

**Comment by JonathanGiles** [comment]
Unless I'm misunderstanding, there still exists a version range: https://mvnrepository.com/artifact/com.nimbusds/oauth2-oidc-sdk/9.32

**Comment by siddhijain** [comment]
Thanks @JonathanGiles. I misread (or mis-interpreted) that the issue got resolved after 9.27 version of oauth2-oidc-sdk.  Will fix this long overdue issue soon.

**Comment by JonathanGiles** [comment]
Thanks! @g2vinay we can update azure-identity now?

**Comment by Avery-Dunn** [comment]
@JonathanGiles @g2vinay We've released [version 1.12.0](https://search.maven.org/artifact/com.microsoft.azure/msal4j/1.12.0/jar) with the updated dependencies, so you should now be able to update to version 1.12 of MSAL Java to get the fixes.
