### ISSUE TITLE
Authority validation differ between app building and parameter

### ISSUE THREAD

**Issue by danilowitsch** [AzureAD/microsoft-authentication-library-for-java#429]
If you create a publc application and add the authority url: https://login.microsoftonline.com/<my-tenant-id> without a trailing slash the api will add the missing slash.

If you create an SilentParamater instance for a SilentRequest you are also able to add the authorityUrl. In this case the url will not check for a missing trailing slash and the parsing within the SilentRequest constructor fails with an IndexOutOfBound Exception.

> 
    PublicClientApplication pca = PublicClientApplication.builder(config.getClientId())
        .authority(config.getAuthority())
        .build();

    SilentParameters.builder(Collections.singleton("User.Read"))
        .authorityUrl(config.getAuthority())
        .build();

**Comment by Avery-Dunn** [comment]
@danilowitsch : Thanks for bringing this to our attention. I'm able to reproduce it and it definitely seems like a bug, so we should have a fix for that trailing slash problem in our next release.

**Comment by danilowitsch** [comment]
Nice.

**Comment by danilowitsch** [comment]
Sorry, my intention was only to comment this.

**Comment by Avery-Dunn** [comment]
Sorry for the long delay on this, but for anyone having this issue it was addressed as part of https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/431, and should be fixed as of the recent [1.12.0 release](https://search.maven.org/artifact/com.microsoft.azure/msal4j/1.12.0/jar).
