### ISSUE TITLE
Two step device code flow

### ISSUE THREAD

**Issue by neerajwadhwa-lcci** [AzureAD/microsoft-authentication-library-for-java#434]
Hi Team, is there a plan to add a two step device code flow? In step-1, we get the device code and in the step-2, we get the token using the device code received from the step-1, this way, the device code flow can be used in a more complicated scenarios where performing both the steps/tasks at once is not doable/desirable.

**Comment by sangonzal** [comment]
Hi @neerajwadhwa-lcci, there is no plan to expose the two different steps device code flow. What are the scenarios where having MSAL perform both steps is undesirable?

**Comment by neerajwadhwa-lcci** [comment]
Hi @sangonzal, because of security constraints, we can't perform ROPC on the server (this server is not built by us, pretty limited in terms of options available for OAuth). We have a method/functionality on the server that can be used to display the device code on the web portal so that the user can perform device code flow and we get the token but this doesn't work with default functionality provided by the MSAL lib, the device code can only be shown to the end user when this method/functionality to display something dynamic on the web portal is completely executed which means I won't be able to get the token by using that device code as there's nothing left to execute (this is a restriction from the server and the flow that it allows).

**Comment by sangonzal** [comment]
Closing, feel free to reopen in case of any follow up questions.
