### ISSUE TITLE
[FEATURE REQ] Expose refresh token / Support consuming refresh token in MSAL clients.

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#436]
Hi, 

We've a user request to support consuming user's refresh token and also allow users to read the refresh token.
I wanted to know what are MSAL's plans around supporting this feature.

Refrencing the original issue here: https://github.com/Azure/azure-sdk-for-java/issues/21104

**Comment by levimllr** [comment]
Ditto this request. Is there a reason why refresh tokens aren't exposed currently in the library? I need to be able to read both access and refresh tokens so I can persist them (encrypted, of course) on disk. I can't depend on this library's current in-memory management of refresh tokens.

**Comment by bgavrilMS** [comment]
MSAL libraries do not expose refresh tokens. The APIs are crafted in such a way that RT usage is handled by MSAL, without the app developer knowing. For example `AcquireTokenSilent` will look for a valid AT and if not found, it will refresh using the RT. 

If you have a specific scenario where RT is needed, please let us know and we can advise.
