### ISSUE TITLE
client assertion does not work when its issuer and subject don't match

### ISSUE THREAD

**Issue by chewong** [AzureAD/microsoft-authentication-library-for-java#437]
```java
public Mono<AccessToken> getToken(TokenRequestContext request)  {
    Map<String, String> env = System.getenv();
    String clientAssertion = "<jwt>";

    IClientCredential credential = ClientCredentialFactory.createFromClientAssertion(clientAssertion);
    String authority = "...";
    try {
        ConfidentialClientApplication app = ConfidentialClientApplication.builder(env.get("AZURE_CLIENT_ID"), credential).authority(authority).build();

        Set<String> scopes = new HashSet<>();
        for (String scope : request.getScopes()) scopes.add(scope);

        ClientCredentialParameters parameters = ClientCredentialParameters.builder(scopes).build();
        IAuthenticationResult result = app.acquireToken(parameters).join();
        return Mono.just(new AccessToken(result.accessToken(), result.expiresOnDate().toInstant().atOffset(ZoneOffset.UTC)));
    } catch (Exception e) {
        System.out.printf("Error creating client application: %s", e.getMessage());
        System.exit(1);
    }

    return Mono.empty();
}
```

I got the following error:

```
Error creating client application: com.nimbusds.oauth2.sdk.ParseException: Issuer and subject in client JWT assertion must designate the same client identifier
```

I have used msal-python, msal-go, msal-net, msal-node, and they all do not require client assertion's issuer and subject to be the same.

**Comment by Avery-Dunn** [comment]
Hello @chewong : Sorry for the delayed response. That error message is coming from a package we use, [com.nimbusds.oauth2.sdk](https://www.javadoc.io/doc/com.nimbusds/oauth2-oidc-sdk/latest/src-html/com/nimbusds/oauth2/sdk/auth/JWTAuthentication.html), which implements the OAuth2 spec and we use it for most of this kind of JWT parsing. 

I took a quick look through the JWT client spec and it doesn't say that they need to match so I'm not sure why the dependency is checking it, and confirmed with at least the MSAL .NET folks that they library allows it like you said. We'll work on a way to get around that check, unfortunately it's a thing that some other part of the dependency calls so we may need to replace more than just this. I'll update this thread once we have the fix.

**Comment by siddhijain** [comment]
@chewong Latest version of MSAL(1.11.1) is now released that contains fix of this issue.

**Comment by vdzhuvinov** [comment]
FYI v9.42 of the Nimbus OAuth / OIDC SDK got a fix to support iss != sub:

https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/393/allow-issuer-and-subject-in-client-jwt

**Comment by siddhijain** [comment]
Thanks for letting us know @vdzhuvinov !
