### ISSUE TITLE
Enum com.microsoft.aad.msal4j.Prompt lacks a "none" option

### ISSUE THREAD

**Issue by mkropf** [AzureAD/microsoft-authentication-library-for-java#438]
I am missing the option "none" in the enum com.microsoft.aad.msal4j.Prompt, I would like to use it in AuthorizationRequestUrlParameters to request a silent login

**Comment by Avery-Dunn** [comment]
Hello @mkropf : Could you describe your use case a bit? Typically, if you want to send a silent request you should make a silent flow call with `acquireTokenSilently`, and if that fails fall back to some interactive flow. 

However, the silent flow only works if you already have a token to return/refresh, but if I understand it right you want to send 'none' to try to do that first interactive call without user interaction?

**Comment by mkropf** [comment]
Hi @Avery-Dunn, you guessed it, I would like to make use of the "keep me signed in" options of MS login. The plan is, my server redirects the client to login with prompt "none" first and only if that fails it redirects the client to login with "select_account"

**Comment by mkropf** [comment]
after all, "none" is a valid prompt option in MS identity platform so I would expect it in the enum type too

**Comment by Avery-Dunn** [comment]
Sorry for the delay on this, but for anyone who needs the 'none' prompt it was addressed in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/504, and was added as part of the recent [1.12.0 release](https://search.maven.org/artifact/com.microsoft.azure/msal4j/1.12.0/jar).
