### ISSUE TITLE
Upgrade Jackson-Databind and SLF4j Dependency 

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#442]
We need to have Msal4j upgrade the com.fasterxml.jackson.core:jackson-databind dependency to 2.12.5
and org.slf4j:slf4j-api to 1.7.32

Upgrading these dependencies will align them with azure-core and help end users to avoid runtime dependency conflicts issues such as NoSuchMethodError, ClassNotFoundException etc.

**Comment by g2vinay** [comment]
@Avery-Dunn 
What's the ETA for this update to be released ?
The change is straight forward, just need to update the dependency mentioned to the specified versions.

**Comment by Avery-Dunn** [comment]
Sorry for the delay, but this issue was addressed in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/502, and should be fixed as of the recent [1.12.0 release](https://search.maven.org/artifact/com.microsoft.azure/msal4j/1.12.0/jar).
