### ISSUE TITLE
Interactive Browser Auth not working on Mac OS

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#447]
**Describe the bug**
When trying to authenticate with Azure via Interactive Browser from a Java/Sprint application, the following error is thrown:
```
Caused by: com.microsoft.aad.msal4j.MsalClientException: Unable to open default system browser
        at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.openDefaultSystemBrowser(AcquireTokenByInteractiveFlowSupplier.java:116)
...
```
And the application halts.

**To Reproduce**
* This was ran many times in OSX with the default browser (in the OS) set to Safari, Chrome or Edge.

***Code Snippet***
```java
        String tenantId = "<Tenant-Id>";
        String clientId = "<Client-Id>";

        String authHostUrl = "https://login.microsoftonline.com/" + tenantId;
        PublicClientApplication publicClientApplication = PublicClientApplication
                .builder(clientId).authority(authHostUrl)
                .build();

        List<String> scopes = new ArrayList<>(1);
        scopes.add("https://vault.azure.net/.default");
        InteractiveRequestParameters parameters =
                InteractiveRequestParameters.builder(URI.create("http://localhost:8080/"))
                        .scopes(new HashSet<>(scopes))
                        .prompt(Prompt.SELECT_ACCOUNT)
                        .build();

        String accessToken = publicClientApplication.acquireToken(parameters).get().accessToken();

```

**Expected behavior**
For my Java application to be able to use the default/any browser to construct a usable `PublicClientApplication` so that I can interactively authenticate.

**Setup (please complete the following information):**
 - OS: OSX Big Sur
 - msal4j:1.11.0 

Referencing original issue: https://github.com/Azure/azure-sdk-for-java/issues/21166

**Comment by bgavrilMS** [comment]
We should fix these bugs. Browser-based auth is important. 

The logic for opening the browser on Windows Mac and Linxu is here: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/5effd6c27477b5ffd22aac502420f13d06eec2ac/src/client/Microsoft.Identity.Client/Platforms/netcore/NetCorePlatformProxy.cs#L148

**Comment by siddhijain** [comment]
This issue is fixed and will be available to test in the next release.

**Comment by Avery-Dunn** [comment]
Fixed as part of https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/651, which was in the 1.13.9 release a couple months ago.
