### ISSUE TITLE
Integrated Windows Authentication fails when app's jar does not have Implementation-Version: 2.0 in the manifest

### ISSUE THREAD

**Issue by Eugene-Roslikov-BQ** [AzureAD/microsoft-authentication-library-for-java#448]
Integrated Windows Authentication fails when app's jar does not have Implementation-Version:  in the manifest, or it is lover than 2.0
root cause of that is 
[getProductVersion() in HttpHeader ](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/main/java/com/microsoft/aad/msal4j/HttpHeaders.java)

**Comment by bgavrilMS** [comment]
I believe this issue was fixed. Please reopen is needed.
