### ISSUE TITLE
Protect Azure Function using MSAL for JAVA

### ISSUE THREAD

**Issue by jdavilap** [AzureAD/microsoft-authentication-library-for-java#450]
Hi, I want to protect my azure function using MSAL for JAVA. How can i do that ? Can you give some example, or link to read documentaction about this.

Thank you.

**Comment by siddhijain** [comment]
Hey @jdavilap, Here are some of the links that can help you get started - 
https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-overview
https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code

**Comment by siddhijain** [comment]
@jdavilap Let us know if you were able to protect your azure function using MSAL Java or if you need any help.

**Comment by siddhijain** [comment]
Closing since no response. Please reopen this or open a new one if you need more information.
