### ISSUE TITLE
Add WAM Support to MSAL for Java, for cross-language consistency

### ISSUE THREAD

**Issue by joshfree** [AzureAD/microsoft-authentication-library-for-java#455]
Today WAM support is only in MSAL for .NET. In order to support WAM in Azure Identity Client Library and meet Azure SDK Design Guidelines (of maintaining feature parity across languages), the support for WAM must exist in all Tier-1 languages (C#, Java, JS, Python) for Azure Identity SDK to GA the support at its layer of the stack.

This GitHub issue tracks the ask for adding WAM support to MSAL in Java, JS, Python, and in Go. I'll file GitHub issues in each respective repo.

Related: AzureAD/microsoft-authentication-library-for-dotnet#643
Related: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam
Related: Azure/azure-sdk#3724

/cc @dingmeng-xue @scottaddie @schaabs @billwert @g2vinay

## Related MSAL Feature Request Issues

MSAL for Python: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/451
MSAL for JS: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4346
MSAL for Java: https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/455
MSAL for Go: https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/284

**Comment by siddhijain** [comment]
Discussed in team meeting on 2/8 - This is waiting on Middle tier work to be finished.

**Comment by siddhijain** [comment]
WAM Integration work can be done now. We will have to wait for AT Pop work to finish.

**Comment by siddhijain** [comment]
Closing this issue since we released a beta version of this integration.
