### ISSUE TITLE
verify signature failed

### ISSUE THREAD

**Issue by lwc-Arnold** [AzureAD/microsoft-authentication-library-for-java#464]
i have get a accessToken from my tenant web application, and i also check it format at[jwt.io/].
now i want to verify the third part of the jwt, the sign, i knew is the sha256withRSA. i verify it by two jwt SDK tool. the [nimbus-jose-jwt] same as you demo dependency,  the [org.bitbucket.b_c / jose4j], all failed. 
yes i get the right public key form[https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration], and select the one by same kid.
pls help. my phone: 18510172128

**Comment by Avery-Dunn** [comment]
Hello @lwc-Arnold : Could you explain your scenario and error a bit more? 

You're using our library to get tokens and that all works, but when separately trying to verify the signature of those tokens you're getting an error? If so, could you paste the exact error you're getting (with the stack trace if you have it)?

**Comment by lwc-Arnold** [comment]
//this is MS RSA publickey            
String jsonWebKeySetJson = "{\"keys\":[{\"kty\":\"RSA\",\"use\":\"sig\",\"kid\":\"Mr5-AUibfBii7Nd1jBebaxboXW0\",\"x5t\":\"Mr5-AUibfBii7Nd1jBebaxboXW0\",\"n\":\"yr3v1uETrFfT17zvOiy01w8nO-1t67cmiZLZxq2ISDdte9dw-IxCR7lPV2wezczIRgcWmYgFnsk2j6m10H4tKzcqZM0JJ_NigY29pFimxlL7_qXMB1PorFJdlAKvp5SgjSTwLrXjkr1AqWwbpzG2yZUNN3GE8GvmTeo4yweQbNCd-yO_Zpozx0J34wHBEMuaw-ZfCUk7mdKKsg-EcE4Zv0Xgl9wP2MpKPx0V8gLazxe6UQ9ShzNuruSOncpLYJN_oQ4aKf5ptOp1rsfDY2IK9frtmRTKOdQ-MEmSdjGL_88IQcvCs7jqVz53XKoXRlXB8tMIGOcg-ICer6yxe2itIQ\",\"e\":\"AQAB\",\"x5c\":[\"MIIDBTCCAe2gAwIBAgIQff8yrFO3CINPHUTT76tUsTANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4XDTIxMTAyNDE3NDU1NloXDTI2MTAyNDE3NDU1NlowLTErMCkGA1UEAxMiYWNjb3VudHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMq979bhE6xX09e87zostNcPJzvtbeu3JomS2catiEg3bXvXcPiMQke5T1dsHs3MyEYHFpmIBZ7JNo+ptdB+LSs3KmTNCSfzYoGNvaRYpsZS+/6lzAdT6KxSXZQCr6eUoI0k8C6145K9QKlsG6cxtsmVDTdxhPBr5k3qOMsHkGzQnfsjv2aaM8dCd+MBwRDLmsPmXwlJO5nSirIPhHBOGb9F4JfcD9jKSj8dFfIC2s8XulEPUoczbq7kjp3KS2CTf6EOGin+abTqda7Hw2NiCvX67ZkUyjnUPjBJknYxi//PCEHLwrO46lc+d1yqF0ZVwfLTCBjnIPiAnq+ssXtorSECAwEAAaMhMB8wHQYDVR0OBBYEFDiZG6s5d9RvorpqbVdS2/MD8ZKhMA0GCSqGSIb3DQEBCwUAA4IBAQAQAPuqqKj2AgfC9ayx+qUu0vjzKYdZ6T+3ssJDOGwB1cLMXMTUVgFwj8bsX1ahDUJdzKpWtNj7bno+Ug85IyU7k89U0Ygr55zWU5h4wnnRrCu9QKvudUPnbiXoVuHPwcK8w1fdXZQB5Qq/kKzhNGY57cG1bwj3R/aIdCp+BjgFppOKjJpK7FKS8G2v70eIiCLMapK9lLEeQOxIvzctTsXy9EZ7wtaIiYky4ZSituphToJUkakHaQ6evbn82lTg6WZz1tmSmYnPqRdAff7aiQ1Sw9HpuzlZY/piTVqvd6AfKZqyxu/FhENE0Odv/0hlHzI15jKQWL1Ljc0Nm3y1skut\"],\"issuer\":\"https://login.microsoftonline.com/{tenantid}/v2.0\"}]}";

            // The complete JWS representation, or compact serialization, is string consisting of
            // three dot ('.') separated base64url-encoded parts in the form Header.Payload.Signature

            String compactSerialization = "eyJ0eXAiOiJKV1QiLCJub25jZSI6IkFmWmpoU1JXdmxQMXJ5XzNMVGRxeXJoMGU5WHVpeHZCSEpySm5lOURKdVUiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1yNS1BVWliZkJpaTdOZDFqQmViYXhib1hXMCIsImtpZCI6Ik1yNS1BVWliZkJpaTdOZDFqQmViYXhib1hXMCJ9.eyJhd******ODJ9.cdXVQizm2I6KibBPAlt28i8QvYYNKo8aK-PCX3lSE8O6CLTmkNkZEJjr5CGR*****_-7Q79d2Wtw";
                    // Create a new JsonWebSignature object
            JsonWebSignature jws = new JsonWebSignature();

            // Set the algorithm constraints based on what is agreed upon or expected from the sender
//        jws.setAlgorithmConstraints(new AlgorithmConstraints(org.jose4j.jwa.AlgorithmConstraints.ConstraintType.PERMIT,   AlgorithmIdentifiers.ECDSA_USING_P256_CURVE_AND_SHA256));
            jws.setAlgorithmConstraints(new AlgorithmConstraints(AlgorithmConstraints.ConstraintType.PERMIT, AlgorithmIdentifiers.RSA_USING_SHA256));

            // Set the compact serialization on the JWS
            jws.setCompactSerialization(compactSerialization);

            // Create a new JsonWebKeySet object with the JWK Set JSON
            JsonWebKeySet jsonWebKeySet = new JsonWebKeySet(jsonWebKeySetJson);


            VerificationJwkSelector jwkSelector = new VerificationJwkSelector();
            JsonWebKey jwk = jwkSelector.select(jws, jsonWebKeySet.getJsonWebKeys());
            // The verification key on the JWS is the public key from the JWK we pulled from the JWK Set.
            jws.setKey(jwk.getKey());

            // Check the signature
            boolean signatureVerified = jws.verifySignature();

            // Do something useful with the result of signature verification
            System.out.println("JWS Signature is valid: " + signatureVerified);

signatureVerified  is  false.

**Comment by Avery-Dunn** [comment]
@lwc-Arnold : It looks like all of the code you posted was copied from [here](https://github.com/felx/jose4j/blob/master/src/test/java/org/jose4j/examples/ExamplesTest.java), in a library called "jose.4.j". I'm not sure what that dependency has to do with our library here (MSAL Java) since we mainly use [Nimbus JOSE+JWT](https://mvnrepository.com/artifact/com.nimbusds/nimbus-jose-jwt) for our token stuff. 

You mentioned that you tried using two tools to verify the signature of a token, one of which is the same as our "demo dependency". Which demo were you looking at? Also, could you describe how you set up your app registration or Azure AD stuff? Did you follow one of our samples or was it something you had already set up?

**Comment by lwc-Arnold** [comment]
the demo is here【https://github.com/AzureAD/microsoft-authentication-library-for-java/tree/dev/src/samples/msal-web-sample】。

**Comment by lwc-Arnold** [comment]
another question,  i have update the tenant config json, set [accessTokenAcceptedVersion] =2, but i still get the token in version1.

**Comment by lwc-Arnold** [comment]
import com.nimbusds.jose.JWSVerifier;
import com.nimbusds.jose.crypto.RSASSAVerifier;
import com.nimbusds.jose.jwk.KeyUse;
import com.nimbusds.jose.jwk.RSAKey;
import com.nimbusds.jose.util.Base64URL;
import com.nimbusds.jwt.SignedJWT;

public class NimbusJwt {

//https://connect2id.com/products/nimbus-jose-jwt/examples/jwt-with-rsa-signature
//JWSVerifier verifier = new RSASSAVerifier(rsaPublicJWK);
//assertTrue(signedJWT.verify(verifier));

    public static void main(String[] args) throws Exception{
        String tokenStr = "eyJ0eXAiOiJKV1QiLCJub25jZSI6IldUVlF1YmlzN2hvNkpiU2lsU2RiTTlSSHJ0RFpFSFU2ZXdlSFJZQzZlRHMiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1yNS1BVWliZkJpaTdOZDFqQmViYXhib1hXMCIsImtpZCI6Ik1yNS1BVWliZkJpaTdOZDFqQmViYXhib1hXMCJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83NGYxYjAwMC0zMzdmLTRkNGUtOWMwOS01YTg4NGIzY2FhNDYvIiwiaWF0IjoxNjQ1NDEyODkxLCJuYmYiOjE2NDU0MTI4OTEsImV4cCI6MTY0NTQxNzAxMCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFTUUEyLzhUQUFBQWxZRG9JTGV4TTRFMjdyUS9KdnpSYlMraks2WE40SVZBRXNGK0cyS3krdEk9IiwiYW1yIjpbInB3ZCJdLCJhcHBfZGlzcGxheW5hbWUiOiJTSC1JRE0xIiwiYXBwaWQiOiI4NjczMDA2Mi03NDQ0LTQwMWUtYmNjYS1iMGU5Yzg1YWNjNTYiLCJhcHBpZGFjciI6IjEiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxMTQuMjQ3LjM0LjY2IiwibmFtZSI6ImlkbSIsIm9pZCI6IjM5YjQzZTE5LWFmODUtNGY2NS05NWNkLTM4MGEwZGQ5M2E0YyIsInBsYXRmIjoiNSIsInB1aWQiOiIxMDAzMjAwMUMzQzVBOTE1IiwicmgiOiIwLkFYRUFBTER4ZEg4elRrMmNDVnFJU3p5cVJnTUFBQUFBQUFBQXdBQUFBQUFBQUFDSEFNWS4iLCJzY3AiOiJvcGVuaWQgcHJvZmlsZSBVc2VyLlJlYWQgZW1haWwiLCJzdWIiOiI4WTc4ckxXbHJDbEt4N3J4STdnYjMyOTVvNGFPbjEta0NVQUdIRi1qRXVzIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkFTIiwidGlkIjoiNzRmMWIwMDAtMzM3Zi00ZDRlLTljMDktNWE4ODRiM2NhYTQ2IiwidW5pcXVlX25hbWUiOiJpZG1ANjE0MDgwNTY3cXEub25taWNyb3NvZnQuY29tIiwidXBuIjoiaWRtQDYxNDA4MDU2N3FxLm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6ImZSN01OZE0ycmtDQlo0R2tONE1CQVEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfc3QiOnsic3ViIjoiZ3dkVy1xYVVCMU5yV1dOSlYtWGdTZTd3VV9rbG1TSGhDdi1YUDE0QTIzOCJ9LCJ4bXNfdGNkdCI6MTYzOTk5NTQ4Mn0.LCkn73bPiqI_1nteyf-DSVId_NVuN5jOKJaRYqb49sTz_dEUcvHdB8aD6W00OwiKEci4l0NyDk85NvWLin29lJX3B0GNIxbhhsex5QRLzEvaxMSWTVd9RVj4dAxjKXaoXpjIepuGXsIPkwChbGnYcTsKmwtGsYcAkmdhdk-XAkvQtXE638ulho8xhSXegxtbiF4_3riKgC-Y0df94ZJpiDBNmINhFKLbARw2pkEoeGBACvfB2LKJctJyyzaoHxiK7fMnyCv5jGaVKHOfB0BD8X0JT0V6SuJ6eG3tQLYMk3crvgN-SM_RtYkkGVLDl7MHlxgGJmG9KKPHyj0HLsHmyA";


        Base64URL n = new Base64URL("yr3v1uETrFfT17zvOiy01w8nO-1t67cmiZLZxq2ISDdte9dw-IxCR7lPV2wezczIRgcWmYgFnsk2j6m10H4tKzcqZM0JJ_NigY29pFimxlL7_qXMB1PorFJdlAKvp5SgjSTwLrXjkr1AqWwbpzG2yZUNN3GE8GvmTeo4yweQbNCd-yO_Zpozx0J34wHBEMuaw-ZfCUk7mdKKsg-EcE4Zv0Xgl9wP2MpKPx0V8gLazxe6UQ9ShzNuruSOncpLYJN_oQ4aKf5ptOp1rsfDY2IK9frtmRTKOdQ-MEmSdjGL_88IQcvCs7jqVz53XKoXRlXB8tMIGOcg-ICer6yxe2itIQ");
        Base64URL e = new Base64URL("AQAB");
        String kid = "Mr5-AUibfBii7Nd1jBebaxboXW0";
         RSAKey key = new RSAKey.Builder(n, e)
            .keyUse(KeyUse.SIGNATURE)
            .keyID(kid)
            .build();

        JWSVerifier verifier = new RSASSAVerifier(key);
        SignedJWT signedJWT = SignedJWT.parse(tokenStr);
        System.out.println(signedJWT.verify(verifier));
    }
}

the code  signedJWT.verify(verifier) return false, i expect ture。
no exception and error in you sdk.
you demo do not verify the token sign.

**Comment by Avery-Dunn** [comment]
As I said a couple times now, could you post the actual error/stack trace? And if you're using our demo to produce these tokens like you mentioned earlier, did you change anything or do anything more than the instructions said? In my own tests I could get tokens with valid signatures.

If the exception isn't happening in our library then I'm not sure how much we can help, you should try getting support from the dependencies that are producing the error if you haven't already asked them.

**Comment by lwc-Arnold** [comment]
thank u so much  
sorry to trouble you,  NO ERROR or EXCEPTION in your library,  NO ERROR or EXCEPTION in your demo. 
i can get token by login, the token  has sign, format is ok. demo runs well.
i just want to do a little more, just validate the token is produced by MicroSoft, by validate the token sign.
i has trouble in validate token sign. i tried two sdk, all failed. can u give me some advice? thank u so much  again.

**Comment by Avery-Dunn** [comment]
So, after asking around and finding some folks who know more about how these access tokens are made, it's my understanding that access tokens simply don't have signatures that can be validated using normal methods. In this case, the token service put a 'nonce' value in the header (which you can see in your token), and I think that is used in some way to encrypt or otherwise change the token signature in a way that MS Graph can verify, but you can't since you generally aren't expected to.

Basically, although access tokens look like a JWT and generally follows that standard format, some Microsoft resources may need non-standard things in access tokens which mess up this sort of validation. I believe ID tokens are more standard, so you should be able to verify them.

Check out this thread for some more details, it's from 2019 but I confirmed with some of the people in the thread that it's still more-or-less true today: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/609#issuecomment-524434987

**Comment by lwc-Arnold** [comment]
thanks for your information.
 now i understand, i decide not validate access token anymore.  thank you for your patience.

**Comment by lwc-Arnold** [comment]
i now understand should not validate access token, then, close.

**Comment by Avery-Dunn** [comment]
Happy to help, and if you have any other questions or issues feel free to open up a new thread to ask.
