### ISSUE TITLE
Valid Client Assertion Fails validation on MSAL Confidential client. Enforces that Subject value should equal issuer value.

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#467]
Where subject value should be equal to issuer value, but in the client assertion token it is not.

subject == "system:serviceaccount:default:pod-identity-sa"

issuer == "https://aramase.blob.core.windows.net/oidc-test/"

**Comment by siddhijain** [comment]
@g2vinay We just fixed this issue in the latest MSAL Release 1.11.1. Are you using the latest library? Can you elaborate on the issue?

**Comment by g2vinay** [comment]
@siddhijain, thanks for the update, I will try out the latest version and let you know.

**Comment by siddhijain** [comment]
@g2vinay We are working on a hot fix release to address an issue found in the last release. I will update you when it is ready to test.

**Comment by siddhijain** [comment]
Closing this issue since the work is done. Feel free to reopen this or open another one in case of any issues with this implementation.
