### ISSUE TITLE
MS graph Subscription (Change notification for users) and access token fetch using java

### ISSUE THREAD

**Issue by AnjanaCloud** [AzureAD/microsoft-authentication-library-for-java#475]
Hi . I am trying to implement msgraph subscription using java. I have the following code. I tried to acquire token like these: Am I using the right auth provider to fetch access token ?

                final TokenCredentialAuthProvider tokenCredentialAuthProvider = new TokenCredentialAuthProvider(SCOPE, (TokenCredential) authProvider);

                GraphServiceClient graphClient = GraphServiceClient
                        .builder()
                        .authenticationProvider(tokenCredentialAuthProvider)
                        .buildClient();

                Subscription subscription = new Subscription();
                subscription.changeType = "created";
                subscription.notificationUrl = ngrok + "/api/send/myNotifyClient";
                subscription.resource = "/users";
                subscription.expirationDateTime = OffsetDateTimeSerializer.deserialize("2016-11-20T18:23:45.9356913Z");
                subscription.clientState = "secretClientValue";
                //   subscription.latestSupportedTlsVersion = "v1_2";

                graphClient.subscriptions()
                        .buildRequest()
                        .post(subscription);

And building authProvider  goes like this: 
```

 ConfidentialClientApplication authProvider = ConfidentialClientApplication                                                                                                                    
                         .builder(CLIENT_ID, ClientCredentialFactory
                         .createFromSecret(CLIENT_SECRET))
                         .authority(AUTHORITY)
                         .build();


```

**Comment by Avery-Dunn** [comment]
Hello @AnjanaCloud : Just to clarify, are you getting some sort of error using this code or are you just looking for guidance/best practices for getting the tokens? Also, the `ConfidentialClientApplication` stuff is MSAL Java, but where is the code in the first part of your post coming from?

**Comment by AnjanaCloud** [comment]
Hi @Avery-Dunn I am trying to build a Java code fto implement notification(subscription) when user is added in AAD, using MSAL and MS Graph API.  I guess, I am not using the authprovider part in the right way. Glad if I get any kind of guidance over fetching token successfully. Thanks.
[MSGraph.txt](https://github.com/AzureAD/microsoft-authentication-library-for-java/files/8101467/MSGraph.txt)

**Comment by AnjanaCloud** [comment]
@Avery-Dunn  @PramodKumarHK89  I am able to fetch user data using Graph Client. My code to implement subscription is not getting succeeded. I think my issue is authprovider and notificationUrl.
Also , I am in confusion about how to give the POST call to "http://localhost:4200/1/mynotification" , how to handle the POST call.  Spent alot of time in it.  It will be a great help if someone can clear my doubts. Thanks in advance.
         
             
 ```
            try{

                final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                        .clientId(CLIENT_ID)
                        .clientSecret(CLIENT_SECRET)
                        .tenantId(TENANT)
                        .build();

                final GraphServiceClient graphClient =
                        GraphServiceClient
                                .builder()
                                .authenticationProvider(new IAuthenticationProvider() {
                                    @NotNull
                                    @Override
                                    public CompletableFuture<String> getAuthorizationTokenAsync(@NotNull URL url) {
                                        return null;
                                    }
                                })
                                .buildClient();

                Subscription subscription = new Subscription();
                subscription.changeType = "created";
                subscription.notificationUrl = "http://localhost:4200/1/mynotification";
                subscription.resource = "/users";
                subscription.expirationDateTime = OffsetDateTimeSerializer.deserialize("2022-03-20T18:23:45.9356913Z");
                subscription.clientState = "secretClientValue";
                //   subscription.latestSupportedTlsVersion = "v1_2";

                Subscription graphresult = graphClient.subscriptions()
                        .buildRequest()
                        .post(subscription);
            
                System.out.println("graphresult :"+graphresult );
            } catch (Exception e) {
                e.printStackTrace();
                logger.info("\nException : "+e);
            }

```

**Comment by Avery-Dunn** [comment]
It seems like that code is just using the [Microsoft Graph SDK for Java](https://github.com/microsoftgraph/msgraph-sdk-java)? Where is MSAL Java involved in your actual code, and code you post the actual error message and stack trace? 

If you have questions about configuring stuff in the MS Graph Java SDK, I'd recommend opening an issue in their Github repo instead: https://github.com/microsoftgraph/msgraph-sdk-java/issues

**Comment by AnjanaCloud** [comment]
```

graphClient.subscriptions()
                        .buildRequest()
                        .post(subscription);
```

```
[vert.x-worker-thread-29] 2022-02-23T04:08:12.514Z INFO User.java
graphClient - com.microsoft.graph.requests.GraphServiceClient@7ce460ee
subscription - com.microsoft.graph.models.Subscription@5eabe03c
Exception : com.microsoft.graph.core.ClientException: Error executing the request
```

**Comment by Avery-Dunn** [comment]
Again, this seems to be code and an error message in the [MS Graph Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java), and I'm not too familiar with that SDK or what could be going wrong here. 

Unless you think this issue is being caused by MSAL Java in some way, I'd recommend opening an issue in their repository, since they'll be able to help you more than we could.
