### ISSUE TITLE
Consistency track: please provide consistent APIs to disable authority validation and instance discovery

### ISSUE THREAD

**Issue by xiangyan99** [AzureAD/microsoft-authentication-library-for-java#481]
Now we have different API/behaviors for customers to disable authority validation and instance discovery.

Please sync across languages to provide consistent ones.

This is important because JEDI scenarios are blocked by current behavior.

**Comment by siddhijain** [comment]
This feature is in 'private preview now. Version 1.0.0-beta.1 contains the latest changes.

**Comment by siddhijain** [comment]
The feature is now released in v1.13.4. Closing the issue.
