### ISSUE TITLE
Ensure all public APIs have updated and thorough Javadoc comments

### ISSUE THREAD

**Issue by Avery-Dunn** [AzureAD/microsoft-authentication-library-for-java#518]
A number of classes and methods either have few Javadoc comments, or the existing comments are insufficient or outdated due to changes/additions to the library. 

These Javadocs are very useful for auto-generating documentation and helping developers understand the library, so we should clean up any outdated comments and ensure any public APIs have thorough comments explaining how to use each feature.

**Comment by siddhijain** [comment]
Moving this to the backlog as it is not a customer ask. https://identitydivision.visualstudio.com/Engineering/_boards/board/t/Auth%20Client%20-%20JAVA/Features/?showParents=true&workitem=2441654
