### ISSUE TITLE
MSAL fails to get token from the cache when authority URL includes port.

### ISSUE THREAD

**Issue by csigueros** [AzureAD/microsoft-authentication-library-for-java#529]
Observed in versions 1.12.0 and 1.13.0

Using ConfidentialClientApplication with authority value set to https://login.microsoftonline.com:443/<tenantid>/ the Access Token is obtained successfully and stored in the cache. 

Next request should use the same token, but it fails to find it from the cache so it sends a new request to obtain another token which replaces the first one in the cache. 

If I repeat the test without the port then everything works as expected. 

Maybe related with https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/409?

**Comment by siddhijain** [comment]
@csigueros That looks like a bug in our library. We will prioritize fixing this and will let you know once the fix is available.

**Comment by bgavrilMS** [comment]
@csigueros - is this still relevant? You should not need to specify port 443.

**Comment by csigueros** [comment]
Hi @bgavrilMS yes, we removed the port last year.
