### ISSUE TITLE
Polling Timeout for Login should be configurable

### ISSUE THREAD

**Issue by eginwong** [AzureAD/microsoft-authentication-library-for-java#532]
Hi! Looking at [msal.js](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/client/DeviceCodeClient.ts) and msal dotnet, I noticed that they have configurable timeouts for the user to login using the browser prompt. 

For our scenario, we are using Azure AD B2C. Including a first-time sign up, users can easily exceed the [hardcoded 120s timeout](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/main/java/com/microsoft/aad/msal4j/AcquireTokenByInteractiveFlowSupplier.java#L128) period. 

I will submit a PR to patch this by allowing a configurable timeout if the issue is acceptable.

**Comment by siddhijain** [comment]
Closing issue as the fix was released in version 1.13.1.
