### ISSUE TITLE
Update the Logging Level to VERBOSE (Msal Default) for Token Caching Callback API

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#542]
Currently, ERROR levels logs are logged for Exception in Token Caching Callback API,
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/5430778/191592872-09b3300f-b99e-4303-a3b6-c199db84b63a.png">

It is expected to follow the default logging level of VERBOSE as discussed with @siddhijain

**Comment by siddhijain** [comment]
This issue is fixed in Release v1.13.2. Closing the issue.
