### ISSUE TITLE
ArtifactId in README is wrong

### ISSUE THREAD

**Issue by Col-E** [AzureAD/microsoft-authentication-library-for-java#544]
From the readme:
```xml
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>com.microsoft.aad.msal4j</artifactId> <!--- Incorrect -->
    <version>1.13.1</version>
</dependency>
```

The artifact ID is just `msal4j` as seen: https://mvnrepository.com/artifact/com.microsoft.azure/msal4j

The hyperlink above the blob in the README ought to be updated as well.

**Comment by siddhijain** [comment]
Thanks for noticing. We will get this fixed.

**Comment by Col-E** [comment]
#545 is a partial fix, the hyperlink above the XML is still incorrect and leads to a 404.

**Comment by DidunAyodeji** [comment]
I have updated the hyperlink. Sorry about that.
