### ISSUE TITLE
Fix export in manifest

### ISSUE THREAD

**Issue by pieterjanpintens** [AzureAD/microsoft-authentication-library-for-java#572]
Your manifest file is incorrect, it contains the following:

`Export-Package: com.microsoft.aad.com.microsoft.aad.msal4j;version="1.13.3"`

This should be:

`Export-Package: com.microsoft.aad.msal4j;version="1.13.3"`

This makes your lib unusable in an OSGi environment unless we hack the manifest file.

https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/bnd.bnd
is incorrect

**Comment by siddhijain** [comment]
Thanks for finding this. We will update and include this in our next release.

**Comment by siddhijain** [comment]
This issue is fixed in the latest release. Please reopen this if the issue persists.
