### ISSUE TITLE
MSAL fails to get token from the cache using ConfidentialClientApplication

### ISSUE THREAD

**Issue by chakravarthi2u** [AzureAD/microsoft-authentication-library-for-java#575]
Dear msal4j-java Team,

I am using ConfidentialClientApplication with authority value set to [https://login.microsoftonline.com:/<tenantId>].
ConfidentialClientApplication app = ConfidentialClientApplication
                .builder(emailConfig.getEwsClientExternalId(), ClientCredentialFactory.createFromSecret(emailConfig.getEwsClientExternalSecret()))               
                .authority("https://login.microsoftonline.com/" + emailConfig.getEwsTenantId()).build();

I am following below example to acquireToken.
[ClientCredentialGrant.java](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/samples/confidential-client/ClientCredentialGrant.java)

I am using scope as: https://outlook.office365.com/.default

Next request should use the same token, but it fails to find it from the cache so it sends a new request to obtain another token which replaces the first one in the cache.

Any thoughts on this?

I am using msal4j 1.13.0

**Comment by siddhijain** [comment]
Thanks for reaching out, @chakravarthi2u. Are you building the app again for the second request? If you use the same app and call the acquireToken() method with the same scope, MSAL should retrieve the token from the cache. If you build the app again or call acquiretoken() with a different scope, MSAL will not find the token in the cache and will make a call to get a new token.

**Comment by chakravarthi2u** [comment]
> Thanks for reaching out, @chakravarthi2u. Are you building the app again for the second request? If you use the same app and call the acquireToken() method with the same scope, MSAL should retrieve the token from the cache. If you build the app again or call acquiretoken() with a different scope, MSAL will not find the token in the cache and will make a call to get a new token.

Hi @siddhijain 
Thanks for your help in this.
I am using same app and not building again. Just calling acquireToken() multiple times. Please see sample code below. 

I am accessing below method in my code to get accessToken for email functionality. 

Scope: https://outlook.office365.com/.default

![image](https://user-images.githubusercontent.com/3807556/206581259-f7046a02-cd0c-466a-b985-5a7514b4690c.png)

Except token and expirationDate, all other values i am getting as null after i put log messages.

I have enabled logging in msal4j and getting below messages confirms that caching not working for me.
![image](https://user-images.githubusercontent.com/3807556/206582403-dacfae92-2ae9-489c-8506-087c99d20df6.png)

**Comment by Avery-Dunn** [comment]
Hello @chakravarthi2u : In that `getAccessToken()` method, it looks like you're creating a new `ConfidentialClientApplication` called 'app'.

That 'app' object is what has the token cache that contains the tokens you get in the `acquireToken()` call. By creating a new `ConfidentialClientApplication` every time you call this method, you're also creating a new (blank) token cache, which is why later calls don't find the cached tokens. Our [ClientCredentialGrant.java](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/samples/confidential-client/ClientCredentialGrant.java) example you linked doesn't do a good job of explaining this, and we'll make the recommended pattern more clear in the future.

For now, just move the `ConfidentialClientApplication` creation outside of your `getAccessToken()` method and pass it in as a parameter. Once you do that, you should stop seeing those 'Cache lookup failed' messages and `getAccessToken()` should start returning the same tokens in multiple calls.

**Comment by chakravarthi2u** [comment]
> Hello @chakravarthi2u : In that `getAccessToken()` method, it looks like you're creating a new `ConfidentialClientApplication` called 'app'.
> 
> That 'app' object is what has the token cache that contains the tokens you get in the `acquireToken()` call. By creating a new `ConfidentialClientApplication` every time you call this method, you're also creating a new (blank) token cache, which is why later calls don't find the cached tokens. Our [ClientCredentialGrant.java](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/samples/confidential-client/ClientCredentialGrant.java) example you linked doesn't do a good job of explaining this, and we'll make the recommended pattern more clear in the future.
> 
> For now, just move the `ConfidentialClientApplication` creation outside of your `getAccessToken()` method and pass it in as a parameter. Once you do that, you should stop seeing those 'Cache lookup failed' messages and `getAccessToken()` should start returning the same tokens in multiple calls.

You guys are awesome. Thanks for quick reply. I tried above solution and its working perfectly fine.

Thanks a lot again.

**Comment by Avery-Dunn** [comment]
Happy to help, and if you run into any other issues feel free to ask.

**Comment by chakravarthi2u** [comment]
> Happy to help, and if you run into any other issues feel free to ask.

Thanks @Avery-Dunn.
