### ISSUE TITLE
Javadocs link points to error page

### ISSUE THREAD

**Issue by mrclmh** [AzureAD/microsoft-authentication-library-for-java#582]
The page displays an errror "Artifact com.microsoft.azure:com.microsoft.aad.msal4j does not exist.".

**Comment by siddhijain** [comment]
@marcelmore Can you please provide more details - which version of the library you are using and when you are getting this error?

**Comment by mrclmh** [comment]
The error page occurs when trying to open the link "Javadocs" (in the column "Reference Docs") in the [README.md](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/README.md)

**Comment by siddhijain** [comment]
Thanks for letting us know! It seems to be related to this https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/572. We are planning a release this week. I will test this after the release to see if it is resolved.

**Comment by siddhijain** [comment]
Please test in the latest version of msal4j 1.13.4 and reopen if the issue persists.
