### ISSUE TITLE
Our B2C Authority format doesn't match what's expected 

### ISSUE THREAD

**Issue by dsmith270** [AzureAD/microsoft-authentication-library-for-java#591]
Hi MSAL4J Team,

We're implementing B2C and the service URLs I'm provided with by our team don't work with MSAL4J. The format of the URLs is different:

https://sadoenswb2c.b2clogin.com/sadoenswb2c.onmicrosoft.com/b2c_1a_dta_single_abn_authentication/oauth2/v2.0/authorize

It's missing the expected "tfp". Is there a way to tell MSAL4J to allow a non-standard B2C Authority? I saw this is possible for Swift and Objective C in their doco, but I need to use java. 

I don't claim this is a bug, just looking for a solution as the source code doesn't seem to allow the Builder to take an Authority object directly. It parses the Authority URL, so only string input seems possible. Vis.:
```
 IClientSecret sec =   ClientCredentialFactory.createFromSecret(conf.getSecretKey());
 ConfidentialClientApplication app = ConfidentialClientApplication.builder(conf.getClientId(), sec)
        		.b2cAuthority(conf.getAuthorityString())
        		.build();
```

Thanks so much for any help or suggestions.

**Comment by siddhijain** [comment]
Thanks for reaching out @dsmith270. Unfortunately, currently msal java does not support a custom B2C Authority and it expects "tfp" in the URL format. We can work on fixing this. We will let you know once it is done.

**Comment by siddhijain** [comment]
@dsmith270 I just learned that you should be able to use the same URL by changing to "https://sadoenswb2c.b2clogin.com/tfp/sadoenswb2c.onmicrosoft.com/b2c_1a_dta_single_abn_authentication". Let me know if that resolves your issue.

**Comment by dsmith270** [comment]
Yes, thanks @siddhijain. It is a little counter-intuitive. I solved this with the help of a friend. If I input a URL constructed from the segments of host, tenant, and policy, and add in the tfp segment, the MSAL4J library will accept it and do the right thing. So the Authority string seems to be more of a spec than an actual URL. This not explained anywhere in the Microsoft Azure doco that I could find. 

Thanks so much - please close this, no enhancement needed.
