### ISSUE TITLE
[ESTSR] ConfidentialClientApplication.acquireToken took 20s to finish after specifying region

### ISSUE THREAD

**Issue by kentzhang** [AzureAD/microsoft-authentication-library-for-java#592]
I am using the msal4j 1.13.4 package in spark project, ConfidentialClientApplication.acquireToken works well without providing region. I have line by line log to record the time each method is taking: 
![image](https://user-images.githubusercontent.com/1408944/217352249-f1622662-7f55-4883-9d5a-0046eaa31474.png)
above log shows it finished in 1 second.

but after add region, all acquireToken is taking 20s to finish. got warning from AadInstanceDiscoveryProvider saying "Exception during call to local IMDS endpoint: java.net.SocketTimeoutException: connect timed out".
below is full log of get token call, acquireToken started from 18:39:27 future.join() finish at 18:39:47

23/02/07 18:39:27 INFO AadAuthByCertCallbackV2: acquireToken started - Tue Feb 07 18:39:27 UTC 2023, region - eastus, authority - https://login.microsoft.com/72f988bf-86f1-41af-91ab-2d7cd011db47, scope - https://eventhubs.azure.net/.default, 13.4
23/02/07 18:39:27 INFO AadAuthByCertCallbackV2: acquireToken started - Tue Feb 07 18:39:27 UTC 2023,  ConfidentialClientApplication build() 
23/02/07 18:39:27 INFO AadAuthByCertCallbackV2: acquireToken started - Tue Feb 07 18:39:27 UTC 2023,  ClientCredentialParameters build() 
23/02/07 18:39:27 INFO AadAuthByCertCallbackV2: acquireToken started - Tue Feb 07 18:39:27 UTC 2023,  acquireToken(parameters) 
23/02/07 18:39:37 WARN AadInstanceDiscoveryProvider [ForkJoinPool.commonPool-worker-1]: Exception during call to local IMDS endpoint: java.net.SocketTimeoutException: connect timed out
23/02/07 18:39:37 WARN AadInstanceDiscoveryProvider [ForkJoinPool.commonPool-worker-2]: Exception during call to local IMDS endpoint: java.net.SocketTimeoutException: connect timed out
23/02/07 18:39:47 WARN AadInstanceDiscoveryProvider [ForkJoinPool.commonPool-worker-1]: Exception during call to local IMDS endpoint: java.net.SocketTimeoutException: connect timed out
23/02/07 18:39:47 INFO AadAuthByCertCallbackV2: acquireToken started - Tue Feb 07 18:39:27 UTC 2023,  future.get() 
23/02/07 18:39:47 INFO AadAuthByCertCallbackV2: acquireToken started - Tue Feb 07 18:39:27 UTC 2023,  authResult.accessToken() 
23/02/07 18:39:47 INFO AadAuthByCertCallbackV2: got access token, starttime: Tue Feb 07 18:39:27 UTC 2023, env eastus.login.microsoft.com, token length 1512

source code for above log:
![image](https://user-images.githubusercontent.com/1408944/217356763-d07c684d-c113-40f0-bc30-c4152b7fe6fc.png)

do you know what might be the issue?

**Comment by Avery-Dunn** [comment]
Hello @kentzhang : Just to confirm some things: 
- Is your application running in an Azure VM or some other Azure service, or just on your own machine?
- Are you on any sort of corporate network that might block a call to that IMDS endpoint and cause a timeout?
- Have you made any successful calls to a regional endpoint, or have they all timed out?

My first thought is that if you aren't on an Azure VM, then the 'IMDS endpoint' call should fail immediately rather than time out (because that endpoint is unreachable from outside of Azure) and then proceed to use the region you set instead of the one from the IMDS endpoint. However, if there's some sort of firewall holding up the request, then it could be timing out before it knows it's unreachable.

**Comment by kentzhang** [comment]
Thanks for looking into this, our program is a spark job running on Azure HDInsight cluster node, let me check if there is any firewall or other traffic control mechanism in place.

**Comment by siddhijain** [comment]
We have released a fix for this issue in 1.13.5 version of msal4j. Please retest.

**Comment by siddhijain** [comment]
Closing the issue. Please reopen or open another one if the issue persists.
