### ISSUE TITLE
Add ability to provide id_token_hint to AuthorizationRequestUrlParameters via Builder

### ISSUE THREAD

**Issue by bpossolo** [AzureAD/microsoft-authentication-library-for-java#601]
I'm trying to implement a custom policy for passwordless authentication.

The policy expects the relying party to provide an `id_token_hint` with the authorization request to Azure B2C.

`com.microsoft.aad.msal4j.AuthorizationRequestUrlParameters.Builder` doesn't currently offer a way to add the `id_token_hint` to the `AuthorizationRequestUrlParameters`

[Official docs for id_token_hint in custom B2C policies](https://learn.microsoft.com/en-us/azure/active-directory-b2c/id-token-hint)

msal4j version: 1.13.4

**Comment by siddhijain** [comment]
Thanks for creating the PR. We are working on providing a different mechanism to support extra query parameters. I will update this thread once the implementation is available.

**Comment by siddhijain** [comment]
We added a map of ExtraQueryParameters that can be used to provide extra parameters in the request. This feature is available in version 1.13.6 of the library to take care of this. Please test and reopen this if the issue persists.

**Comment by bpossolo** [comment]
cool. thank you
