### ISSUE TITLE
Authorization for bot

### ISSUE THREAD

**Issue by prateek-narsinghani** [AzureAD/microsoft-authentication-library-for-java#604]
Hi team,
I need to build a bot that can send daily notifications to a channel for the organizations which have added the app.
For that, I need authorization for using Microsoft graph API. The problem is the authorization code is short-lived. What entity can be stored so that I don't need access from the user every time. 
I am not able to figure out how to get refresh tokens
Thanks in advance!

**Comment by Avery-Dunn** [comment]
Hello @prateek-narsinghani : MSAL Java maintains an in-memory cache for the tokens it acquires, and our [acquireTokenSilently](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AbstractClientApplicationBase.java#L148) method should handle retrieving these cached tokens and refreshing them for you.

[This page](https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=java) shows the recommended pattern for the interactive flow, but this pattern will apply to most flows:
 - Use [getAccounts](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AbstractClientApplicationBase.java#L178) to get all cached account objects, and filter based on the one you want
 - If the account is cached, set up a [silentParameters](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/SilentParameters.java) object and send it to the [acquireTokenSilently](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AbstractClientApplicationBase.java#L148) method
   - If there is a cached token for that account, the acquireTokenSilently method will return it. If the cached token expired, the library will refresh it and cache/return the valid token
   - If there isn't a cached token for that account, the acquireTokenSilently method will return an exception saying so, and you can then perform some other acquireToken method to get a new token for that user

However, there are a couple of scenarios (mainly the [on-behalf-of](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/ConfidentialClientApplication.java#L66) and [client credentials](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/ConfidentialClientApplication.java#L47) flows) which don't really deal with specific accounts. For these acquireToken calls, the library will attempt to find cached tokens automatically, and you do not need to do a separate acquireTokenSilently call.

**Comment by prateeknarsinghani** [comment]
@Avery-Dunn thanks for the quick reply. Is there any other way a bot can send message to teams app? Like a client authorizes a bot and then it can store a secret which then can be used to send message. 
I am not able to understand the flow, currently I was using Microsft Graph API to send [chatMessage](https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http) and using [authorization-code-provider](https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS#authorization-code-provider) which would require user to give authorization again and again.

Or if not how to make a graph client using the acquireTokenSilently method?

**Comment by Avery-Dunn** [comment]
Could you describe your scenario a bit more? When you say a "client authorizes", do you mean some individual user gives permission to a client-side app to send messages (using that user's tokens)? Or is more of a server-side app, set up with a set of credentials/some secret and sending messages on behalf of multiple users?

We support [a number of authorization flows](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows) and have repo full of samples showing the basics of each: https://github.com/Azure-Samples/ms-identity-msal-java-samples

Depending on exactly what you need, here are a couple that might be relevant: 
 - [Client credential](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#client-credentials) flow, where your application has its own set of credentials to get tokens for APIs like Graph rather than dealing with individual users
   - We have samples [using a secret](https://github.com/Azure-Samples/ms-identity-msal-java-samples/tree/main/1.%20Server-Side%20Scenarios/msal-client-credential-secret) and [using a certificate](https://github.com/Azure-Samples/ms-identity-msal-java-samples/tree/main/1.%20Server-Side%20Scenarios/msal-client-credential-certificate)
 - [On-behalf-of](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#on-behalf-of-obo) flow, where your users authenticate with a middleman API, and then that API makes calls to other APIs like Graph on behalf of your users
   - [Our OBO sample](https://github.com/Azure-Samples/ms-identity-msal-java-samples/tree/main/1.%20Server-Side%20Scenarios/msal-web-api-sample)
 - [Authorization code](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#authorization-code) flow, where an individual user's credentials are used to get an authorization code, which the library redeems for an access token that can be used to access APIs like Graph
   - [Our web app sample](https://github.com/Azure-Samples/ms-identity-msal-java-samples/tree/main/1.%20Server-Side%20Scenarios/msal-java-webapp-sample)

Regardless of the exact flow, our library should be returning access tokens in the AuthenticationResult object, caching those tokens in our in-memory cache, and automatically refreshing tokens when you call the acquireTokenSilently API

**Comment by prateek-narsinghani** [comment]
@Avery-Dunn Let me explain my scenario a bit: 
I am trying to create a teams app notification bot using Java Spring Boot. Different organizations can add it to their Teams app and then it can send some custom notifications to a channel within their org.
I have a developer account. 
What I have done till now is: 
1. Create a bot on the Developer portal and added permissions to it on the Azure portal according to [this](https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http).
2. Used the [authorize](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) graph API to get the authentication token.
3. Make graph client using TokenCredentialAuthProvider.
4. Use send chat message graph [API](https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http).
The problem with this flow is that auth-code and token are short-lived and I will need to get authorization every time from the organization's Teams admin. 

I wanted to know if I am on the right track or if there's a simpler way for bots.

**Comment by Avery-Dunn** [comment]
Have a look at our [client credential secret](https://github.com/Azure-Samples/ms-identity-msal-java-samples/tree/main/1.%20Server-Side%20Scenarios/msal-client-credential-secret) and [client credential certificate](https://github.com/Azure-Samples/ms-identity-msal-java-samples/tree/main/1.%20Server-Side%20Scenarios/msal-client-credential-certificate) samples (they're basically the same, they just use different credential types).

Those samples show how to get an access token, and uses the token to call MS Graph to get a list of users. Those samples don't show how to use the [acquireTokenSilent ](https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=java) method to get a cached token, but [the doc I linked earlie](https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=java)r should help show how to combine it with what the samples show.

Here's some pseudocode to give an idea of what your code will probably look like:
```java
//Get the accounts from MSAL Java's cache and filter in some way to get the correct user
Set<IAccount> accountsInCache = pca.getAccounts().join();
IAccount account = someFilter(accountsInCache);

IAuthenticationResult result;
try {
    //Look for an access token that matches the account and scopes originally used to get the token.
    //  This will return either the original token, or a refreshed one if the original expired
    SilentParameters silentParameters = SilentParameters .builder(someScopes, account).build();

    result = pca.acquireTokenSilently(silentParameters).get();
} catch (Exception ex) {
    if (ex.getCause() instanceof MsalException) {
        //If the silent call fails, try to get to get it using some other auth method
        //  I just copied one of the client credential calls as an example, but this is the pattern for all auth flows
        ClientCredentialParameters clientCredentialParam = ClientCredentialParameters.builder(
                Collections.singleton(someScopes))
                .build();
    	
        result = app.acquireToken(clientCredentialParam).get();
    } else {
        // Handle other exceptions accordingly
        throw ex;
    }
}

//Once you have the access token, use it to call MS Graph or anything else that the access token gives you permission to use
```

**Comment by prateek-narsinghani** [comment]
Using the client secret credentials, I tried sending a message to a channel but got error 
`"Message POST is allowed in application-only context only for import purposes. Refer to https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams for more details."`
I have the teamwork.migrate.all permission on my app. Can you please let me know what am I missing here?

**Comment by Avery-Dunn** [comment]
Earlier you said you were trying to create a bot which can "send some custom notifications to a channel", but that error message seems to be about the API for migrating messages into teams. From [the doc](https://learn.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&tabs=http) you linked earlier: "Note: Application permissions are only supported for [migration](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams)", and the linked doc on migration is all about importing chat history and whatnot from some other system into Teams.

One thing to pay attention to when setting the permissions is to look at whether they are [delegated or application permissions](https://learn.microsoft.com/en-us/azure/active-directory/develop/permissions-consent-overview#types-of-permissions). For example, that 'Teamwork.Migrate.All' application permission would be used in a scenario where you have application-wide credentials (such as those used in the client credentials flow), whereas the 'ChannelMessage.Send' delegated permission would be used in a scenario where you have specific user credentials (in this case the 'user' would be some account you set up to act like a bot, and you'd use basically any [flow](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows) except client credentials). 

Most of the permissions about sending messages seem to be delegated permissions. I'm not too familiar with the Graph API or Teams side of things, but I assume that means you'd need to set up some 'bot' user and make those Graph calls using it's credentials, and use one of the flows that deals with individual users ([username/password](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/IPublicClientApplication.java#L16) would probably be the simplest to set up and test, but isn't that secure so for production I'd recommend something else). [This doc ](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?tabs=dotnet#proactive-app-installation-in-teams) might also be relevant for what you're trying to do.

**Comment by prateeknarsinghani** [comment]
@Avery-Dunn thanks for your help. I found a way to send messages using the bot SDK of Java. Still have some challenges to face but your last comment helped me to think of other solution as I didn't want to set up a bot user.
Once again thanks for your help!

**Comment by Avery-Dunn** [comment]
Glad to hear things are working, and if you have any other questions feel free to leave more comments or open up new threads.
