### ISSUE TITLE
Log exact urls being called by acquireTokenSilentAsync?

### ISSUE THREAD

**Issue by unhammer** [AzureAD/microsoft-authentication-library-for-java#613]
We're trying to upgrade our signin policy for use in our android app, but in the new version we're not getting an extra field that used to be there (a list of emails) from the refresh response, only the login response. But we do get it from our test client that uses 

`https://foo.b2clogin.com/foo.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_SIGNIN&client_id=…&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ms&scope=openid&response_type=id_token&prompt=login`

for login and without `&prompt=login` for refresh:

`https://foo.b2clogin.com/foo.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_SIGNIN&client_id=…&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ms&scope=openid&response_type=id_token`

Is it possible from our android app to log the exact urls msal4j uses so we can compare what's going wrong?

We're fetching tokens with `IMultipleAccountPublicClientApplication.acquireTokenSilentAsync`. I've tried 

```java
import android.util.Log;
import com.microsoft.identity.client.Logger;
import com.microsoft.identity.client.ILoggerCallback;
…
        Logger.getInstance().setEnableLogcatLog(true);
        Logger.getInstance().setEnablePII(true);
        Logger.getInstance().setExternalLogger(new ILoggerCallback()
            {
                @Override
                public void log(String tag, Logger.LogLevel logLevel, String message, boolean containsPII)
                    {
                        Log.d("microsoftb2cuser", logLevel + ":" + tag + ":" + message);
                    }
            });
```

which logs things like `realm is not returned from server. Use utid as realm` but it shows no urls.

**Comment by siddhijain** [comment]
Thanks for your question @unhammer. From the code above, it does not look like you are using msal java that our team supports. can you confirm which msal you are using? Are you using Azure Identity library directly which uses msal java under the hood?

**Comment by unhammer** [comment]
my build.gradle has
`implementation 'com.microsoft.identity.client:msal:2.0.12'`
– is that a different repo?

**Comment by siddhijain** [comment]
Yes I believe that is msal-android. You can raise a github issue here https://github.com/AzureAD/microsoft-authentication-library-for-android

**Comment by unhammer** [comment]
OK, thanks for clearing that up, [raised](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1787)
