### ISSUE TITLE
[Feature Request] Add App service managed identity with initial managed identity work

### ISSUE THREAD

**Issue by DidunAyodeji** [AzureAD/microsoft-authentication-library-for-java#616]
Add IMDS managed identity source.

- [x] Add initial managed identity code 
- [x] Add code for App service source
- [x]  Test the flow manually
- [ ]  Add unit tests
- [x]  Add error handling

For more details see: https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/615

**Comment by Avery-Dunn** [comment]
Released as part of 1.14.2-beta
