### ISSUE TITLE
Proxy authentication with SSLTunnelSocketFactory does not work

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-java#62]
- Create an SSLTunnelSocketFactory
- Set SSLSocketFactory on the AuthenticationContext
- Make a call through a proxy that requires authentication

Two connect calls are made. The first one does not go through the proxy. If you manually set the proxy, the first call will error out with "HTTP/1.0 407 Proxy Authentication Required"

**Comment by navyasric** [comment]
This is replaced by this feature: https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/115
