### ISSUE TITLE
[Feature Request] Add Cloud Shell managed identity source to MSI Integration

### ISSUE THREAD

**Issue by DidunAyodeji** [AzureAD/microsoft-authentication-library-for-java#620]
Add Cloud Shell managed identity source.

- [x] Add code for Cloud Shell source
- [ ] Add unit tests 
- [x] Add error handling 
- [ ] Manual testing

For more details see: #615

**Comment by Avery-Dunn** [comment]
Released as part of 1.14.2-beta
