### ISSUE TITLE
Cannot bypass account selection prompt

### ISSUE THREAD

**Issue by kilokili777** [AzureAD/microsoft-authentication-library-for-java#621]
I installed the MSAL Java Servlet example. It basically works, however when I click on the "Sign In" button it sends me to https://login.microsoftonline.com/ to present a prompt "Pick an account" (only 1 account listed). I can select my account manually and then it let's me into the MSAL sample app "You are signed in" page. (I should also note, that for the first time after clicking the account, it sends me to a MFA page, but not subsequent logins)

I tried to recompile the AuthHelper.java by removing prompt(Prompt.SELECT_ACCOUNT) but no effect. I also tried prompt(Prompt.NONE) but this generates a value not found error despite being listed in the API.

AuthorizationRequestUrlParameters parameters = AuthorizationRequestUrlParameters
                .builder(Config.REDIRECT_URI, Collections.singleton(Config.SCOPES)).responseMode(ResponseMode.QUERY)
                .prompt(Prompt.NONE).state(state).nonce(nonce).build();

Reference Stackoverflow:
https://stackoverflow.com/questions/75801146/msal-java-servlet-example-how-to-avoid-sign-in-button-prompting-pick-an-accoun

QUESTION: How can I configure it to not prompt me to pick my account since there is only 1 account? (And avoid the MFA page?)

https://github.com/Azure-Samples/ms-identity-msal-java-samples/tree/main/3.%20Java%20Servlet%20Web%20App%20Tutorial/1-Authentication/sign-in

I expected to click on "sign in" and for it to authenticate and redirect to main app index page. Instead, it asks me to select which windows account, and then if the first time, will also issue a MFA page.

**Comment by Avery-Dunn** [comment]
Hello @kilokili777 : For an interactive request, there is a [loginHint](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/InteractiveRequestParameters.java#L57) parameter that can be used to pre-fill the username/email section on the Microsoft login page ([domainHint](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/InteractiveRequestParameters.java#L65) is also needed in a multi-tenant setup). If you fill this in with a user's email address it should skip the "pick an account" prompt, however I don't believe there's a way to skip the prompt automatically when there's only one option.

As for MFA, I don't think there's a way to skip it. MFA policies are handled by Azure AD (or other identity providers), so if a user has MFA set up for their account then the prompt for it will show up. As you saw though this won't happen every time a user tries to log in: as long as their [tokens ](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Acquiring-Tokens) are valid your application can use them without needing users to re-enter credentials, so users shouldn't need to see login screens or go through MFA that often.

**Comment by bgavrilMS** [comment]
`I also tried prompt(Prompt.NONE) but this generates a value not found error despite being listed in the API.` - this sounds like a bug.

There is no way to bypass MFA from MSAL. You or your tenant admin can configure a user or the entire tenant to not have MFA. 
Your app must be prepared to handle MFA, in case the tenant admin adds it.

**Comment by kilokili777** [comment]
@Avery-Dunn : Thank you! I was able to test by manually coding a username and domain hint as below and it worked, the user was logged right in without being prompted to select his account..... **BUT now how can I get the browser to pass the logged in windows username so I can populate the loginHint?**

`AuthorizationRequestUrlParameters parameters = AuthorizationRequestUrlParameters
                .builder(Config.REDIRECT_URI, Collections.singleton(Config.SCOPES)).responseMode(ResponseMode.QUERY)
                .loginHint("user1@test.com").domainHint("test.com").state(state).nonce(nonce).build();`

**Comment by Avery-Dunn** [comment]
Sorry for the delayed response on this, but in case you're still having trouble with this I'm not sure how to get the 'browser' to pass you the logged in username. MSAL Java can make requests, parse responses, and handle redirects, but it doesn't really have any view over what a user is seeing or doing on a particular page.

Once a user successfully logs in you'll have their username (`AuthenticationResult.account.username()`) and this is also in the token cache, so for each user's session you should be able to populate loginHint with that info.

**Comment by Avery-Dunn** [comment]
Closing this thread due to inactivity. If you're still having issues or have any related questions, feel free to leave a comment or re-open.

**Comment by siddhijain** [comment]
@Avery-Dunn Lets use this issue or create another to track the bug that Bogdan reported above - "I also tried prompt(Prompt.NONE) but this generates a value not found error despite being listed in the API. - this sounds like a bug."
