### ISSUE TITLE
how to validate oidc id_token?

### ISSUE THREAD

**Issue by noebrito** [AzureAD/microsoft-authentication-library-for-java#627]
Hey there!

I am implementing a flow where my server receives an adfs oidc id_token and I need to verify it before continuing with additional business logic. Is there a part of the library I am missing where I provide it the token and it performs the verification? Everything I am seeing is how to acquire a new token based on client credentials. I was looking for something similar to the okta and google libraries where it'll perform the basic claim checks and then make a http request to fetch the public keys and perform a signature check.

Thanks!

**Comment by siddhijain** [comment]
MSAL Java is a token acquisition library. So, unfortunately, the token verification/validation do not happen as part of the acquisition process. I know a team is working on creating a Java library that validates tokens, but it is not available yet. We will let you know once it is available. Let us know if you have any other questions.

**Comment by noebrito** [comment]
Thanks for the response!
