### ISSUE TITLE
Support for interactive authentication using OS default browser

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-java#64]

**Comment by hbjamil** [comment]
Any idea when this issue will be resolved ?

**Comment by sangonzal** [comment]
@hbjamil This will make it into release 1.4, which should be available next week. 

Still testing, but the default approach will probably use [java.awt.desktop](https://docs.oracle.com/javase/9/docs/api/java/awt/Desktop.html). This will  be configurable, and you will be able to provide your own logic to open the browser. The behavior and API will be very similar to MSAL.NET, [described here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively), except for that we don't support any of the mobile platforms.
