### ISSUE TITLE
Authenticating user in spring using azure AD

### ISSUE THREAD

**Issue by chillforever** [AzureAD/microsoft-authentication-library-for-java#660]
Hello, I'm working on implementing 'login with microsoft' functionality in our own oauth server. I have followed below instruction to make it to work: https://www.baeldung.com/spring-boot-azuerad-authenticate-users

It's fine as long as it is for users from particular tenant id. What i need here is to configure it for multitenant case as well as for private account. 

my current configuration is:

``` security:
    oauth2:
      client:
        registration:
         azure:  
            provider: azure  
            client-id: <client-id>
            client-secret: <client-secred>
            scope: openid, profile, email  
            authorization-grant-type: authorization_code  
        provider:  
          azure:  
            authorization-uri: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"  
            token-uri: "https://login.microsoftonline.com/common/oauth2/v2.0/token"  
            user-info-uri: "https://graph.microsoft.com/oidc/userinfo"  
            issuer-uri: "https://login.microsoftonline.com/<tenant-id>/v2.0"
```

I have tried to replace <tenant-id> with common but then i'm getting exceptions and my server is unable to start. Can you provide me with right configuration for such a case?

**Comment by Avery-Dunn** [comment]
Hello @chillforever : Just to confirm, you're just using the `spring-boot-starter-oauth2-client` and `org.springframework.boot` dependencies described in that Baeldung tutorial, right? If so those aren't our products so we can't help much.

What's the error message you're getting? Are you using MSA Java at all? If it's an error I've seen before I might be able to help out, but you might have better luck asking in the [Spring Boot](https://github.com/spring-projects/spring-boot) Github repo.

Microsoft has a series of Azure Spring products ([com.azure.spring](https://mvnrepository.com/artifact/com.azure.spring) on Maven) that you can look into, and issues for that can generally be posted in the [Azure SDK for Java](https://github.com/Azure/azure-sdk-for-java/tree/main) Github repo.

**Comment by Avery-Dunn** [comment]
Closing due to lack of response. If you're still having issues or have other questions, feel free to re-open this thread or start a new one.
