### ISSUE TITLE
Errors is logged and thrown at the same time in AuthenticationResultSupplier resulting in handled exceptions still being logged as errors

### ISSUE THREAD

**Issue by snussbaumer** [AzureAD/microsoft-authentication-library-for-java#662]
In [AuthenticationResultSupplier, lines 98-99](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/fe7e69cc645260655a12684f1a23f3367e83fd89/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AuthenticationResultSupplier.java#L98-L99) we see :  
```java
    logException(ex);
    throw new CompletionException(ex);
```

[logException](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/fe7e69cc645260655a12684f1a23f3367e83fd89/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AuthenticationResultSupplier.java#L155) can in certain cases log an error with `clientApplication.log.error(logMessage, ex);`

This means that even when the exception is properly handled by the calling code (which we do) there is still a remaining error in the logs.

We have this problem and people end up investigating an issue that is not there. 

For the time being we completely disabled logging for ConfidentialClientApplication ... but it would be much preferable that the error log not be done at all (or at least that this logging could be disabled when building the ConfidentialClientApplication)

**Comment by Avery-Dunn** [comment]
Hello @snussbaumer : I plan on looking into why we do that a bit more, but after a quick look I agree it doesn't make sense to both throw an exception and log it at an 'error' level.

In our next release, this will likely be changed to log those errors at a 'debug' level like the other exceptions in that `logException` method. I don't have an ETA on that, but will update this thread once we do.

**Comment by Avery-Dunn** [comment]
As of the latest 1.14.1 release, this info is now logged at the 'debug' level and we don't unnecessarily print out the stack trace, so logs should raise fewer flags and be less verbose.
