### ISSUE TITLE
[BUG] [Repair Item] Remove client timeouts for connecting to the STS

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-java#664]
Today, MSAL Java times out after 15s. This timeout should be removed. AAD has its own timeouts which are not public.

**Comment by Avery-Dunn** [comment]
This was fixed as of https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/684, and part of the 1.13.10 release.
