### ISSUE TITLE
Refactor code to hide APIs that are not relevant for managed identity. For more information see design doc

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-java#688]
Refactor the code to hide APIs not supported for managed identity. For more information see [design doc](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=/ManagedIdentity/ManagedIdentity.md&_a=preview&anchor=msal-apis-that-should-either-be-disabled-or-no-op-with-managed-identity).

**Comment by Avery-Dunn** [comment]
Completed a while back, and released as part of 1.14.2-beta
