### ISSUE TITLE
Document manual testing for cloud shell / service fabric

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-java#695]
Since integration tests do not cover cloud shell and service fabric flow, document how to test these manually.

Reference: 
* [Manual testing steps for cloud shell](https://microsoft.sharepoint.com/teams/ADAL/_layouts/OneNote.aspx?id=%2Fteams%2FADAL%2FSiteAssets%2FDevEx%20Notebook&wd=target%28ID4S%2FMSALs%2FTechnical%2FMSI.one%7CA2A57687-9A17-4C9E-86D1-60AA32AB5005%2FTest%20Managed%20Identity%20on%20Azure%20Cloud%20Shell%7C2864DAE8-64AA-4251-BF74-E181679F8221%2F%29)

**Comment by bgavrilMS** [comment]
Can we reuse the manual testing docs from MSAL.NET?

**Comment by neha-bhargava** [comment]
> Can we reuse the manual testing docs from MSAL.NET?

No, MSAL.Net testing was primarily done using Visual Studio. 
* The cloud shell part of manual testing should be similar to what we do for .Net
* For service fabric Visual Studio was able to create the resources and publish the app. Need to explore if this can be achieved in IntelliJ or CLI. Using CLI for service fabric was not straight forward.

**Comment by bgavrilMS** [comment]
CLI would be better, as we could reuse it for MSAL JS
