### ISSUE TITLE
Upgrade to non-vulnerable version of logback-classic

### ISSUE THREAD

**Issue by Avery-Dunn** [AzureAD/microsoft-authentication-library-for-java#704]
The version of logback-classic we use to view logs in our tests ([1.2.3](https://mvnrepository.com/artifact/ch.qos.logback/logback-classic/1.2.3) in MSAL Java, [1.2.11](https://mvnrepository.com/artifact/ch.qos.logback/logback-classic/1.2.11) in the msalruntime interop) has vulnerabilities. This dependency is only used for testing so the vulnerability shouldn't affect our customers, however it can still potentially raise flags in various build tools.

**Comment by bgavrilMS** [comment]
Can you take a dependency on the latest minor version of every test dependency? This seems like a never ending battle.
