### ISSUE TITLE
Create a QuickStart sample

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-java#72]
Create a quick start, concept to be found here:

Javascript qs, notice how we are using tags for what goes to the portal and docs.
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-javascript

The md file from docs and convert it into HTML based on the tags for it to surface in portal.
Detailed instructions shared internally.

**Comment by jmprieur** [comment]
@sangonzal : this is done?

**Comment by jmprieur** [comment]
closing as duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/89
cc: @sangonzal @henrik-me
