### ISSUE TITLE
Write CIAM Samples

### ISSUE THREAD

**Issue by DidunAyodeji** [AzureAD/microsoft-authentication-library-for-java#724]
Let's aim for 3 samples:

- [x] [P0] sign into a web site (Java servlet)
- ~[P2] sign into a cli application~
- [x] [P2] sign into a web site with CIAM, call protected web api (see https://github.com/Azure-Samples/ms-identity-msal-java-samples/blob/main/4-spring-web-app/3-Authorization-II/protect-web-api/resource-api/src/main/java/com/microsoft/azuresamples/msal4j/msidentityspringbootwebapi/SecurityConfig.java)

https://github.com/Azure-Samples/ms-identity-ciam-dotnet-tutorial/tree/main/1-Authentication

CC @DidunAyodeji @localden

**Comment by bgavrilMS** [comment]
Dropping the public client app.

**Comment by Avery-Dunn** [comment]
Resolved with https://github.com/Azure-Samples/ms-identity-msal-java-samples/pull/51 for the sign-in sample, and https://github.com/Azure-Samples/ms-identity-msal-java-samples/pull/53 for the web API sample
