### ISSUE TITLE
IAuthenticationResult should expose refresh token

### ISSUE THREAD

**Issue by zvrba** [AzureAD/microsoft-authentication-library-for-java#73]
I have a scenario where the application is divided into two desktop programs: a front-end UI and a back-end worker. With ADAL4J, refresh token is exposed in authentication result, which is then passed to the backend through an environment variable. There is no easy way of doing this with MSAL4J. The workaround with serializing the token cache to JSON and reading the refresh token from there is rather cumbersome.

**Comment by henrik-me** [comment]
Hi @zvrba , We are generally not recommending using the refresh token. The library takes care of refreshing as appropriate. Can you pls. share additional information on your use case? It seems like you may benefit from using the obo flow instead.

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow

**Comment by zvrba** [comment]
Hi,

A single application (desktop, native client) is split into two parts: interactive front-end (written in Java) and batch back-end (written in C#/netcore). The front-end logs in the user interactively and then it passes the tokens to the back-end. The back-end must continue to run non-interactively in the background without the user present. ObO would be possible, but it seems less secure since the back-end must be configured with the application secret. It will be installed on a shared network folder and used by many users across many computers in a cross-platform environment (OSX and Windows). In this case it's difficult to protect the secret. In a config file, it'd be readable for anyone, while hard-coding it in the executable is security by obscurity at best.

Is the token cache serialization format compatible between MSAL for C# and MSAL4J? If so, I could serialize it to disk from the front-end to a temporary file, deserialize it from the back-end and securely delete the file.

**Comment by sangonzal** [comment]
@zvrba You are right in that you should not be putting a secret on a native client, and therefore OBO is not appropriate in this case. It seems to me that your best option is to serialize the token cache. Token cache serialization format is compatible in between MSAL.NET and MSAL4J, so you can share cache in between both of your applications.

**Comment by henrik-me** [comment]
@zvrba: Not sure I fully understand. Is this a single user application which has background processing (.net) and a front-end (java)? That is this is not a service, it's rather a single application? How is the background processing happening (does it run in the user context)?

**Comment by zvrba** [comment]
> Is this a single user application

No, it will be used by multiple users. Each user will log on with their own credentials.

> which has background processing (.net) and a front-end (java)? That is this is not a service, it's rather a single application?

Correct, it's a single application comprised of two separate processes; this is out of pure necessity since .netcore doesn't have a cross-platform UI framework (3rd party frameworks don't seem mature enough).

> How is the background processing happening (does it run in the user context)?

Background processing accesses all resources as the user that logged on to the front-end. E.g., if `someone@xy.onmicrosoft.com` logs in through the front-end, the back-end must continue using this identity to further use remote services (e.g., logging on to Azure SQL database using token).

**Comment by sangonzal** [comment]
@zvrba Did this answer your question? Can I go ahead and close this issue or did you have any other questions?

**Comment by zvrba** [comment]
I have yet to try exchanging the serialized cache between MSAL.NET and MSAL4J. You can close this issue and if MSAL.NET <> MSAL4J for some reason doesn't work, I'll open a new issue. Thanks.
