### ISSUE TITLE
[Feature Request] MSAL Java support for CIAM custom authority

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-java#732]
### MSAL client type

Public, Confidential

### Problem Statement

CIAM will support custom authorities, which will require MSAL to perform OIDC discovery of the endpoints.

Blocked until we have a test environment.

### Proposed solution

Recommendation is for MSAL to add support to WithGenericAuthority for user flows (consider renaming to WithOidcAuthority).

Since this is a general-purpose mechanism, we should also try to use a non-Microsoft authority, such as Facebook or Google. Concern is that client_info missing will mess up token caching logic

**Comment by Avery-Dunn** [comment]
Support added in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/851 and released in 1.17.0
