### ISSUE TITLE
The latest release is released with wrong version.

### ISSUE THREAD

**Issue by OleksandrShkurat** [AzureAD/microsoft-authentication-library-for-java#742]
### Library version used

1.14.0

### Java version

17

### Scenario

Other - please specify

### Is this a new or an existing app?

None

### Issue description and reproduction steps

The latest release 1.14.0 has released as version 1.14.10 instead of 1.14.0
At the same time the tag name is correct.

### Identity provider

Other

**Comment by bgavrilMS** [comment]
Thanks for reporting. 

Best thing to do is in these cases is to move forward, e.g. release MSAL 4J 1.14.11 or 1.15.0 to avoid confusing the dev tools.

**Comment by Avery-Dunn** [comment]
Hello @OleksandrShkurat : I believe this mistake of having 1.14.**10** was only in the Github release page, which is more about information regarding releases and I've just corrected it: https://github.com/AzureAD/microsoft-authentication-library-for-java/releases/tag/v1.14.0

If you look at the actual pom.xml file used for the build it's correctly 1.14.**0**: https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/d4b5096f9e7926fb491978b45599dc96b46f8f83/msal4j-sdk/pom.xml#L6

And if you look in Maven's repository it is also listed as 1.14.**0**, and there is no 1.14.**10**: https://mvnrepository.com/artifact/com.microsoft.azure/msal4j/1.14.0

So overall this thankfully just seems like a documentation issue, and you should be able to reference msal4j 1.14.**0** as a dependency in your projects.

**Comment by Avery-Dunn** [comment]
Closing as this seems to have been a documentation issue that is now fixed. If you're still running into issues or have any other questions, feel free to re-open this thread or start a new one
