### ISSUE TITLE
SSHHandshakeException: PKIX Build failed.

### ISSUE THREAD

**Issue by dbschema-pro** [AzureAD/microsoft-authentication-library-for-java#743]
### Library version used

1.14.3-beta

### Java version

OpenJDK 19

### Scenario

ConfidentialClient - web site (AcquireTokenByAuthCode)

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

I try to connect to AzureSQL using the beta release of msal4j, I got the exception as in the image.
Is this a bug in the msal4j or some error on my side?
I am using OpenJDK 19.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by dbschema-pro** [comment]
![image](https://github.com/AzureAD/microsoft-authentication-library-for-java/assets/60284259/52bedef9-727f-42c4-aec4-037a065ac0d6)

**Comment by Avery-Dunn** [comment]
Hello @wise-coders : Are you using MSAL Java directly in your application? That error seems to be coming from a SQL Server or JDBC package that uses our msal4j package.

If you aren't using the msal4j package directly, then this likely a configuration issue or problem on the SQL/JDBC side. This exact error is mentioned in this post on the Azure Database Support Blog, and suggests there's an issue with the keystore: https://techcommunity.microsoft.com/t5/azure-database-support-blog/pkix-path-building-failed-unable-to-find-valid-certification/ba-p/2591304
