### ISSUE TITLE
[Question] Is login_hint optional claim flow supported similar to msal.js?

### ISSUE THREAD

**Issue by tclausing** [AzureAD/microsoft-authentication-library-for-java#775]
Goal: silently acquire a token using the `login_hint` optional claim pattern as documented in msal.js [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#with-user-hint).

`acquireTokenSilently` looked encouraging but per javadoc it's only a cache fetch/refresh, and `SilentParameters` doesn't accept a `loginHint`. `AuthorizationRequestUrlParameters` and `InteractiveRequestParameters` do but they don't seem to apply to a "silent" flow in the server-side sense (without a redirect/popup).

Is the `login_hint` optional claim pattern possible as a "silent" server-side-only solution (or a possible enhancement) with msal4j?

**Comment by Avery-Dunn** [comment]
Hello @tclausing : In MSAL Java login hint is not supported for the silent flow, it only allows the [Account](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/Account.java) object commonly returned in the [AuthenticationResult](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AuthenticationResult.java). 

However, some other MSALs allow login hints to be passed in so we'll discuss adding it and I'll update this thread once I have more info. In the meantime, as a workaround you could use the [getAccounts](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/747eb0046ba5c083003030c2d31ec86fd1461d2e/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/IClientApplicationBase.java#L117) API to get the list of cached accounts, sort through them based on the account's username, and then pass in the correct account to the silent flow:
```Java
//assuming you have a public client app named 'app' that you've been getting tokens with
Set<IAccount> accountsInCache = app.getAccounts().join();

//In a public client scenario each session should have a small number of accounts, so this will be a quick search
while(accountsInCache.iterator().hasNext()) {
  account = accountsInCache.iterator().next()
  if (account.username().equals(someLoginHint)) { 
    //break loop and anything else you want to do with the account
  }
}

SilentParameters silentParameters = SilentParameters.builder(someScopes, account).build()
```
