### ISSUE TITLE
[Bug] Msal Persistence extension uses old dependencies, update them and release it.

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#777]
### Library version used

1.2.0

### Java version

JDK 17

### Scenario

Other - please specify

### Is this a new or an existing app?

None

### Issue description and reproduction steps

Msal4j Persistence extension is using old version of msal4j dependency and other dependencies.
Update it to latest use msal4j and release it. Update any other dependencies it uses to their latest version as well.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
@Avery-Dunn - isn't the extension released with every MSAL version? IMO we should release it in a similar fashion as the broker package (same repo, same version etc.)

**Comment by Avery-Dunn** [comment]
@bgavrilMS : No, the extensions package has always been in a separate repo, and looking at it now has gotten very out of date: https://github.com/AzureAD/microsoft-authentication-extensions-for-java

It was before my time on the team so I don't know the reason for it being separate. However, I think it would make sense to move it to this repo (Maven allows [relocating projects](https://maven.apache.org/guides/mini/guide-relocation.html)) and following what we did for the broker package (though we'd need to find any docs and other references first)

**Comment by Avery-Dunn** [comment]
Forgot to close this at the time, but in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/807 the extensions package was moved to this repo, and a new [1.3.0 version](https://mvnrepository.com/artifact/com.microsoft.azure/msal4j-persistence-extension/1.3.0) was released to update the dependencies.
