### ISSUE TITLE
Update documentation for MSI Java

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-java#792]
Update MSI documentation here: https://github.com/Azure-Samples/msal-managed-identity/tree/main/src when the sample is ready with the link and latest updates before GA

Link to MSI Java documentation: [Managed identity with MSAL Java - Microsoft Authentication Library for Java | Microsoft Learn](https://learn.microsoft.com/en-us/entra/msal/java/advanced/managed-identity)

**Comment by bgavrilMS** [comment]
Duplicate of #694
