### ISSUE TITLE
[Feature Request] Need an API for Managed Identity to detect the current environment

### ISSUE THREAD

**Issue by rayluo** [AzureAD/microsoft-authentication-library-for-java#815]
### MSAL client type

Managed identity

### Problem Statement

Please refer to the "MSAL implementation" part of [this internal PR](https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?version=GBdev&path=/ManagedIdentity/FacilitateImdsProbing.md&_a=preview&anchor=msal-implementations).

**Comment by Avery-Dunn** [comment]
Done as part of https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/823 and released in version 1.15.1
