### ISSUE TITLE
[Bug] Release notes and git tag for version released on Maven Central is missing

### ISSUE THREAD

**Issue by reftel** [AzureAD/microsoft-authentication-library-for-java#825]
### Library version used

1.15.1

### Java version

N/A

### Scenario

Other - please specify

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

On https://mvnrepository.com/artifact/com.microsoft.azure/msal4j , a version 1.15.1 is listed, but there is no git tag on https://github.com/AzureAD/microsoft-authentication-library-for-java/tags nor release notes on https://github.com/AzureAD/microsoft-authentication-library-for-java/releases .

### Identity provider

Other

**Comment by bgavrilMS** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/changelog.txt

**Comment by Avery-Dunn** [comment]
The tag and release notes have now been made: https://github.com/AzureAD/microsoft-authentication-library-for-java/releases

**Comment by reftel** [comment]
Thank you!
