### ISSUE TITLE
Add Support for Object ID in Managed Identity Client

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#853]
## Add Support for Object ID in MSAL Java

**Background**: It was identified that MSAL Java currently lacks support for Object ID, which is crucial for enabling scenarios that require Object ID for authentication and identity management. This feature is already supported in other languages like .NET and Python, highlighting a gap in the Java implementation.

**Motivation**: The primary motivation for adding Object ID support in MSAL Java stems from the need to authenticate and manage identity using Object ID in various Microsoft services. The lack of Object ID support in MSAL Java limits the ability to implement consistent identity management solutions across different programming languages.

**Requirements**:

* Implement Object ID support in MSAL Java MI client, allowing users to authenticate using Object ID.
* Ensure compatibility with existing authentication mechanisms to minimize impact on current users.
* Provide clear documentation and examples on how to use Object ID for authentication in Java applications.

**Justification**: Adding Object ID support will bring MSAL Java in line with other language implementations, ensuring a consistent and unified approach to identity management across Microsoft services. This feature is critical for enabling secure and efficient identity management solutions.

**Comment by g2vinay** [comment]
@localden

**Comment by Avery-Dunn** [comment]
Support added in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/854 and released in 1.17.0
