### ISSUE TITLE
[Feature Request]     Bump jackson dependency due to possible CVE

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-java#882]
### MSAL client type

Public, Confidential, Managed identity

### Problem Statement

See https://github.com/FasterXML/jackson-databind/issues/3972 for details. While it is disputed, it is being taken into account by some compliance tools. Better to just upgrade. 

Applicability to MSAL is very low, as MSAL only parses JSON that comes from the identity provider.

### Proposed solution

Bump jackson-databind from 2.13.4.2 to 2.18.1 or higher

**Comment by bgavrilMS** [comment]
@Avery-Dunn - can you please include this in the next MSAL 4j release?

**Comment by Avery-Dunn** [comment]
Just created a PR to resolve this: https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/887

It will definitely be in the next release, which should be out by the end of this week.

**Comment by Avery-Dunn** [comment]
The fix for this was released as part of [1.18.0](https://mvnrepository.com/artifact/com.microsoft.azure/msal4j/1.18.0).
