### ISSUE TITLE
[Bug] AzureArcManagedIdentitySource looking for WWW-Authenticate response header while agent returns Www-Authenticate

### ISSUE THREAD

**Issue by blancqua** [AzureAD/microsoft-authentication-library-for-java#884]
### Library version used

1.17.2

### Java version

21

### Scenario

Other - please specify

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

I am trying to log in my application running on an Azure Arc enabled Ubuntu 24.04 server. In the class AzureArcManagedIdentitySource, there is a check for existence of the WWW-Authenticate header. However, my agent returns the header without capitals: Www-Authenticate (see image).

![image](https://github.com/user-attachments/assets/ca2ec857-7be8-4387-ac9d-f3b108a9affd)

I see the code used to check for Www-Authenticate but this changed with this commit: https://github.com/AzureAD/microsoft-authentication-library-for-java/commit/68bba5168b61726afd8ca223e70a54062ad09c01

### Expected behavior

I expect my application to log in via the Azure Arc Managed Identity.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

1.15.0

### Solution and workarounds

I assume best option would be to make the check case-insensitive...

**Comment by blancqua** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/885

**Comment by Avery-Dunn** [comment]
The fix for this was released as part of [1.18.0](https://mvnrepository.com/artifact/com.microsoft.azure/msal4j/1.18.0), thanks again for making the fix!
