### ISSUE TITLE
Add helper to create authorization code endpoint URL

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-java#95]
Add helper method for crafting the URL for the authorization code endpoint.

**Comment by jmprieur** [comment]
@sangonzal 
Suggesting the following spec: **GetAuthorizationRequestUrl(scopes)**
the Java equivalent to https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.confidentialclientapplication.getauthorizationrequesturl?view=azure-dotnet
