### ISSUE TITLE
what to with tokenCache, how to get a new token for web app

### ISSUE THREAD

**Issue by ZuperKeurZ** [AzureAD/microsoft-authentication-library-for-java#98]
I'm writing a webapp, where I want to use the msgraph api on a user's behalf even if that user is offline.

For This I'm using the authorization code flow. 

Everything is working fine so far. I redirect the user to the login page, and on return get the AuthenticationResponse. This response I use to get an IAuthenticationResult that I can use to access the msgraph api.

I serialize the TokenCache and store in the db. 

Whenever I need to call msgraph later I create a new ConfidentialClientApplication and deserialize the TokenCache. 

As far as I can see, all documentation and issues point in the direction of using the authorization code flow again. This way msal4j will automatically request a new refresh token if necessary or return the one in the cache if it still valid.

But i can not find an answer on what I should put in the AuthorizationCodeParameters. In the flow you are supposed to use the refresh token for this. But there is no way to extract the refreshtoken from the TokenCache.

please help, I got this far on my own but can't find any info on what to put in there.

```
ConfidentialClientApplication clientApplication = ConfidentialClientApplication.builder(msGraphConfiguration.getClientId(), new ClientSecret(msGraphConfiguration.getClientSecret())).build();
clientApplication.tokenCache().deserialize(serializedTokenCache);

clientApplication.acquireToken(AuthorizationCodeParameters.builder("WHAT TO PUT HERE?", getRedirectUrlAsUrl()).build()).get();
```

**Comment by jmprieur** [comment]
Once you have serialized the cache, you can just call acquireTokenSilent to get a token.

**Comment by ZuperKeurZ** [comment]
@jmprieur, Excellent, thank you very much!

I was mixed up with the public client and expected the silent flow to expect a browser where the user was still logged in in the back.

For anyone else encountering this problem.
The original IAuthenticationResult contains the IAccount that needs to be passed in the SilentParameters. You can serialize and deserialize this IAccount using the methods in the AccountCacheEntity class and store them as u do with TokenCache.

```
    static AccountCacheEntity create(String clientInfoStr, String environment, IdToken idToken){
        return create(clientInfoStr, environment, idToken, null);
    }

    IAccount toAccount(){
        return new Account(homeAccountId, environment, username);
    }
```

**Comment by sangonzal** [comment]
@ZuperKeurZ Just wanted to add to what you wrote, in case anyone else runs into this in the future. 

The recommended way of getting an account is to call the getAccounts() method on public client application. This will return `Set<IAccount>`, which then you can filter to the get the account which you would like to use in SilentParameters. We have a [wiki page](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Token-Cache) covering this topic. 

AccountCacheEntity should not be available to to be used outside the of package (it has a default modifier) so I'm not sure how you are using it here. Either way, in general we recommend only using the library through the public APIs. We try avoid making any breaking changes to the public API (and document them when introduced), but don't make any such promises for internal classes.
